### ISSUE TITLE
Standard access to kernel-level PRNGs

### ISSUE THREAD

**Issue by eu90h** [racket/racket#1062]
Many languages have a standard way to access random numbers generated from the operating system's  entropy pool. 

They seem to be invariably implemented in the same way: reading bytes from `/dev/urandom` on *nix based systems or calling Advapi32.dll's CryptGenRandom/RtlGenRandom on Windows systems. 
See for instance [Python](https://docs.python.org/2/library/os.html#os.urandom) or [Go](https://golang.org/src/crypto/rand/rand.go). 

The Racket [system](http://docs.racket-lang.org/reference/os.html?q=system) modules lack any such procedure for OS PRNG access. 

I have a patch which adds a procedure `(secure-random n)` which reads `n` random bytes from the OS PRNG. I would like to test it a little bit more (particularly on Windows), but it should be ready to go soon.

The proposed `secure-random` function has the added bonus of being cryptographically secure, unlike the already present `random` function. Interestingly, using the MRG32k3a PRNG (which is what Racket's `random` is) was the cause of Hacker News being [compromised](https://news.ycombinator.com/item?id=639976).

If you folks like the proposal, I'll post the patch here soon. 

Thanks to @lexi-lambda for suggesting the name `secure-random`

**Comment by rfindler** [comment]
This sounds great!

Does it make sense to use the word `system` in the name of the function?
Like system-random or something like that to indicate that it's coming from
the underlying OS?

**Comment by eu90h** [comment]
I believe that `secure-random` is best, as it makes the procedure more "self-documenting". 

If we went with `system-random` for instance, the programmer wonders "what's the difference between this and the normal `random`?". By naming it `secure-random`, the programmer need not wonder the difference. This point was convincingly argued by lexi-lambda in an IRC discussion.

I believe the documentation would be the best place to explain the source of randomness.

**Comment by rfindler** [comment]
Okay.

**Comment by jeapostrophe** [comment]
I feel pretty strongly that "secure-random" is a misleading name, because
it is very opinionated and "blesses" the function too much. There's no
reason that the OS is particularly secure and there are many instances of
mistakes in this part of OSes. I think a name like "system-random" is
perfectly apt: it is descriptive and you can use the documentation to
explain why you'd like to use it over others.

Jay

On Tue, Sep 15, 2015 at 9:12 PM, Robby Findler <notifications@github.com>
wrote:

> Okay.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plt/racket/issues/1062#issuecomment-140591823>.
>



-- 
Jay McCarthy
http://jeapostrophe.github.io

           "Wherefore, be not weary in well-doing,
      for ye are laying the foundation of a great work.
And out of small things proceedeth that which is great."
                          - D&C 64:33

**Comment by rfindler** [comment]
Is the goal of these random sources to be secure? (And we're just seeing
bugs (and then presumably fixes)?) Or is the design of these randomness
sources something else?

**Comment by lexi-lambda** [comment]
Jay, I see your point, but I disagree with that argument. I think `secure-random` is the clearest name because it expresses *intent*. All of the data sources are inherently intended to be secure. The OS may provide many random functions, but this only uses the ones specifically intended for secure/cryptographic use.

This isn't terribly unreasonable: consider the Ruby [SecureRandom](http://ruby-doc.org/stdlib-2.1.2/libdoc/securerandom/rdoc/SecureRandom.html) class. It lists the following potential sources:

> - openssl
> - /dev/urandom
> - Win32

None of these are internal to Ruby, of course, but that's probably for the best. Secure cryptography is notoriously hard, and the only way to get *any* semblance of security is to use the existing sources that have been proven over the years.

I think throwing out the term "secure" because there might be bugs is too idealistic. All software *might* have bugs, but whole industries depend on the fact that these pieces of software don't. The fact that any vulnerabilities make huge headlines (e.g. Heartbleed) is proof that they're overally pretty solid.

Calling a function `system-random` doesn't tell me anything at all (not even any more than the name `random`). I'd rather my code be self-documenting wrt intent than be 100% safe by avoiding a highly unlikely potential inaccuracy.

**Comment by rfindler** [comment]
I disagree about what the name `system-random` tells you. It says "this
uses the source of randomness on the machine where the program you're
writing is eventually run". That is a lot of information, IMO.

I googled around and found nothing that seemed authoritative, but got the
general sense that things like /dev/random aren't trying to guarantee real
sources of randomness, but instead use what entropy they have available
and, when they run out, fall back to PRNG algorithms.

So system-random is starting to sound better to me too.

**Comment by jackfirth** [comment]
dev/urandom is the preferred Unix source of cryptographically secure randomness. Most OS level sources of randomness are used *because* they have some actual source of entropy they can use, giving you true random numbers (as much as they can, if they run out of entropy for a request they fall back on standard PRNG methods). This does make calling them "secure" an apt term.

**Comment by rfindler** [comment]
I interpreted the "if they run out of entropy" clause as saying that they
weren't designed to be secure, but were more of a best effort. Is that the
wrong interpretation?

**Comment by jackfirth** [comment]
It's more "as secure as is practically feasible on this system" which, unless you're making a call to a web service that provides stronger guarantees, is probably the best you're going to get.

**Comment by eu90h** [comment]
Appeal to authority is a terrible way to argue, but I'd like to cite Daniel
J. Bernstein, Thomas Pornin, and Thomas Ptacek, whose arguments for
/dev/urandom being cryptographically secure are quoted in [this article](
http://www.2uo.de/myths-about-urandom/#experts) which discusses myths about
/dev/urandom.

Alexis brings up a crucial point which is the probability that someone
[misuses randomness](https://news.ycombinator.com/item?id=639976), thereby
introducing insecurities where none may have existed, is much higher than
the probability that /dev/urandom is insecure. This motivates the
suggestive name `secure-random`.

**Comment by eu90h** [comment]
Additionally, there is also precedent of the output of /dev/urandom being used directly to generate keys in cryptographic software. NaCl and LibreSSL both do this (and I'm sure others exist).

NaCl in particular is an extremely well-designed cryptographic library. It embodies best practices all around. As a result, I feel it wouldn't be disingenuous to call it `secure-random`.

**Comment by eu90h** [comment]
I'd like to post the patch [here](https://gist.github.com/eu90h/5dfd65a3aa1b276be49c) for initial review. I have another pull request open and apparently can't issue another one, so a gist will have to do. My plan is to place it the directory `racket/collects/file` for lack of a better place.

**Comment by jeapostrophe** [comment]
I am not convinced by these arguments for secure-random vs system-random. I
think that we should reserve a name like secure-random for something that
is known to be a cryptographically secure PRNG, such as Blum Blum Shub. All
we know about /dev/urandom is that "the operating system provided it" (so
in the case of Windows that probably means the NSA provided it) and that's
what a name like "system-random" communicates.

I think that naming the module with something like "file" is confusing
because it rolls the implementation in to the name too much. I think a new
"os" collection (like mzlib/os) or extension to the "racket/system" is the
right place.

In contrast, I feel like a "secure-random" would come from a "math"-related
collection, but since we know that this implementation has no math in it,
it's clear it's not an RNG implementation we really know anything about and
can vouch for, so that's not a good place for it.

Jay

On Wed, Sep 16, 2015 at 3:39 AM, Stefan <notifications@github.com> wrote:

> I'd like to post the patch here
> <https://gist.github.com/eu90h/5dfd65a3aa1b276be49c> for initial review.
> I have another pull request open and apparently can't issue another one, so
> a gist will have to do. My plan is to place it the directory
> racket/collects/file for lack of a better place.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plt/racket/issues/1062#issuecomment-140656900>.
>



-- 
Jay McCarthy
http://jeapostrophe.github.io

           "Wherefore, be not weary in well-doing,
      for ye are laying the foundation of a great work.
And out of small things proceedeth that which is great."
                          - D&C 64:33

**Comment by rfindler** [comment]
On Tue, Sep 15, 2015 at 9:17 PM, Stefan <notifications@github.com> wrote:

> http://www.2uo.de/myths-about-urandom/#experts)
>

Reading this webpage says to me that system-random is the right name. As
Jay writes, it sends the message that this random function is one that
comes from the system. I think the documentation can explain that it is
probably the best choice for cryptographically secure random numbers (and
we can say that in the docs for the other random functions, pointing to
system-random), but fundamentally all Racket can say about it is that it's
guarantees come from elsewhere.

**Comment by rfindler** [comment]
I agree that adding the function to `racket/system` is better than
something with the word "file" in it.

**Comment by samth** [comment]
I'm strongly in favor of the name 'secure-random'. As Jay says, that should
indicate use of a CSPRNG seeded with genuine randomness, which is exactly
what /dev/random is.

**Comment by jeapostrophe** [comment]
On Wed, Sep 16, 2015 at 8:06 AM, Sam Tobin-Hochstadt <
notifications@github.com> wrote:

> I'm strongly in favor of the name 'secure-random'. As Jay says, that should
> indicate use of a CSPRNG seeded with genuine randomness, which is exactly
> what /dev/random is.


On what platforms and where is this guarantee given? Will Racket ever be on
platform that doesn't provide such a guarantee? (say random Javascript
browsers) Are the algorithms that most OSes use actually proved to be
CSPRNGs or just "designed to be CSPRNGs"?

Jay

-- 
Jay McCarthy
http://jeapostrophe.github.io

           "Wherefore, be not weary in well-doing,
      for ye are laying the foundation of a great work.
And out of small things proceedeth that which is great."
                          - D&C 64:33

**Comment by rfindler** [comment]
On Wednesday, September 16, 2015, Sam Tobin-Hochstadt <
notifications@github.com> wrote:

> I'm strongly in favor of the name 'secure-random'. As Jay says, that should
> indicate use of a CSPRNG seeded with genuine randomness, which is exactly
> what /dev/random is.
>
>
>
The web claims otherwise, saying that it is best effort.

**Comment by rfindler** [comment]
Two other observations that point towards "system" being the most important
feature of this function than "secure":

- the implementation can raise the error "/dev/urandom does not exist".

- the names of the underlying sources do not have the name "secure" in
them.

**Comment by samth** [comment]
A bit (lot) longer on why I think this should be called `secure-random` (or something similar like `crypt-random`):

1. The underlying operations are genuinely aimed at secure operations. Here's a quote from the [kernel manpage for Linux](http://man7.org/linux/man-pages/man4/random.4.html):

 > If a seed file is saved across reboots as recommended below (all
       major Linux distributions have done this since 2000 at least), the
       output is cryptographically secure against attackers without local
       root access as soon as it is reloaded in the boot sequence, and
       perfectly adequate for network encryption session keys.

 @rfindler, I think what the web claims is that _genuine randomness_ is best-effort from  `/dev/urandom` -- when entropy is low, a cryptographically-secure PRNG is used to generate more bits.

 Here's the Mac page:

 >  The random device implements the Yarrow pseudo random number generator algorithm

 [Yarrow](https://www.schneier.com/yarrow.html) is, according to its web page, "a secure pseudorandom number generator".

 The [Win32 API](https://msdn.microsoft.com/en-us/library/aa379942.aspx) is actually called `CryptGenRandom`, and says:

 > The CryptGenRandom function fills a buffer with cryptographically random bytes.

2. These operations are widely available. According to Wikipedia, `/dev/random` and `/dev/urandom` are available on Linux, NetBSD, OpenBSD, FreeBSD, Solaris, HP-UX, Cygwin, and AIX. A quick search shows that it's available on DragonflyBSD too. I believe that covers all of the platforms we support currently. 

 As for JavaScript, all recent browsers now support `crypto.getRandomValues()`, which says in its spec

 > The getRandomValues method generates cryptographically random values. 

 So I don't think we'd need to raise the "does not exist" error. 

3. Other languages expose these sources of randomness with the word "secure" or "crypto" in them. @lexi-lambda already mentioned Ruby. Java puts it in `SecureRandom` as well. The WebCrypto JS standard puts it on the `crypto` object. In [node.js](https://nodejs.org/api/crypto.html#crypto_crypto_randombytes_size_callback) it's called `crypto.random()`. Haskell has the `Crypto.Random` library (and a bunch of others). As [this StackOverflow answer](http://stackoverflow.com/a/20890675) shows, in Haskell `System.Random` is the _insecure_ random number generator. 

 Python seems to be the outlier, where it's called `SystemRandom` and `os.urandom()`. 

4. The name `secure-random` (or something similar, such as `crypto-random`, or `random` from a `racket/crypto` library) is important for communicating to users. The Hacker News vulnerability that @eu90h linked to (and which I strongly encourage everyone to read) came down to using Racket's `random` function with an inadequately-random seed in a security-sensitive situation. Naming the function in a way that encourages developers to use it is an important part of the user interface, for which documentation is an imperfect substitute.

5. Every OS that runs Racket provides a "system" source of randomness that is _not secure_, and it's important to distinguish the use of `/dev/random` and similar from those. On Linux/Windows/etc, that's `rand()`, on JavaScript it would the `Math.random()` function. We don't want to cause people to think that the function proposed here is a binding to those system-level operations.

6. Writing our own CSPRNG would be a very bad idea. The Racket community doesn't include any cryptographers that I know of, and even if it did, anything we write wouldn't be as tested, audited, attacked, or validated as system-provided CSPRNGs.

7. In cases where the OS doesn't provide a CSPRNG (none that we support currently, I think) we already ship OpenSSL on many platforms and can use that to provide a CSPRNG.

**Comment by rfindler** [comment]
Thank you Sam. Three thoughts come to mind:

I find this to be a strong argument for crypto-random more than for
secure-random.

Jay has published four crypo papers according to DBLP. What is your bar?

**Comment by samth** [comment]
I think `crypto-random` is fine. @eu90h, what do you think?

And @jeapostrophe, I 100% apologize for forgetting your past as a cryptographer!

**Comment by electronicpatterns** [comment]
Just to interject my perspective as an user-space developer using Racket in
personal projects.

To me this discussion boils down to who has done the work of verifying the
function is secure or whether the Racket stakeholders have delegated that
to some other third-party. I define third-party as an entity non-affiliated
with Racket and Racket does not have any control over its activity.

When I read "secure-random", I interpret it as meaning Racket has done the
work of verifying the source meets acceptable standards of being secure,
including audit of the relevant code. When I follow the discussion, I am
getting the message that Racket is actually deferring to third-parties to
make the security claim.

If I use secure-random, believing that its guarantees have verified by
Racket and it's actually using the underlying operating system service
which may or may not have understated its claims, should Racket be blamed
for misleading me into believing that using this function is secure?

Since we live in a time where security claims are frequently found to be
exaggerated or mistaken, it may be more risky to claim more than intended.
It seems more appropriate to label the function to be clear to what it
really is, if that is what is is, just rebinding of /dev/urandom,

So I would say it's more honest to say "os-urandom" so developers know
exactly what it is and can decide for themselves whether urandom is
appropriate for their needs. And moreover, there is /dev/random and
/dev/urandom, one is blocking till enough entropy is collected and the
other does not and you've got to deal with the possibility that
/dev/urandom may not have had enough time to generate entropy.

Does "secure-random/system-random" already take into account the difference
between /dev/random and /dev/urandom?

**Comment by jeapostrophe** [comment]
I feel better about crypto-random than secure-random.

I have confidence and trust in the rest of you to decide on a name and
place to put it that reflects our tradition and naming conventions. I'll
step out of the pull request debate to help make progress.

Jay

On Wed, Sep 16, 2015 at 11:35 AM, Sam Tobin-Hochstadt <
notifications@github.com> wrote:

> I think crypto-random is fine. @eu90h <https://github.com/eu90h>, what do
> you think?
>
> And @jeapostrophe <https://github.com/jeapostrophe>, I 100% apologize for
> forgetting your past as a cryptographer!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plt/racket/issues/1062#issuecomment-140779713>.
>



-- 
Jay McCarthy
http://jeapostrophe.github.io

           "Wherefore, be not weary in well-doing,
      for ye are laying the foundation of a great work.
And out of small things proceedeth that which is great."
                          - D&C 64:33

**Comment by eu90h** [comment]
This thread reminds me of that old joke, "there are only two problems in CS, cache invalidation and naming things."

25 comments, this thread have been quite lively! I hope I haven't come across in any posts as rude or stubborn, if I have I preemptively apologize.

@samth I'm fine with the name `crypto-random`.
Given @jeapostrophe's background with both cryptography & Racket itself, his opinion should be weighted more heavily. If he's comfortable with `crypto-random`, then I'll choose that one.

Regarding the location, I too felt the `file` directory was a poor choice, but I'm still unfamiliar the with general file structure and available packages/collections so just went with `file` because it had sha-1 and md5 implementations there.

**Comment by rfindler** [comment]
Lets go with `crypto-random`.

I still feel like racket/system is a good place for the actual
implementation (and maybe if you flip through the code, you'll agree too?)

Also, I think that we should, at the same time, update the documentation
for the other random functions to refer to this one so people are less
likely to have exploits like the one that affected HN.

**Comment by eu90h** [comment]
@rfindler racket/system was exactly what I had in mind when I started, I must've somehow missed it's folder.

**Comment by eu90h** [comment]
Closing since this was merged. Thanks everyone.

**Comment by samth** [comment]
Related to this discussion, [this article](https://lwn.net/Articles/657269/) about similar issues in Python is interesting reading.
