### ISSUE TITLE
raco pkg errors

### ISSUE THREAD

**Issue by lehitoskin** [racket/racket#1084]
I'm using Gentoo and I just installed 6.2.1 from version 6.1.1 and when downloading packages (any of them) with raco, I'm getting these errors:

```
raco setup: --- creating launchers ---
raco setup: --- installing man pages ---
raco setup: --- building documentation ---
get-doc-info error: /usr/share/doc/racket/guide/in.sxref::0: read (compiled): wrong version for compiled code
  compiled version: 6.1.1
  expected version: 6.2.1
raco setup: docs failure: delete-file: cannot delete file
  path: /usr/share/doc/racket/guide/out0.sxref
  system error: Permission denied; errno=13
raco setup: --- installing collections ---
raco setup: --- post-installing collections ---
raco pkg install: packages installed, although setup reported errors
```

I apologize if this is technically the wrong place to make the issue, there's just so many repositories.

**Comment by mflatt** [comment]
It looks like something has gone wrong installing v6.2.1 over v6.1.1, with "/usr/share/doc/racket/guide/in.sxref" (and maybe other files) left over from v6.1.1.

Can you say more about how each version was installed and how v6.1.1 was installed?

Thanks!

**Comment by lehitoskin** [comment]
v6.2.1 was installed through Portage. Here's the [ebuild that was used](http://gpo.zugaina.org/AJAX/Ebuild/10634650/View).

v6.1.1 was installed outside of Portage by compiling from source because an up to date ebuild didn't exist at the time (which is a real problem when you're using "bleeding-edge" Gentoo).

For both versions I enabled X, doc, futures, jit, places, and threads.

**Comment by jsmaniac** [comment]
More generally, when installing a new version of Racket, if I have locally-installed packages (e.g. with `cd my-package/; raco pkg instll`), then the compiled code in their `compiled/` directories is not updated.

Instead of displaying

```
compiled/my-file_rkt.zo::1: read (compiled): wrong version for compiled code
  compiled version: 6.90.0.29
  expected version: 6.11
```

it would be nice if Racket silently re-compiled the files, and overwrote the `.zo`. The alternative is to delete all the `compiled` directories, which is error-prone (I'm always afraid `find /path/to/package -type d -name compiled -print0 | xargs -0 rm` is going to accidentally delete something that it shouldn't.

**Comment by lexi-lambda** [comment]
Won’t just running `raco setup` do what you describe, @jsmaniac?

**Comment by jsmaniac** [comment]
@lexi-lambda I think it does, but I have regularly seen it miss some files in the past (often some .sxref in the documentation, but I'm not sure if it is limited to that).

I would be nice if we documented somewhere the list of commands that one should run in order to upgrade from Racket 6.x to 6.y (I suppose it can be as simple as download the Racket installer, `chmod +x`, `./...`, `raco setup`). I'll try to submit a PR with this soon.

**Comment by mflatt** [comment]
@jsmaniac Are you by chance using the `require-typed-check` package?

@bennn I get wrong-version errors even from `raco setup` in that package's tests, but it's because `require/typed/check` tries loading a library in a fresh namespace, which doesn't play well with `raco setup`. Would it work to change `typed-lib?` to use `module-declared?` with a #t second argument?

**Comment by jsmaniac** [comment]
@mflatt `raco pkg show -l -a | grep require-typed-check` shows nothing, so it seems that I'm not using that package.

**Comment by bennn** [comment]
@mflatt using `module-declared?` works for me; I pushed an update
https://github.com/bennn/require-typed-check/commit/06eed3448fc13e67a92cce36ebb6f32145dabf0e

**Comment by mflatt** [comment]
I think we're probably beyond sorting out the original problem here. There is always a question of how Racket could do better for recompiling when you upgrade, but that's covered by other issues.
