### ISSUE TITLE
Result type of resolve-path does not match documentation

### ISSUE THREAD

**Issue by sabauma** [racket/racket#1132]
Per the [documentation](http://docs.racket-lang.org/reference/Manipulating_Paths.html#%28def._%28%28quote._~23~25kernel%29._resolve-path%29%29), `resolve-path` should return a `path` object for any `path-string?` input.  Currently, it returns a `string` on `string` inputs and a `path` on `path` inputs. Either the docs or the implementation is wrong.

Example:

```racket
> (resolve-path "/usr/share/zoneinfo")
"/usr/share/zoneinfo"
> (resolve-path (string->path "/usr/share/zoneinfo"))
#<path:/usr/share/zoneinfo>
> (path? (resolve-path "/usr/share/zoneinfo"))
#f
```

**Comment by harrisi** [comment]
I'm unsure of how exactly to fix this right now, but I do believe I found the root cause.

In [file.c](https://github.com/racket/racket/blob/master/racket/src/racket/src/file.c#L4540) at the definition of `do_resolve_path`, the behavior of the internal variable `expanded` isn't working as intended (it seems). Here's my understanding of what's happening:

- [`expanded`](https://github.com/racket/racket/blob/master/racket/src/racket/src/file.c#L4547) is declared as an int (and is uninitialized)
- a reference to [`expanded`](https://github.com/racket/racket/blob/master/racket/src/racket/src/file.c#L4559) is passed to [`do_expand_file`](https://github.com/racket/racket/blob/a0f7b618f7f201b9f2299afc7f41c91a7995a9fd/racket/src/racket/src/file.c#L1852)
- the very first statement in `do_expand_file` [sets the value the reference to `expanded` is pointing to to 0](https://github.com/racket/racket/blob/a0f7b618f7f201b9f2299afc7f41c91a7995a9fd/racket/src/racket/src/file.c#L1857)
- [a reference to `expanded` is passed to `remove_redundant_slashes`](https://github.com/racket/racket/blob/a0f7b618f7f201b9f2299afc7f41c91a7995a9fd/racket/src/racket/src/file.c#L1955), which will set the value [`expanded` is pointing to](https://github.com/racket/racket/blob/a0f7b618f7f201b9f2299afc7f41c91a7995a9fd/racket/src/racket/src/file.c#L1844) to 1 [_iff_ there are extra slashes](https://github.com/racket/racket/blob/a0f7b618f7f201b9f2299afc7f41c91a7995a9fd/racket/src/racket/src/file.c#L1827).
- back to `do_resolve_path`, there is again a [check on `expanded`](https://github.com/racket/racket/blob/master/racket/src/racket/src/file.c#L4620), and at this point there seems to be two possible situations:
    1. The path has no extra slashes, which means `expanded` is 0.
    2. The path has extra slashes, which means `expanded` is 1.

In the first situation, the `if` statement will be true (`!0` is truthy), which means the value passed to `resolve-path` will be returned unchanged (which, then, means that currently `(resolve-path "/foo/bar/baz")` is the same as `(identity "/foo/bar/baz")`). In the second situation, the `else` branch will be taken, which will then return the correctly-"pathified" value.

So the quick fix (with minimal testing) is to remove that branching and just use the [`else` branch](https://github.com/racket/racket/blob/master/racket/src/racket/src/file.c#L4623) for a return statement. But clearly this is not the right way to fix this problem. It seems as though this whole file situation got a bit complicated and now the behavior doesn't really make sense. I'm not sure how to fix it or what to try to simplify or abstract or what.

More interestingly, when calling `resolve-path`, if the string (or path) given to it _does_ have extra slashes, the behavior is correct (I think). So in your example, you could do:

```
> (resolve-path "//usr/share/zoneinfo")
#<path:/usr/share/zoneinfo>
```

This is a very silly and hacky "fix," but if you need this to work and don't want to use `string->path` for some reason, just add a bunch of slashes!

I intend to try to "decomplect" this further, but I don't expect to gain much ground. Maybe someone smarter than me can use this information to fix this error.

Note: I noticed that in this case the call to `do_expand_file` (on Unix-like systems, anyway) from `do_resolve_path` actually only calls `remove_redundant_slashes` because of the parameters passed to it. I don't know what all should be changed, and my C is very very bad.

**Comment by mflatt** [comment]
@harrisi Thanks for the analysis! I think the solution in this case is to check whether the argument was a string (as opposed to a path), and not return the argument in that case. I'm running a build with that change, and I'll push it if things work out.

(The only problem I can imagine is that some existing code might accidentally rely on the old behavior of returning a string.)
