### ISSUE TITLE
->i applies domain contracts twice

### ISSUE THREAD

**Issue by bennn** [racket/racket#1135]
The `->i` contract applies domain contracts twice to its arguments. The applications should happen once, and the now-protected arguments should be shared by the client function & codomain contract. (See footnote 3 in http://www.eecs.northwestern.edu/~robby/pubs/papers/popl2011-dfff.pdf)

```
#lang racket/base
(require racket/contract)

(define (incr/c v)
  (set-box! v (add1 (unbox v))))

(define/contract
  (foo x)
  (->i ([x incr/c]) [result (x) integer?])
  (unbox x))

(foo (box 0))
;; Returns 2, should return 1.
```

**Comment by rfindler** [comment]
I am not following how footnote 3 is related here.

But in any case, the contract is applied to the value twice because we need
both the version with the indy blame (for use in the depended-on contract
(result in this case)) and the version with the normal blame.

The contract system cannot currently share those applications because of
the way the inter arrangement of code works.

Why do you need it to?

**Comment by bennn** [comment]
I thought footnote 3 said: "when we get an argument for a dependent contract, we should apply the domain contract to it once and use that result twice".

In terms of the example, I'd want:
```
(let* ([x+ (incr/c x)]
       [result (unbox x+)]
       [check (integer? x+)])
  result)
```

We can close the issue if it's not possible to fix. I don't need it for anything in particular, and if I did need it (maybe, enforcing affine usage with contracts) I could use lax contracts instead.

**Comment by samth** [comment]
Footnote 3 in that paper is about "picky" -- the difference between picky and `->i` is precisely that the two uses are different.

**Comment by rfindler** [comment]
Footnote 3 says that we will apply the contract to the value 2 times, not 1+n times (where n can be zero actually). 

It may be possible to fix, but fundamentally the two values have different blame behavior so it isn't possible in the general case.

In the case where we know there is no negative blame we could probably avoid it, but it isn't a simple change and the performance implications for that are unclear.

**Comment by rfindler** [comment]
(also what sam said)

**Comment by rfindler** [comment]
So, just to add one more self-reply: if there were a footnote like footnote 3 that applied to picky, it would have a let that would apply to only ONE of the "mon"s since the two mons are different.

**Comment by chrdimo** [comment]
The reason the footnote is there is technical. We chose the substitution to be able to express all the variants of the semantics concisely in a similar manner. Otherwise we would need a let with one binder for picky and a let with two binders for indy (after some renaming in the range of the contract). Due to this choice we replace x in the range of the contract with an open term --- not a value --- and thus we violate CBV. But it does not matter in the context of the paper; the two variants of the rules are equivalent.

As for affine usage, the effect comes too early in the example above. It should take place when the value is used, not upon application of the contract. For boxes this means the effect should be pushed in the redirection function of the chaperone/impersonator.

**Comment by rfindler** [comment]
@chrdimo I'm not quite sure I'm following: are you saying that this program produces the wrong result?

**Comment by bennn** [comment]
Thanks @findler @samth @chrdimo for explaining why `->i` needs 2 lets. If I ever need effects in my contracts I'll stick with `->d`.

**Comment by chrdimo** [comment]
No.  I am saying that this program behaves as expected and that the paper does not say anything about arbitrary effects that happen during application of contracts on higher-order values (CPCF cannot express them for ho combinators and disallows flat contracts on ho values via types). The footnote of the paper is only there for a reader who would object to the rule on the grounds that the substitution does not involve a value (if we had gone with the let approach, as you said above, for indy we would apply the contract twice with different blame labels each time). 

Also, for the implementation, I can't think of a useful contract combinator where effects upon contract application would matter. The affine contracts that Ben brought up can be correctly expressed with ho combinators that delay the effect until the right moment.* So I think ->i is fine as is unless if we have a non-contrived example where effects during contract application matter.

* @bennn   ->d is wrong. If you need effects push them at contract checking time not contract application time. If you want to limit them at a certain dynamic scope use contracts that install parameters and use them as flags for the effects you care about.

**Comment by bennn** [comment]
@chrdimo what about this contract?

```
(define (checksum-valid? port)
  (string=? (read-line port)
            "Hello,"))

(define with-checked-port/i
  (->i ([port  checksum-valid?])
       [result (port) (port-closed? port)]))
```

**Comment by chrdimo** [comment]
I think this is a misuse of  flat contracts. The real solution would be to have contract combinators that describe this kind of protocols. Flat contracts describe first-order invariants of values. Thus the failure would be justifiable since the flat contract is used to describe a firs-order property that is variable.

A similar problem showed up in the past with box/c, vector/c etc.

**Comment by rfindler** [comment]
That's what I mean, yes. The flat properties being segregated from the ho
ones.

And it comes up in other places: or/c and checking on the server side.

So it does seem interesting. (Thanks, Ben!)

Still a big job. :)

Robby
