### ISSUE TITLE
expansion produces different identifier names than compilation

### ISSUE THREAD

**Issue by samth** [racket/racket#1138]
Consider the two files below (from samth/pycket#174). If you run `raco expand` on each, there's a weird discrepancy. The expansion of `main.rkt` will refer to two identifiers provided from the `#%contract-defs` submodule of `streams.rkt`, named something like `idY4` and `idY32`. However, these identifier names aren't mentioned in the expansion of `streams.rkt` (there are various other identifiers with that sort of name, but not the ones used in `main.rkt`). 

If you look at the output of `raco decompile`, though, the identifiers are there in both files. The identifiers that appear in the `raco expand main.rkt` and `raco decompile main.rkt` output are the same, but the output of `raco decompile streams.rkt` has definitions for the relevant identifiers whereas `raco expand streams.rkt` has different names (such as `idY16`) for them.

Note that this doesn't happen on the 6.3 pre-release builds.

## main.rkt

```racket
#lang racket/base

(require "streams.rkt")

;;--------------------------------------------------------------------------------------------------
(define ones (make-stream 1 (λ () ones)))
(stream-get 0 ones)
```

## streams.rkt

```racket
#lang typed/racket/base

(provide (struct-out stream)
         make-stream
         stream-unfold
         stream-get)

(struct: stream ([first : Natural] [rest : (-> stream)]))

(: make-stream (-> Natural (-> stream) stream))
(define (make-stream hd thunk)
  (stream hd thunk))

(: stream-unfold (-> stream (values Natural stream)))
(define (stream-unfold st)
  (values (stream-first st) ((stream-rest st))))

(: stream-get (-> stream Natural Natural))
(define (stream-get st i)
  (define-values (hd tl) (stream-unfold st))
  (cond [(= i 0) hd]
        [else    (stream-get tl (sub1 i))]))

```

Originally reported by @sabauma.

**Comment by mflatt** [comment]
The difference between v6.3 and the development branch has to do with changes in the contract system.

The difference between compilation and `expand` paths is due to some non-determinism that seems to be in TR. I tracked it back as far as `generate-contract-def/provide` being called in different orders for `stream`, `stream-first`, etc. It's possible that the order is not picked by TR, but my guess is that there's an unordered hash-table traversal somewhere in the TR compiler.

For me, it was enough to run `racket -l racket/base -l- raco expand` versus `raco expand` to see different outputs for "streams.rkt".
