### ISSUE TITLE
`random-sample` keyword argument name

### ISSUE THREAD

**Issue by elibarzilay** [racket/racket#1207]
(Vincent wanted me to post this here:)

I had no clue what `replacement?` means, until I looked at the code.  The term that I know this feature as is "with repetitions" -- my problem with "replacement" is not just whether it's more common or not (google seems to agree that "repetitions" are indeed more common), but it's that "replacement" doesn't really convey any meaning by itself (and so far I still don't know how that word conveys what I know as samples with repetitions).

This can be fixed now when it's fresh enough, and before it goes in a release and therefore gets set in stone.

**Comment by soegaard** [comment]
2016-01-14 8:44 GMT+01:00 Eli Barzilay <notifications@github.com>:

> (Vincent wanted me to post this here:)
>
> I had no clue what replacement? means, until I looked at the code. The
> term that I know this feature as is "with repetitions" -- my problem with
> "replacement" is not just whether it's more common or not (google seems to
> agree that "repetitions" are indeed more common), but it's that
> "replacement" doesn't really convey any meaning by itself (and so far I
> still don't know how that word conveys what I know as samples with
> repetitions).
>
The samples are drawn from a pool. After a sample is drawn - is it to be
placed back into the pool or not?
If it is, repetitions will occur.

I think the replacement/repetition word choice is one of the cases where
two words are in common use.
In statistics (I think) the word chosen is usually "replacement" (check
MathWorld [1] for one).

I kind of like "replacement" better than "repetition" - most likely because
I met that term first :-)

No matter which one is chosen - it is worth mentioning both phrases in the
docs.

/Jens Axel


[1]     http://mathworld.wolfram.com/BallPicking.html

**Comment by bennn** [comment]
Here a few more votes for "replacement"
- [Wikipedia](https://en.wikipedia.org/wiki/Simple_random_sample)
- [matlab](http://www.mathworks.com/help/stats/randsample.html?requestedDomain=www.mathworks.com)
- [R](https://stat.ethz.ch/R-manual/R-devel/library/base/html/sample.html)
- [Python](https://docs.python.org/3/library/random.html)

**Comment by elbarzil** [comment]
The wikipedia link was useful in that it has a hebrew version, where
"replacement" was translated into a word that means "returns",
supporting Jens Axel's explanation of "place back in the pool".  I
suspect that the thing that bugs me more here is the "substitution"
meaning rather than the fact that in hebrew that "returns" word is
awfully close to the word used for "repeats" (one character difference,
making google useless since it counts both words).

In any case, names in apis in other languages are much more important to
follow, so that does it.

**Comment by stamourv** [comment]
Ok, in that case, I'll close the issue.
Thanks all for the discussion!
