### ISSUE TITLE
Error with sync/timeout

### ISSUE THREAD

**Issue by gus-massa** [racket/racket#1232]
In https://github.com/racket/racket/pull/1076 I get an error with `sync/timeout` in [sync.rktl#L229](https://github.com/racket/racket/blob/dfef5b43fc8e87c5038f13429d45e10af77e6092/pkgs/racket-test-core/tests/racket/sync.rktl#L229). The problem only appears in AppVeyor and never in Travis, so it's probably related to Windows. 

I'm using Win7, with Visual Studio 32bits. I could reproduce the error with this short version in the branch of the PR, in almoss-HEAD and in 6.3. So I guess it's not a problem in the PR. The stange part is that the PR increases the probability of the error.

    #lang racket/base
    
    ;;enable to increase the error rate
    #;(void (thread (lambda () 
                   (let loop ()
                     (let ([v (make-vector 1000)])
                       (vector-set! v (random 1000) #t)
                       (loop))))))

    (define-syntax-rule (test r f args ...)
      (let-values ([(res-list cpu real gc) (time-apply f (list args ...))])
        (unless (equal? (list r) res-list)
          (displayln (list res-list (list r) '(f args ...) cpu real gc)))))
    
    (let ([make-delay
           (lambda (amt)
	     (guard-evt
              (lambda ()
                (wrap-evt
                 (alarm-evt (+ (current-inexact-milliseconds) (* 1000 amt)))
                 (lambda (v) amt)))))])
   
    (for ([i 100])
      (test #f sync/timeout 0.1 (make-delay 0.15) (make-delay 0.2))
      (test 0.15 sync/timeout 18 (make-delay 0.15) (make-delay 0.2))
      (test 0.15 sync/timeout 18 (make-delay 0.2) (make-delay 0.15))
      (test 0.15 sync/timeout 0.18 (make-delay 0.15) (make-delay 0.2))
      (test 0.15 sync/timeout 18 (choice-evt (make-delay 0.2) (make-delay 0.15))))
    )

Typial output without the tread to create garbage:

    ((0.15) (#f) (sync/timeout 0.1 (make-delay 0.15) (make-delay 0.2)) 0 158 0)
    ((0.2) (0.15) (sync/timeout 18 (choice-evt (make-delay 0.2) (make-delay 0.15))) 0 445 0)
    [and a few more ...]

Typical ouput with the tread to create garbage:

    ((0.2) (0.15) (sync/timeout 18 (make-delay 0.15) (make-delay 0.2)) 219 223 141)
    ((0.15) (#f) (sync/timeout 0.1 (make-delay 0.15) (make-delay 0.2)) 140 156 78)
    [and many more ...]

**Comment by mflatt** [comment]
This doesn't look like a bug, but it probably needs clarification in the docs.

A delay provided to `sync/timeout` is merely a lower bound on the duration of the sync attempt. Similarly, an alarm event becomes ready at a given time, but there's no guarantee that `sync` sees the time between two alarm events becoming ready. More generally, there's no guarantee that an event will be selected before another event that becomes ready later; the intended guarantee is something more along the lines of "eventually, some ready event will be selected".

I expect that the difference with this example is more visible on Windows because the system clock is so coarse (around 15ms), but a sufficiently loaded Linux installation should produce the same result.

**Comment by mflatt** [comment]
Just to clarify: I think the failing tests in "sync.rktl" are bad.

The only idea I have for making them work in practice is to make the long delays (i.e., the ones that are not meant to be selected) orders of magnitude larger than the delays that are meant to be selected. Then, then tests should pass in all but the most unfriendly environments.

**Comment by gus-massa** [comment]
Agree. I think that something like
 
    (test 0.15 sync/timeout 18 (make-delay 0.15) (make-delay 2))

will work.
