### ISSUE TITLE
eval bug

### ISSUE THREAD

**Issue by sk1e** [racket/racket#1282]
The following code sample produces a error while running on my racket 6.4 and 6.3 installations. But not on 6.2.1.
```
#lang racket/base

(require racket/class
         racket/draw)

(define-namespace-anchor anchor)
(define ns (namespace-anchor->namespace anchor))
(eval '(new object%) ns)
(is-a?/c bitmap-dc%)
```

Error message:

`lifted.0.0: undefined;`

**Comment by harrisi** [comment]
I really don't understand what's going on with this, and I'm not good enough with git to try to narrow down changes that have happened in the last couple releases, but maybe something I say here can help someone smarter than me figure it out.

The line highlighted in DrRacket is the `eval` line. However, if either the `eval` line _or_ the `is-a?/c` line are commented out, there is no error. The order doesn't matter, although if `eval` is after `is-a?/c`, you get the output from `is-a?/c` before the program crashes. The byte code doesn't seem to help too much (not for me, anyway), but that might be because of eval. Without eval expanding, I don't know where to look.

Note: I tried a number of substituted values for both `is-a?/c` and `bitmap-dc%` (using similar values) and they all gave the same error. So I don't think that the problem is something specific to either `is-a?/c`or `bitmap-dc%`. Unfortunately this made it harder for me to snoop around.

I would like to try to narrow down two versions where this does and doesn't happen, although that sounds like a lot of compiling. Maybe there's a quick way to test several commits between each other for this error which would be helpful.

**Comment by mflatt** [comment]
@sk1e Thanks for the report!
@harrisi Thanks for investigating!
The bug was related to some compromises for the (hopeless) top level not lining up as well as they could.
