### ISSUE TITLE
Default current-print ignores current-output-port

### ISSUE THREAD

**Issue by jsmaniac** [racket/racket#1294]
This program prints `'aaa` on stdout, wheras according to the docs, it should not print anything:
```
#lang racket/base
(let ([os (open-output-string)])
  (parameterize ([current-output-port os])
    (displayln "not shown")
    ((current-print) 'aaa)))
```

[The documentation](https://docs.racket-lang.org/reference/eval.html#%28def._%28%28quote._~23~25kernel%29._current-print%29%29) says:

> The default print handler prints the value to the current output port (as determined by the current-output-port parameter) and then outputs a newline, except that it prints nothing when the value is #<void>.

But in the example above, `current-output-port` is ignored.

**Comment by mflatt** [comment]
I think the example works as expected when run via `racket`, which uses the default print handler. DrRacket, in contrast, uses a custom print handler. In other words, it's one of those few places where DrRacket intentionally behaves differently for `racket`.

**Comment by rfindler** [comment]
DrRacket does this because it uses current-print to print values to the "value port" in the DrRacket interactions window (REPL). That is, DrRacket is making a finer distinction that we can in the command-line racket: it has three interesting ports: the port where values are printed (blue), the port where other output goes (purple), and the port where errors go (red).

It seems reasonable to print values to the value port only when the current-output-port is set to the output port of the interactions window. I'll push that change.
