### ISSUE TITLE
Potentially incorrect indentation

### ISSUE THREAD

**Issue by Earnestly** [racket/racket#1325]
In https://github.com/racket/racket/blob/master/racket/src/racket/src/read.c#L3136 the `if` statement seems to suggest that `scheme_read_err` is part of the `else` block:

```c
  else
    scheme_tell_all(port, &line2, &col2, &pos2);
    scheme_read_err(port, stxsrc, line, col, pos, pos2-pos, -1, indentation, "read: expected fixnum, got %V", n);
  return NULL;
```

The indention is misleading if this isn't the case.

**Comment by gus-massa** [comment]
Looking at the previous function [read.c#L3117](https://github.com/racket/racket/blob/master/racket/src/racket/src/read.c#L3117), I think that the curly brackets are missing. 

The code is equivalent, because the other branch has a `return`, but it's confusing. 

Perhaps you can send this as a PR. (If Matthew doen't fix this inmeditely.)

**Comment by gus-massa** [comment]
Fixed in https://github.com/racket/racket/commit/9978696991d04f8bc8aed34aa02fa39cd7b9b3f3

Thanks for the report.
