### ISSUE TITLE
"require: namespace mismatch" in DrRacket but not on the command-line

### ISSUE THREAD

**Issue by jsmaniac** [racket/racket#1352]
The file below works fine with `racket file.rkt` and `raco make file.rkt`, but gives the following error message with DrRacket. I'm using version `6.5.0.5`. I posted a question about this [on StackOverflow](http://stackoverflow.com/questions/37867859/module-meta-language-in-racket), and @samth said on IRC it's probably a bug in Racket.

```
/usr/share/racket/pkgs/typed-racket-lib/typed-racket/typecheck/tc-toplevel.rkt:479:30: require: namespace mismatch;
 reference to a module that is not available
  reference phase: 1
  referenced module: "/nix/store/62qr8is77hh9qd5nxyrrc9dym32www92-racket-6.5.0.5/share/racket/pkgs/typed-racket-lib/typed-racket/env/env-req.rkt"
  referenced phase level: 0 in: add-mod!
```

The goal is to create a module meta-language `mylang` which can be parameterized with another language. Below, `mylang` simply uses the first expression as the delegated-to language, and keeps the rest of the module's body as-is. More complex implementations could extract the body in the same way as scribble/lp2, for example.

``` racket
#lang racket

(module mylang racket
  (provide (rename-out [-#%module-begin #%module-begin]))
  (require (for-syntax syntax/strip-context))
  (define-syntax (-#%module-begin stx)
    (syntax-case stx ()
      [(_ lng . rest)
       (let ([lng-sym (syntax-e #'lng)])
         (namespace-require `(for-meta -1 ,lng-sym))
         (with-syntax ([mb (namespace-symbol->identifier '#%module-begin)])
           #`(mb . #,(replace-context #'mb #'rest))))])))

(module foo (submod ".." mylang) typed/racket/base
  (ann (+ 2) Number))

(require 'foo)
```

I tested this in the most conservative setting possible for DrRacket regarding optimizations:
- No debugging or profiling
- Do **not** populate "compiled" directories
- Preserve stack trace
- Do **not** impose constant definitions
- The error is given even if `(require 'foo)` is omitted

The background expansion works fine (little green dot in the bottom-right corner), the error message only appears when pressing F5.

Inside the DrRacket REPL of another empty (just the `#lang racket`) racket file located in the same folder, the following works, and I can access definitions from `file.rkt` if I add any:

``` racket
(require racket/enter)
(enter! "file.rkt")
```

Finally, if I copy-paste the following expression inside DrRacket's REPL for an empty file (just the `#lang racket`) I still get the error, but if I copy-paste it in the command-line REPL (just `racket` without any arguments) it works fine. It also works fine if fed into DrRacket's REPL wrapped with `(eval '(begin …))`.

``` racket
(begin
    (module mylang racket
      (provide (rename-out [-#%module-begin #%module-begin]))
      (require (for-syntax syntax/strip-context))
      (define-syntax (-#%module-begin stx)
        (syntax-case stx ()
          [(_ lng . rest)
           (let ([lng-sym (syntax-e #'lng)])
             (namespace-require `(for-meta -1 ,lng-sym))
             (with-syntax ([mb (namespace-symbol->identifier '#%module-begin)])
               #`(mb . #,(replace-context #'mb #'rest))))])))

    (module foo 'mylang typed/racket/base
      (ann (+ 2) Number))

    (require 'foo))
```

**Comment by jsmaniac** [comment]
I forgot to note: the error occurs only if `typed/racket/base` or `typed/racket` is used in `foo`, if instead `racket/base` is passed, everything works fine.

**Comment by mflatt** [comment]
In recent Racket versions (roughly, since the "new" expander; current version is 8.1.0.2), the example fails earlier and in a consistent way between Racket and DrRacket. The difference compared to the old expander is that `(current-namespace)` is kept more separate from instantations and visits specific to an expansion of a module. Essentially, the problem is that the expansion of `#%module-begin` doesn't declare a dependency on the language represented by `lng-sym`.

Adjusting the example by adding `(#%require #,lng-sym)` in `(mb . (#%require #,lng-sym) #,(replace-context ...))` to declare the dependency gets back to the old behavior — and the old difference between `racket` and DrRacket. However, that difference is not exactly a bug; it's a result of how `typed/racket/base` adds code before the `#%require` that starts the body, so the dependency declaration doesn't work as intended. More generally, the idea of trying to inject the dependency with `#%require` doesn't work for all languages, because not all languages support `#%require` in a module body.

A new commit (to appear soon) will finally provide a way to achieve what you wanted: `syntax-local-lift-require` can be used during `#%module-begin` expansion. That solves the problem because the lifted import gets added to the beginning of the expanded module, instead of appearing in the body that the next `#%module-begin` sees.

Here's the revised example that will work with the improved `syntax-local-lift-require`:

```
#lang racket

(module mylang racket
  (provide (rename-out [-#%module-begin #%module-begin]))
  (require (for-syntax syntax/strip-context))
  (define-syntax (-#%module-begin stx)
    (syntax-case stx ()
      [(_ lng . rest)
       (let ([lng-sym (syntax-e #'lng)])
         (with-syntax ([mb (syntax-local-lift-require lng-sym (datum->syntax #f '#%module-begin))])
           #`(mb . #,(replace-context #'mb #'rest))))])))

(module foo (submod ".." mylang) typed/racket/base
  (ann (+ 2) Number))

(require 'foo)
```
