### ISSUE TITLE
Docs in search include relative paths

### ISSUE THREAD

**Issue by endobson** [racket/racket#1426]
When looking for a function I found that some modules were shown like `"../../crypto.rkt"`. That doesn't seem like the best behavior since it is non obvious what it is relative to nor does that seem relevant to me that is was specified as relative at some point during doc creation.

http://docs.racket-lang.org/search/index.html?q=base64
![ScreenShot](https://cloud.githubusercontent.com/assets/170008/17828658/47badeb0-664d-11e6-8ca8-c324bb36356d.png)

**Comment by mflatt** [comment]
This appears to be a bug in the docs for the "grommet" package, which has

```
  @declare-exporting["../../crypto.rkt"]
```

I think it must be a leftover, because the path doesn't make sense relative to the ".scrbl" document in its repo, much less in the rendered documentation.

(The "Hash" and "HMAC"  sections have good `defmodule` declarations, so the `declare-exporting` form applies only to the "Base64" section.)

**Comment by gus-massa** [comment]
I have just send a PR to the package to fix this. https://github.com/RayRacine/grommet/pull/7

**Comment by gus-massa** [comment]
The PR was merged and this is already fixed in Racket 6.9.
