### ISSUE TITLE
optimizer clock internal error

### ISSUE THREAD

**Issue by andmkent** [racket/racket#1461]
This code gives me the following error: "internal error: optimizer clock tracking has gone wrong"

```racket
#lang racket/base

(module a racket/base
  (provide (all-defined-out))
  (require (for-syntax
            syntax/parse
            racket/base))
  (define-values (prop1 _1 _2) (make-struct-type-property 'prop1))
  (define-values (prop2 _3 _4) (make-struct-type-property 'prop2))
  
  (define-syntax (def-struct stx)
    (syntax-parse stx
      [(_ var [#:prop . prop-body])
       #'(let ()
           (struct var () #:transparent
             #:property prop1 the-val ;; undefined value?
             #:property prop2 prop-body)
           (define the-val 42)
           42)])))

(require (submod "." a))

(def-struct Univ [#:prop 3])
```

Racket version 6.6, OS X 10.11.6

**Comment by gus-massa** [comment]
After an extensive minimization, I got this:

    #lang racket/base
    (letrec-values ([() (list (3) the-val)]
                    [(the-val) 42])
      777)  ;==> #f 

(I replaced the last `42` by `777`.)

I think that the optimizer realizes that `(3)` will generate an error and replaces the rest of the expression by `#f` because it will never be executed. But later the optimizer thinks that the first part has no side effects and removes it.

A similar change may break some of the internal clocks in your example, so the effect is very different but I think that the root casue is the same.

I'm guessing a little, and I still don't have a fix, [optimize_lets](https://github.com/racket/racket/blob/d4158c2b04b71d193ab32e43396b62b865ec2df6/racket/src/racket/src/optimize.c#L6878) is very complex.

**Comment by rfindler** [comment]
I think that the example blow might, maybe be in reach of a random
expression generator. But I don't know how to formulate a predicate. Is
there a way to evaluate an expression with and without the optimizer that
could be used to try to help find such bugs?

Robby

**Comment by gus-massa** [comment]
Currently the optimizer has two objectives:

* collect some information for the resolve and sfs steps of the compiler

* apply some optimizations

(And there are a few optmizations scatered in other steps of the compilation, but (probably) all the optimizations outside optimize.c are small and foolproof.)

I think that it's posible to make two copies of optimize.c, and keep in one copy all the optimizations and in the other the only keep the necesary parts to save the info for the following steps.

Perhaps this can be enable extending the meaning of 

    set PLT_RECOMPILE_COMPILE=0

--

To test for error between **one** and **two** optimizations you can try an improved version of 

    #lang racket
    
    (define (test-reoptimization stx)
      (equal? (eval (compile stx))
              (eval (compiled-expression-recompile (compile stx)))))
    
    (test-reoptimization #'(+ 1 2))
    (test-reoptimization #'(let ([x 5]) (+ x x)))
    (test-reoptimization #'(let ([x (* (random) 0)]) x x))

But the transfomations are complex (in particular the resolve/unresove part). So I think it's  difficult to make `(compiled-expression-recompile (compile/0-optimizations stx))` equivalent to `(compile/1-optimization-as-usual stx)`.

**Comment by rfindler** [comment]
Are there arguments I could pass to the build process that would disable
the relevant parts of the code? And then I could just compile two versions
and test them against each other?

**Comment by mflatt** [comment]
@gus-massa Thanks for mostly tracking down the problem! I think the issue is that the `found_escapes` test on line 7139 is not right for letrec mode. Changing the test to `(!is_rec && found_escapes)` avoids the bug and passes existing tests (i.e., no tested optimization is lost). I'll check more to be sure that's the right repair.
