### ISSUE TITLE
Segfault with letrec

### ISSUE THREAD

**Issue by bctnry** [racket/racket#1462]
```
(letrec ([a 0]
         [b (let ([t 0])
              (λ () (set! a 1)))])
  (b))
```
and I get this:

```
 Seg fault (internal error) at 1
 Seg fault (internal error) at 1
 Seg fault (internal error) at 1
```

**Comment by mflatt** [comment]
Thanks for the report!

This crash is a regression relative to v6.4 caused by a refactoring of the compiler between v6.4 and v6.5. The refactoring lost information about `letrec`s that are converted internally to `let*` when a mutable variable is involved. The crash happens in DrRacket and not in plain `racket`, because DrRacket's extra debugging constraints prevent the optimizer from further actions that happen to avoid the crash. I'm still deciding on the best way to fix the problem.
