### ISSUE TITLE
regex: bug on matching (?!regex)

### ISSUE THREAD

**Issue by lotabout** [racket/racket#1468]
Consider the following:

```
> (regexp-match "a*(?!b)" "aaaxy")
#f
```

While in python:
```
In [29]: re.match(r'a*(?!b)', "aaaxy").group()
Out[29]: 'aaa'
```

Python's version is the expected one. It seems that it happens when repeat (`*`, `+`) is used before `(?!...)`.

**Comment by mflatt** [comment]
Thanks for the report!

The problem is a 10-year-old bug in the pattern matcher's optimizer, which notices that "a*" might be expensive to match (due to backtracking), so it attempts to find a substring that must appear in matching input as a quick pre-test on the input. Unfortunately, the optimizer takes "b" as the substring that must appear — incorrectly treating a must-not-match part of the pattern as a must-match part of the pattern.

I'll push a repair soon.
