### ISSUE TITLE
define-rename-transformer-parameter uses the old binding within make-rename-transformer

### ISSUE THREAD

**Issue by jsmaniac** [racket/racket#1479]
In the example below, `(syntax-parameterize ([num (make-rename-transformer #'two)]) …)` changes the syntax-local-value for `num`, but `num` still behaves like the old binding (`#'one`) when used as a macro.

When using `define-syntax-parameter` instead of `define-rename-transformer-parameter`, the use of `num` as a macro works as expected.

This sounds like a bug to me and @samth thought so too at a first glance (on IRC).

If this behaviour is correct for some reason, it should at least be documented (I did not see anything relevant in the docs, but might have missed something).

```
#lang racket
 
(require racket/stxparam)
(define-syntax (test stx)
  (syntax-case stx ()
    [(_ t)
     #`#,(syntax-local-value #'t)]))
 
(begin-for-syntax
  (define (p1 stx) #'1)
  (define (p2 stx) #'2))
(define-syntax one p1)
(define-syntax two p2)
 
(define-rename-transformer-parameter num
  (make-rename-transformer #'one))
 
;; prints '(#<procedure:p1> 1)
(list (test num)
      num)
 
(syntax-parameterize ([num (make-rename-transformer #'two)])
  ;; Should print: '(#<procedure:p2> 2)
  ;; But prints:   '(#<procedure:p2> 1)
  (list (test num)
        num))
```

**Comment by jeapostrophe** [comment]
@mflatt Can you help me with this?

I added the following test case

```
(begin
  (define-syntax (slv stx)
    (syntax-case stx ()
      [(_ t)
       #`'#,(object-name (syntax-local-value #'t))]))

  (define-syntax one (procedure-rename (λ (stx) #'1) 'one))
  (define-syntax two (procedure-rename (λ (stx) #'2) 'two))

  (define-syntax-parameter normal
    (make-rename-transformer #'one))
  (test #f eq? (slv normal) 'one)
  (test #t = normal 1)
  (syntax-parameterize ([normal (make-rename-transformer #'two)])
    (test #f eq? (slv normal) 'two)
    (test #t = normal 2))
  
  (define-rename-transformer-parameter rt
    (make-rename-transformer #'one))
  (test #t eq? (slv rt) 'one)
  (test #t = rt 1)
  (syntax-parameterize ([rt (make-rename-transformer #'two)])
    (test #t eq? (slv rt) 'two)
    (test #t = rt 2)))
```

to `~plt/pkgs/racket-test-core/tests/racket/stxparam.rktl`

but I can't make heads or tails of it. The `rt` binding definitely calling the dynamic `rename-transformer-target` function that uses `syntax-local-get-shadower` to make it so it binds to the inner-most `rt33` (or whatever) which is why `syntax-local-value` works, but I can't see why the expander doesn't see that when expanding `rt`.

I feel like if one works, the other should too, and I really can't tell the different between the two contexts looking at the `syntax-debug-info` of the two identifiers inside the implementations.

**Comment by mflatt** [comment]
@jeapostrophe I hope to have time to look at this tomorrow or this weekend.

**Comment by jeapostrophe** [comment]
Phew, I'm glad I wasn't incompetent :)
