### ISSUE TITLE
raco pkg new: what versions to include, and how to include them?

### ISSUE THREAD

**Issue by SuzanneSoy** [racket/racket#1500]
As a follow-up to #1466, I'm opening this issue.

`raco pkg new` creates a `.travis.yml` file which builds the project on these versions:

```
- RACKET_VERSION=6.0
- RACKET_VERSION=6.1
- RACKET_VERSION=6.1.1
- RACKET_VERSION=6.2
- RACKET_VERSION=6.3
- RACKET_VERSION=6.4
- RACKET_VERSION=6.5
- RACKET_VERSION=6.6
- RACKET_VERSION=6.7
- RACKET_VERSION=HEAD
```

Currently, the version numbers are hardcoded, and new versions have to be added by hand. @stamourv asked if we can make this part automatically generated.

I see several options:
1. Include all the `X.Y` version numbers from `6.0` until `(version)`, and hardcode the few versions which do not fall within this pattern, like `6.1.1`, which was a regular release (i.e. not a quick bugfix).
2. Same as above, but use some later version we agree upon, as `6.0` is starting to be somewhat old, and it gives a lot of work to Travis.
3. Same as above, but include only the last `N` versions, for a small value of `N`
4. Include a few hand-picked significant versions (e.g. one with the old macro expander and one with the new macro expander), plus raco's own version (as given by `(version)`), plus `HEAD`
5. Just raco's own version (as given by `(version)`), plus `HEAD`
6. Something else?

I think it's best if the code works 100% without network access (i.e. checking online for the latest version instead of using `raco`'s own `(version)` would be a bad idea, as it would introduce some latency, and would give different results depending on whether there is network access or not).

Option `4` seems like a good pick for me (we can hardcode some knowledge of which versions are significant enough to warrant extra testing, but the file does not need to be updated at each new release). @stamourv hinted that option `5` is fine, as it provides a template that the user can then modify.

I'm opening this issue so that we can decide on the best strategy, and I'll then try implementing it.

**Comment by stamourv** [comment]
4 or 5 both sound fine to me. It would be nice to also have the latest release, but that does require network access. I guess `raco pkg new` could just try to get access to the release info, and if it fails, just swallow the exception and skip adding that version.

**Comment by jackfirth** [comment]
If you're going to include HEAD, you might want to make it exempt from failure in the Travis build matrix. I've found it a bit too unstable for external packages to tie themselves to in CI.

**Comment by stamourv** [comment]
Oh, interesting. I've found HEAD pretty stable in general. Any recent issues you remember?

**Comment by jackfirth** [comment]
There are two issues that come to mind, the latter more troublesome than the former:

1. Some time ago when @AlexKnauth and I were working on the lens library, every once in a great while the build against HEAD would fail while everything else passed, typically due to some odd macro bug somewhere in the latest version of racket. Reporting the bug and waiting for a fix wouldn't take too long, but we didn't want our CI process dependent on this.
2. Attempting to download the source would fail relatively often due to network issues. Setting up a retry isn't too hard, but it's more complex than I'd like for a CI script and it drastically increases build times.

**Comment by stamourv** [comment]
How about using the nightly builds instead of HEAD? Wouldn't help with 1, but would help with 2.

**Comment by jackfirth** [comment]
That would probably work much better. Avoiding doing a git pull and install would go a long way towards making the "recent Racket" build as reliable as the released Racket builds.

**Comment by AlexKnauth** [comment]
Doesn't it already use the nightly builds for that already?

**Comment by jsmaniac** [comment]
Yes, greghendershott's `travis-racket` script, which is used by the currently generated `.travis.yml` uses the nightly builds for what it calls `HEAD`.

The generated `.travis.yml` also contains the following lines to make failures on HEAD acceptable:

```
matrix:
  allow_failures:
#   - env: RACKET_VERSION=HEAD
```

It's currently commented-out, but I can un-comment that line.

**Comment by jsmaniac** [comment]
@stamourv by the way, do you happen to know (roughly) where the release info is available online?

**Comment by stamourv** [comment]
http://download.racket-lang.org/version.txt

**Comment by sorawee** [comment]
`raco pkg new` now uses @Bogdanp's `setup-racket`, but the issue remains. I agree that we should not need to modify `raco pkg new` every now and then.

Perhaps `setup-racket` should have a version `"stable"` which is always updated to the most recent Racket version. The default could then be:

```
racket-version: [<<raco-version>>, "stable", "current"]
```

Perhaps `setup-racket` could also dedup versions. For example, if `<<raco-version>>` = `"7.9"` and the most recent Racket version is 7.9, then there's no need to run both `"7.9"` and `"stable"`.

**Comment by jackfirth** [comment]
I suggest `"latest"` for consistency with the docker images.

**Comment by sorawee** [comment]
It's unfortunate that `current` is "later" than `latest `...

**Comment by Bogdanp** [comment]
https://github.com/Bogdanp/setup-racket/pull/17 adds a `stable` version to `setup-racket` based on the [`version.txt`](http://download.racket-lang.org/version.txt) file that @stamourv mentioned above. I went with `stable` because that's what the version is called in that file and to avoid the confusion between `current` and `latest`. I'd rather not change `current` to something else at this point to avoid making it painful for projects that use the action to upgrade when they need/want to. 

> Perhaps setup-racket could also dedup/aggregate versions. For example, if <<raco-version>> = "7.9" and the most recent Racket version is 7.9, then there's no need to run both "7.9" and "stable".

Multiple versions are usually set up at the matrix level in GH Actions, which is a higher level of abstraction than what the action has access to so I don't think there's a way to do this.

**Comment by mflatt** [comment]
It looks like recent changes have addressed the issue. Is that right, or are there still things that could be done?

**Comment by sorawee** [comment]
Yeah, it doesn't look like there's anything to do here. It looks like we still need to modify `racket/collects/pkg/private/new.rkt` every now and then to bump the `setup-racket` when @Bogdanp releases a new version, but that's a fact of life, I guess.

Closing.
