### ISSUE TITLE
output scribble/text to file in DrRacket

### ISSUE THREAD

**Issue by Ninlives** [racket/racket#1550]
Say I have a file "MOU.scrbl", its content is 
```
#lang scribble/text

@(define pub "public")

@pub static void main()
```
and another file "out.rkt":
```
#lang racket
(parameterize ([current-output-port (open-output-file "fn.java" #:exists 'truncate)])
  (dynamic-require "MOU.scrbl" #f))
```

Run the latter one in DrRacket will create an empty file.
Change the exists flag to `'can-update` will create an empty file if the file doesn't exists.Otherwise it acts as it should be.
Run in command line using `racket` works fine.

OS: Debian 8.6
Arch: X86_64
Racket: 6.7

**Comment by rfindler** [comment]
This program doesn't close the port it opened for `fn.java`, which is why you're not seeing the output.  I recommend you use `call-with-output-file`, e.g.:

```
#lang racket
(call-with-output-file "fn.java"
  (λ (port)
    (parameterize ([current-output-port port])
      (dynamic-require "MOU.scrbl" #f)))
  #:exists 'truncate)
```

To make DrRacket behave more like racket here, you could evaluate `(exit)` in the REPL. That'll close the ports and will probably cause the data that's pending to be flushed. (But better to close the port explicitly yourself, as above.)
