### ISSUE TITLE
Missing type for range-proc with new macro wrapper

### ISSUE THREAD

**Issue by jsmaniac** [racket/racket#1560]
@lexi-lambda Due to the macro wrapper for `range` in https://github.com/racket/racket/commit/597661fa4e90475843318d052859aedabbcff9f7, Typed/Racket does not know anymore about the type of `range`, and complains:

```
 Type Checker: missing type for identifier;
 consider using `require/typed' to import it
  identifier: range-proc
  from module: racket/list
  in: (range 5)
```

**Comment by lexi-lambda** [comment]
This is probably an issue with Typed Racket, not Racket (though I am willing to look into fixing it, since I broke it). I would imagine it would need to do the same thing with `in-range`, since `in-range` also expands into an internal procedure. @samth, do you know off the top of your head what needs to be done here?

**Comment by jsmaniac** [comment]
@lexi-lambda Thanks for the fix!
