### ISSUE TITLE
ptr-ref: contract violation when building documentation

### ISSUE THREAD

**Issue by wargrey** [racket/racket#1572]
```
raco setup: 0 rendering: <pkgs>/racket-index/scribblings/main/release.scrbl
ptr-ref: contract violation
  expected: (and/c cpointer? (not/c (lambda (p) (pointer-equal? p #f))))
  given: ffi-obj
  argument position: 1st
  other arguments...: ctype
  context...:
   /opt/racket/collects/ffi/unsafe.rkt:205:2: get-ffi-obj*
   /opt/racket/collects/net/osx-ssl.rkt: [running body]
   /opt/racket/collects/net/http-client.rkt: [traversing imports]
   /opt/racket/collects/net/url.rkt: [traversing imports]
   /opt/racket/collects/planet/private/resolver.rkt: [traversing imports]
   /opt/racket/collects/planet/resolver.rkt: [traversing imports]
   /opt/racket/share/pkgs/scribble-lib/scribble/tag.rkt: [traversing imports]
   /opt/racket/share/pkgs/racket-index/setup/scribble.rkt: [traversing imports]
raco setup: 0 rendering: <pkgs>/schema/tamer/schema.scrbl
raco setup: 0 rendering: <pkgs>/racket-index/scribblings/main/start.scrbl
raco setup: 0 rendering: <pkgs>/racket-index/scribblings/main/local-redirect.scrbl
raco setup: 0 rendering: <pkgs>/racket-index/scribblings/main/search.scrbl
```
------
This occurs in OpenIndiana, then the building process keeps waiting (the broken worker?) and refuses to terminate itself.

**Comment by mflatt** [comment]
Thanks for the report!

Is this with a release or with a snapshot or git checkout that includes 78bbcec9633110e9cb8027cfe0b828f4722392ed?

**Comment by wargrey** [comment]
Yes, it's git checkout, and 8bbcec is found.

**Comment by mflatt** [comment]
Just to make sure, do you see the same error with `raco setup -j 1`?

I'm puzzled by the `given: ffi-obj` in the error message. Maybe something in the document configures printing, but does it really show up that way, without `#<...>`?

**Comment by wargrey** [comment]
Sorry my bad.
It's `#<ffi-lib>`, I removed `#<>` because markdown eats them.
The same to `#<ctype>` (sometimes it's displayed as `#<ctype:pointer>`.

In this morning, I never saw it with `-j 1`, without `-j`, it occurs or not at random.

Here is another off-topic question.
I see `(processor-count)` returns a constant 2 in Solaris, one year ago I modified the C source (and linked with `kstat`) to get the correct count, it built as expected, but even a simple future program crushed racket due to segfault. Do you have plan to solve it? For me, it's just curious since there are other ways to get the correct count and parallel programs can work as expected.

**Comment by mflatt** [comment]
Since this report, there have been some repairs for futures and places — and, of course, a whole new runtime system.

Unfortunately, I haven't been able to check for crashes, because I keep getting kernel panics when using an October 2020 Hipster installation in VirtualBox on Mac OS with either 1 or 2 cores when using `-j 2`. I hit one panic while installing a system package, so I imagine it has to do with the VirtualBox setup. (The Northwestern snapshot builds on OpenIndiana regularly, but not with multiple CPUs, and the documentation is pre-rendered.)

If you have any interest in checking again, that would be great. Otherwise, I'm inclined to close the issue for now until/unless it shows up again.

**Comment by wargrey** [comment]
Okay, it’s reasonable to close this issue.

I have stopped using OpenIndiana since the death of my laptop installed it.
