### ISSUE TITLE
DrRacket.app resides in /usr/local/bin using raco install on OS X

### ISSUE THREAD

**Issue by romatthe** [racket/racket#1575]
This was already touched upon a year ago in #1180, but I'm still having some trouble with this. 

After performing `brew install minimal-racket` on OS X 10.12.1, I installed DrRacket using `sudo raco pkg install --auto drracket`. The installation seems to work just fine, but DrRacket.app is not placed in `/Applications`, instead it resides in `/usr/local/bin/DrRacket.app`.

Note that DrRacket itself works just fine, both `racket -l drracket/drracket` and `open /usr/bin/local/DrRacket.app` work flawlessly. The only problem is the placement of the .app file. The same goes for `Racket Documentation.app`, though I'm not sure what its origin is.

I'm also not sure if this is a problem only related to DrRacket or to all applications installed through raco.

**Comment by mflatt** [comment]
I see that the Homebrew formula for Racket sets `bindir` to "/usr/local/bin", so that's why applications end up there. I've added a `guibindir` setting that overrides `bindir` for GUI applications (i.e., ".app"s on Mac OS) and could be set to "/Applications".

I'm not sure that's the right solution, but it might be a good idea, and I think a separate `guibindir` setting makes sense, anyway.

**Comment by mflatt** [comment]
Homebrew now includes a Racket cask that installs to `/Application/`.

So, it's still true that installing `minimal-racket` via Homebrew plus `raco pkg install drracket` will put DrRacket in `/usr/local/` or `/opt/homebrew/`, but installing a cask is generally the way to go for GUI programs via Homebrewq.
