### ISSUE TITLE
raco test is broken w/o --process

### ISSUE THREAD

**Issue by zenspider** [racket/racket#1585]
Using the same code in #1584, if you try to run the file with a normal `raco test` it blows up. (it's been working absolutely fine in racket-mode, so I was very surprised by this). If you run with `--process` then it works as expected.

```
2954 % raco test 12i.rkt
raco test: (submod "12i.rkt" test)
begin: unbound identifier;
 also, no #%app syntax transformer is bound
  at: begin
  in: (begin (module cpu-mod "12i.rkt" (provide pc a b c d result) (run (list (inc a)))) (dynamic-require (quote (quote cpu-mod)) (quote result)))
  context...:
   (submod /Users/ryan/Work/git/searbsg/advent_of_code/zenspider/12i.rkt test): [running body]
   /MyApplications/dev/lisp/Racket/share/pkgs/compiler-lib/compiler/commands/test.rkt:176:16
12i.rkt: raco test: test raised an exception
2 tests passed
```

versus:

```
2955 % raco test --process 12i.rkt
raco test: (submod "12i.rkt" test)
cpu time: 0 real time: 0 gc time: 0
'((pc 1) (a 1) (b 0) (c 0) (d 0))
cpu time: 0 real time: 0 gc time: 0
'((pc 2) (a 0) (b 2) (c 0) (d 0))
cpu time: 0 real time: 0 gc time: 0
done
5 tests passed
```

**Comment by mflatt** [comment]
I'd say this is a deficiency of `raco test --process`, because it ends up filling the initial namespace with `racket/base`, but the initial namespace should be empty.

Unfortunately, when you change the `test` module to `main` and run with `racket 12i.rkt`, then it also works. That's a little subtle: `racket 12i.rkt` first requires the overall module into the current namespace, which in this case provides `begin`, and then it requires the `main` submodule. So, again, things work out, but more or less accidentally.

Maybe another way to put it is that using `eval` without a specific namespace is asking for trouble, and various ways of running a module will unfortunately oblige with trouble.

**Comment by mflatt** [comment]
I don't think we can change anything here without breaking existing workflows, but doc clarifications in 8962b027fe5c4a0d04ef5c6853d2fab7ad593ce4 hopefully help a little.
