### ISSUE TITLE
Profiling returns empty profile on DragonFlyBSD

### ISSUE THREAD

**Issue by markuspf** [racket/racket#1597]
I was trying to profile some code, but both `raco profile` and using `(require profile)` and profiling thunks returns an empty profile. My test code is as simple as this

```
#lang racket

(require profile)

(define (f x) (foldr + 0 (range x)))

(profile (f 10000000))
(profile (foldr * 1 (range 1 100)))
```

The returned profile looks like this

```
Profiling results
-----------------
  Total cpu time observed: 12659ms (out of 11764ms)
  Number of samples taken: 53 (once every 239ms)

====================================
                        Caller
Idx  Total    Self    Name+srcLocal%
     ms(pct)  ms(pct)   Callee
====================================
49999995000000
Profiling results
-----------------
  Total cpu time observed: 0ms (out of 0ms)
  Number of samples taken: 0 (once every 0ms)

====================================
                        Caller
Idx  Total    Self    Name+srcLocal%
     ms(pct)  ms(pct)   Callee
====================================
933262154439441526816992388562667004907159682643816214685929638952175999932299156089414639761565182862536979208272237582511852109168640000000000000000000000
```

I am running recent DragonFlyBSD master with racket 4.7 built from dports. Happy to help debugging and submit a PR once someone can point me to the relevant bits of code to prod at.

If anyone has a FreeBSD system to hand it'd be interesting to know whether it works there.

**Comment by stamourv** [comment]
Hi Markus, and sorry for the delay.
I can reproduce with Racket 6.9 (from download.racket-lang.org). I get an empty profile for your program on Dragonfly BSD. But, if I disable the JIT (using the `-j` flag), the profile is what we expect.
I also tried on FreeBSD, per your recommendation, and it works both with and without JIT.

The issue seems to be that the samples taken by the profiler have empty stack traces.
If you'd like to take a look, the relevant code is likely `scheme_native_stack_trace`, in `racket/src/racket/src/jitstack.c`, line 162. I don't directly see anything that would differ between FreeBSD and dragonfly, but the differences may come from definitions in `racket/src/racket/sconfig.h`.

**Comment by mflatt** [comment]
I'm not sure if this got any better for BC — there were some small changes for stack traces along the way — but the solution here is to replace BC with CS, which has reliable stack traces. (Well, reliable modulo optimizations, but no platform sensitivities.)

I don't know whether Racket CS already compiles on DragonflyBSD, but there should be no particular obstacle to updating build configurations if it doesn't work an there's any interest.
