### ISSUE TITLE
weak box value seems to be collected before it should be.

### ISSUE THREAD

**Issue by dfeltey** [racket/racket#1613]
This program: 
```
#lang racket

(let ()
  (define fc1 (list 7))
  (define wb (make-weak-box fc1))
  (define fc2 (list fc1))
  (set! fc1 #f)
  (collect-garbage)
  (collect-garbage)
  (collect-garbage)
  (begin0 (weak-box-value wb) fc2))
```
Produces `#f`, but it seems that the reference to the original value of `fc1` contained in `fc2` in the `begin0` expression should prevent the value from being collected since it is referenced after accessing the value inside the weak-box.

**Comment by stamourv** [comment]
FWIW, if you actually use that `fc2` (e.g., call `display`) in the `begin0`, it holds on to the value.

What I suspect is going on is that that reference to `fc2` is considered "omittable" by the optimizer, and so is optimized away.

I think one could argue that this behavior is in line with the intended behavior of weak boxes, though.

**Comment by rfindler** [comment]
I think that the semantics of references should be pinned down in such a
way that this program reveals a bug. (I can understand if it is too much
work to fix the optimizer, and so we pass on that part.)

If the reference had been before the weak-box-value call, then I agree with
you -- it is fine for the box to either contain the value or not.

**Comment by gus-massa** [comment]
I think that the current behavior is correct but surprising. It would be good to change the  [docs about weak box](https://docs.racket-lang.org/reference/weakbox.html) to make it more clear this possibility. (And probably the docs of weak hashes and ephemerons too.)

Weak box are a little too low level constructions and the abstractions may leak. It’s possible to detect  that a reference that is apparently alive has been collected using  current-memory-use or the order of the wills and executors.

Fixing this particular example is not too difficult (I think). It’s just enough to use a flag to keep the reference in the optimizer phase, and add the code to remove most of them later in the safe-for-space phase. 

It’s more complicated if you also want to change the case where you place the last `fc2` with `(if #f (display fc2) 7)` or `(if (box? (box 0)) (display fc2) 7)`. (This kind of code is more usual than expected after expansions and inlining.) The problem is that all the references in the discarded branch must be saved, without executing the code.

And with inlining, there are more interesting examples. 

    #lang racket
    
    (define (test z)
      (define fc1 (list (random) z))
      (define wb1 (make-weak-box fc1))
      (define fc2 (lambda () (void fc1) (displayln "*") z))
      (define wb2 (make-weak-box fc2))
      (collect-garbage)
      (collect-garbage)
      (collect-garbage)
      (list (weak-box-value wb1)
            (weak-box-value wb2)
            (fc2)
            (when #f (fc2))))
    
    (test 5)
  
The call `(fc2)` is inlined, so it disappears. But if you keep a reference to `fc2` then it will be necessary to keep a reference to `fc1` too. I’m worry that this change will keep to many things alive for too long. In particular, I worry that this will keep too much memory alive during recursions in loops, but I still couldn’t write a good example for this.

**Comment by mflatt** [comment]
Note that this isn't just a question of the core optimizer. For example, when you have
 `(define (f #:x [x 0]) ...)`
and
 `(f #:x 1)`
then the expansion of the call doesn't include a reference to `f`; instead, it refers directly to part of the implementation that takes optional-argument values and optional-argument flags to say whether the value was provided.

We could certainly design a language where keyword-argument applications are obliged to retain a reference to the general function, but I'm suggesting that there are likely many macros that would not be consistent with liveness defined in terms of identifier reference.

Naturally, I agree with @gus-massa that `make-weak-box` is a relatively low-level operation and intentionally underspecified (i.e., defined in terms of what the GC can prove, which is intentionally underspecified). I'd put it in the same category as `eq?`; it's not as bad as operations that we prefix with `unsafe-`, but maybe those operations deserve an `underspecified-` prefix. We'd rather throw out those operations than constrain the compiler and GC to make them fully specified, but we'd also rather have them for limited use than not have them at all.

I've occasionally run into the problem of keeping a value live when working with low-level features like weak boxes, and my solutions have involved implicit claims about what the GC would be able to prove. I think it would be useful to have some `observe` primitive that always returns `(void)` but where the GC is specifically not allowed to know whether `observe` uses any part of its argument (even though it doesn't).

**Comment by rfindler** [comment]
I'm happy to defer to @mflatt and @gus-massa on these points overall, but I think that the rules about when a variable reference can be eliminated can be made clear based on how safe-for-space works. In particular, if an optimizer can prove that `e1` always evaluates to `#t`, then it is safe to eliminate the `fc2` reference in this expression:

  `(if e1 e2 fc2)`

as the safe for space rules would never hold on to fc2. Or, put another way, a GC could have happened after the evaluation of the test position and before whatever weak boxes that `e2` might check.

But that reasoning does not work for the expression in the initial issue that Dan posted. In that case, the variable reference should be holding onto `fc2`.

I see what @mflatt means about this being an issue for macros too, and hadn't considered that before. I agree that makes the issue more sticky.

I think that one thing that distinguishes Racket from other languages out there is our grounding in PL theory, and so this is one place where I'd naturally lean towards preserving the semantics, since we know what a good semantics is. But I'll get off my soap box now ;)

**Comment by mfelleisen** [comment]
> On Feb 7, 2017, at 11:22 AM, Matthew Flatt <notifications@github.com> wrote:
> 
>  we prefix with unsafe-, but maybe those operations deserve an underspecified- prefix.


+1
+10
+100
. . .

**Comment by mflatt** [comment]
The function `void/reference-sink` was added in v6.10.1.2 (i.e., later in 2017) to `ffi/unsafe`. So, there's now at least a way to reliably retain a reference.
