### ISSUE TITLE
“git-checkout” fails when it can’t reuse the connection

### ISSUE THREAD

**Issue by leafac** [racket/racket#1616]
For context, see https://github.com/tonyg/racket-pkg-website/issues/36.

My investigation led me to believe that `git-checkout` is to blame for the issue. It [reuses the HTTP connection](https://github.com/racket/racket/blob/b3223ad8d2ef285e11394fcd4e42af0a13e4775c/racket/collects/net/git-checkout.rkt#L742-L764) for multiple `http-conn-sendrecv!`. But, as the following script demonstrates, `http-conn-sendrecv!` (in particular, `http-conn-recv!`) might have the side effect of closing the connection:

```racket
#lang racket
(require net/http-client)

(define conn (http-conn))
(http-conn-open! conn "git.leafac.com" #:ssl? 'secure #:port 443)
(http-conn-sendrecv! conn "/")
(http-conn-live? conn) ; => #f
(http-conn-sendrecv! conn "/") ; => Raise contract violation
```

I believe the correct move is to change `read-dumb-objects` (as well as helper functions, for example, `get-packfile-list`) in `git-checkout.rkt` to use a fresh HTTP connection for each request. For example, using `http-conn-sendrecv` instead of `http-conn-sendrecv!`.

I’d like some feedback before working on a pull request. In particular, from the people that worked on `git-checkout` (@mflatt, @florence, @rfindler and @lexi-lambda) and @jeapostrophe which helped me in the investigation.

**Comment by jeapostrophe** [comment]
Excellent. At least `git-checkout.rkt` could confirm that the connection is still live before trying to use it

**Comment by mflatt** [comment]
Continuing @jeapostrophe's comment: A fresh connection could be noticeably slower for servers that support reusing the connection. Instead of using a fresh connection every time, probably the best approach is to check whether the connection is closed and then reopen it.

Maybe the `conn` should be wrapped with another layer that remembers the host and port, and then a wrapper on `http-conn-sendrecv!` would check whether the connection is still open and reopen as needed each time.

**Comment by leafac** [comment]
Thank you for the feedback. I feel like a wrapper around the `conn` is the best compromise between performance and correctness. But I think it wouldn’t belong in `git-checkout`, but as a separate widget in `http-client`. What’s your opinion?

**Comment by jeapostrophe** [comment]
I agree, `http-conn-open/reuse`?
