### ISSUE TITLE
generics: expose generic-property and generic-method-table?

### ISSUE THREAD

**Issue by AlexKnauth** [racket/racket#1647]
Should we expose and document `generic-property` and `generic-method-table`, two of the internal macros in `racket/private/generic-methods.rkt`?

An example usage would be
```racket
(struct name [field ...]
  #:property (generic-property gen:interface)
  (generic-method-table gen:interface
    method-def ...))
```

These macros are currently being used by both Rosette and Typed Rosette for different reasons. Rosette needs them for lifting structs to work as symbolic values, and Typed Rosette needs them to expand to after typechecking generic method implementations.

This was first asked in `generics: optional scope argument for private macros` (https://github.com/racket/racket/pull/1644).

**Comment by stamourv** [comment]
I'd rather not. That's an internal interface, and we may want to change it.

**Comment by rfindler** [comment]
Sounds to me like you already lost that capability. :(

**Comment by mfelleisen** [comment]
Really? The require path includes ‘private’ and that means ‘sorry, you can get hurt at any point in time’

**Comment by rfindler** [comment]
Well, I know that is what it is supposed to mean, but when an important app gets broken by change, it seems to me, we don't want to make that change. 

And to be clear, no one here is suggesting any need or plan to make any change, right?

**Comment by stamourv** [comment]
Right. No plan to change anything. Just trying to keep options open for the future.

**Comment by rfindler** [comment]
I think that the best way, in this situation, to make a good future for Racket is to look at what those libraries really need from their use of the private library's code, think about how to provide it in a future-friendly way and then ask them to change their implementations.

I find it hard to believe they would have used the private code lightly (although it is possible) and one way to interpret the use of "private" is a require for a pull request to provide that functionality (or something like it) publicly.

**Comment by AlexKnauth** [comment]
For Typed Rosette in particular, the thing that it needed was a way to specify the scope of the method implementations with a separate identifier from the gen:interface identifier used to look up the property and method names.

This functionality could be provided in a more public way, so that a syntax like
```racket
(struct name [field ...]
  #:methods gen:interface #:method-scope here
  [method-def ...])
```
Could be used instead of the private macros.

**Comment by mfelleisen** [comment]
@rfindler Another way to interpret ‘private’ then is to say it means nothing. If so, I consider this a serious gap in our language. We can’t say anything that remains truly private, so Racket lacks a lot of expressive power.

**Comment by stamourv** [comment]
@AlexKnauth: You're describing an implementation. What's the use case?

**Comment by rfindler** [comment]
@mfelleisen If what you're saying is that we need a linguistic mechanism to play the role of the convention that `private` in a path in a require currently plays then yesterday I would have completely and enthusiastically agreed with you. But today, I start to realize that this flexibility we have in the current system has its own value, namely that it lets someone implement something in Rosette without having to bother the implementors of the generics system to get them to change something.

So maybe what I think we want is a linguistic mechanism that allows this kind of thing but that also makes it easier or somehow encourages us to find ways to accommodate these uses in a way that's public and that the authors of the library (the generics in this case) are comfortable with.

Not sure such a thing is possible, tho!

**Comment by AlexKnauth** [comment]
@stamourv Re: For Typed Rosette in particular:

The only use case is for macros to expand to it without being denied by the default scoping rules. That's why it feels weird to add this to the main `struct` syntax.

**Comment by LiberalArtist** [comment]
A different use case I can think of for having access to `generic-property` and `generic-method-table`: since `interface*` can associate arbitrary structure-type properties with a class-based object, this would allow classes to implement generic interfaces, which they can't do currently except via defaults.

On the private issue, as a user, I definitely understand "private" to mean that no guarantees are made, but the times when I will actually require someone else's private module are I think what @rfindler describes: when I can almost make use of some library, but need some small additional piece of functionality that isn't exposed. Personally I would make a pull request rather than rely on this in a finished product (or fork the library if needed).

**Comment by rfindler** [comment]
re "finished": I'm not sure we really want to make decision decisions in the language around the concept of finished software. Software is never finished.

**Comment by AlexKnauth** [comment]
@LiberalArtist But that would be better suited for a public interface added to `racket/class`. The `racket/class` module would require the private module, but the user shouldn't have to.

**Comment by stamourv** [comment]
@AlexKnauth: I also don't like the idea of adding a method-scope argument to the struct form. Exposing generics' internal interfaces (as you originally suggested) would be less bad, IMO, but still not ideal.

Could you get what you want by changing how the generics library uses scopes internally?

**Comment by AlexKnauth** [comment]
I could change it to use the scope of the struct name instead of the interface name... But I don't know whether we can do that without breaking other things. The way generics uses scope, it has to be *exactly* right, not just the largest-subset relationship. Anything other than an exact match will result in either failing to implement the method or raising an ambiguous binding error.

**Comment by rocketnia** [comment]
To chime in, I've found myself wanting this kind of feature just for library design. Specifically, it would make it more seamless to deprecate deprecate certain generic interfaces in favor of more expressive ones. Currently, structure type properties have a more seamless experience here.

Suppose I write a library A, and one of my users builds a library B that wraps it and exposes all the same functionality with a different interface. Eventually, B is just a better experience than A all around, so as a collective decision, that developer and I agree we should convert library A into a legacy wrapper around library B instead.

If I originally export a structure type property descriptor from library A, then the developer of library B can use the `supers` argument to [`make-struct-type-property`](https://docs.racket-lang.org/reference/structprops.html?q=make-structure-type-property#%28def._%28%28quote._~23~25kernel%29._make-struct-type-property%29%29) to define their own structure type property that abstracts over it. Then their own users won't need to know this one is implemented in terms of mine; they'll only need to know that when the two property descriptors are used together, they can overlap and conflict with each other. When it comes time to reverse the relationship between libraries A and B, we can simply make my property into a wrapper around theirs instead.

If I only export a generic interface from library A, then the developer of library B can't define their own generic interface that wraps it in the first place. If they define a generic interface or structure type property that we both agree is better than mine, we have no backwards-compatible option for merging them because some users may have already implemented both interfaces on the same structure type without getting an overlap error. The best we can do is to ask users to migrate.

But a generic interface can already be defined to wrap a structure type property descriptor using `#:derive-property`, so if we also had an operation like `generic-property` to convert a generic interface to a property, then generic interfaces could abstract over each other.

I don't really know the extent of what Rosette needs, but at least for the deprecation purposes I'm describing here, the `generic-property`-like operation wouldn't need to expose the internal representation of generic methods. It could very well use its own representation and convert between them during its `guard` and `supers`. (I think it would even be *preferable* to use a different representation here; the internal one represents methods in a particular order, and authors of generic interfaces might think of that order as an implementation detail.)

For Rosette's purposes, and for authors of any other `struct`-like syntax, having some `generic-method-table`-like syntax to construct first-class values out of `#:methods` blocks would be nice. Again, I don't think it would necessarily need to expose the actual internal representation, just some representation that would make it possible to define `struct`-like syntaxes.

@AlexKnauth Does that seem like enough? I notice Rosette currently relies on a little more specific functionality, particularly the ability to check whether a given property descriptor is `equal?` to `(generic-property gen:equal+hash)`, but it looks like if Rosette had been able to define its own `gen:equal+hash` that abstracted over the existing one, that would have been the approach taken in the first place.

**Comment by AlexKnauth** [comment]
@rocketnia Yes, there's an asymmetry between:
 - you _can_ define a generic-interface or property that inherits from a property
 - you _can't_ define a property that inherits-from/wraps/implements a generic interface

There is no `#:methods gen:interface [definition ...]` keyword for `make-struct-type-property`. Exposing `generic-property` and `generic-method-table` would allow someone to make a macro for defining structure properties that could have a `#:methods` keyword.

Something like
```racket
(define-struct-type-property [prop:duck duck? duck-ref]
  #:methods gen:sound
  [(define (play-sound self)  (quack!))]
  #:methods gen:move
  [(define (move self dir)  (walk! (duck-ref self) dir))]
  #:methods gen:custom-write
  [(define (write-proc self out mode)  (fprintf out "🦆"))])
```

**Comment by LiberalArtist** [comment]
I was reminded of this recently, and it struck me that, currently, generic interfaces rely on special support from `struct` for their `#:methods` clause. To borrow @AlexKnauth's example:
> For Typed Rosette in particular, the thing that it needed was a way to specify the scope of the method implementations with a separate identifier from the gen:interface identifier …
> 
> This functionality could be provided in a more public way, so that a syntax like
> 
> ```racket
> (struct name [field ...]
>   #:methods gen:interface #:method-scope here
>   [method-def ...])
> ```
supporting `#:method-scope` would mean a change to the grammar for `struct`.

As I understand it (which is not very deeply), the reason for `#:methods` rather than:
> ```racket
> (struct name [field ...]
>   #:property (generic-property gen:interface)
>   (generic-method-table gen:interface
>     method-def ...))
> ```
is to statically guarantee that the property and method table always come from the same generic interface.

It seems like there are probably cases other than generics when it would be useful to statically enforce a connection between a property and its associated value. Adding new keywords to `struct` doesn't scale, and it means new constructs can't be implemented as libraries.

Meanwhile, people have also identified places other than `struct` where they want to be able to use generics, without breaking the tie between the property and the corresponding value:

- as arguments to `make-struct-type-property`, allowing properties to inherit from generic interfaces (raised by @rocketnia above)
- as arguments to `make-struct-type` for dynamically-created struct types (raised by @pmatos in https://github.com/racket/racket/issues/2142, though it turned out that he didn't need `make-struct-type` in that case)
- with `interface*` from `racket/class`, allowing objects to implement generic interfaces.

I think an alternative approach would be to use a tamper-proof run-time value to package together the private property and a known-good value. Then macros from libraries like `racket/generic` could simply expand to expressions: other macros like `struct` or `interface*` wouldn't need to handle them specially, and it would be more reasonable for a library to provide fine-grained options (like the `#:method-scope` that started this thread) than to have to build all potential options into `struct` (and
everywhere else).

A new type of value designed for this purpose might be especially elegant, but I think (inspired by the discussion between @rocketnia and @AlexKnauth) you could do this now by creating a derived struct type property that just ignores its immediate argument. For example (this runs):
```racket
#lang racket

(require racket/private/generic-methods)

(define-syntax-rule (make-generic-struct-type-property gen:interface
                                                       method-def ...)
  (let ([prop (generic-property gen:interface)]
        [methods (generic-method-table gen:interface method-def ...)])
    (make-struct-type-property 'gen:interface #f
                               (list (cons prop (λ (ignored) methods))))))

(match-define-values [prop:silly-dict _ _]
  (make-generic-struct-type-property
   gen:dict
   (define (dict-ref self k [default #f])
     'i-am-a-dict)))

(struct example ()
  #:transparent
  #:property prop:silly-dict 'ignored)

(dict-ref (example) 42) ;; -> 'i-am-a-dict
```

**Comment by rocketnia** [comment]
I like that approach for `make-generic-struct-type-property`. It neatly avoids exposing any details about how the method table is represented.

Aesthetically, I think it might look a bit more seamless with the language design if the property value isn't ignored. How about if the `make-generic-struct-type-property` form binds a local variable that makes it easy for the methods to refer to the property value?

```racket
(define-syntax-rule (make-generic-struct-type-property gen:interface
                                                       prop-value
                                                       method-def ...)
  (let ([prop (generic-property gen:interface)])
    (define (methods prop-value)
      (generic-method-table gen:interface method-def ...))
    (make-struct-type-property 'gen:interface #f
                               (list (cons prop methods)))))
```

It might appear this change makes the operation more expressive, but as far as I can tell, all the techniques the new `prop-value` variable facilitates could still be achieved without `prop-value`:

* Rather than using `prop-value`, if the method implementations need to depend on the property's value, they can call the property's accessor. This isn't quite the same thing if impersonators are involved, but if the programmer is worried about that, they can redundantly store the value in a second, non-impersonatable property.

* Rather than using `prop-value`, if the `method-def ...` body (_outside_ the method implementations) needs to use the property's value, I think that part of the computation can be factored out into a separate structure type property which performs that computation in its guard procedure.

**Comment by tail-reversion** [comment]
I don’t claim to know about the implementation and design details of this issue, but I’d greatly appreciate if there were a way to implement generics via `make-struct-type`, which is a critical necessity for my `#lang`.

As such, I’m curious to know if there’s any consensus about how to proceed with this issue, or is progress still in the discussion phase?

**Comment by AlexKnauth** [comment]
I like the suggestion for `make-generic-struct-type-property` by @LiberalArtist. I would be inclined to choose that over rocketnia's version because LiberalArtist's version only evaluates the method definitions once on property-creation, while rocketnia's version evaluates the method definitions each time the property is attached to a struct-type. 

But I suppose I would like either of their versions over my original suggestion of exposing `generic-property` and `generic-method-table`

**Comment by rocketnia** [comment]
That's a good consideration. I'd be good with any of these, really.

**Comment by jackfirth** [comment]
I'm also in favor of both versions of `make-generic-struct-type-property` with a slight bias towards the version that evaluates method definitions once on property-creation. I'm against exposing `generic-property` and `generic-method-table` directly.

Instead of ignoring the property's value, could we mandate that it be `#false` and raise an error otherwise? Perhaps `make-generic-struct-type-property` should return _only_ the `prop:` value and not return the accessor and predicate at all.

**Comment by AlexKnauth** [comment]
Here's what I would do based on @LiberalArtist's suggestion:
```racket
(make-struct-type-property/generic
  name-expr
  maybe-guard-expr
  maybe-supers-expr
  maybe-can-imporsonate?-expr
  option
  ...)
maybe-guard-expr =
                 | guard-expr
maybe-supers-expr =
                  | supers-expr
maybe-can-impersonate-expr =
                           | can-impersonate-expr?
option = #:property prop-expr val-expr
       | #:methods gen-interface-id [method-def ...]
```
Produces 3 values just like `make-struct-type-property`.

```racket
(make-generic-struct-type-property
  gen-interface
  method-def
  ...)
```
Produces just the property value.

Implementation:
```racket
#lang racket/base

(provide make-struct-type-property/generic
         make-generic-struct-type-property)

(require racket/function
         racket/private/generic-methods
         syntax/parse/define
         (for-syntax racket/base))
(module+ test
  (require rackunit
           racket/dict))

(begin-for-syntax
  (define-splicing-syntax-class pmreotpheordtsy
    #:attributes [prop-super-pair]
    (pattern (~seq #:property prop:expr val:expr)
      #:with prop-super-pair
      #'(cons prop (const val)))
    (pattern (~seq #:methods gen-interface:id
                   [method-def
                    ...])
      #:with prop-super-pair
      #'(cons (generic-property gen-interface)
              (const (generic-method-table gen-interface method-def ...))))))

(define-simple-macro
  (make-struct-type-property/generic
   name:expr
   (~optional guard:expr #:defaults [(guard #'#f)])
   (~optional supers:expr #:defaults [(supers #''())])
   (~optional can-impersonate?:expr #:defaults [(can-impersonate? #'#f)])
   pm:pmreotpheordtsy
   ...)
  (make-struct-type-property name
                             guard
                             (list* pm.prop-super-pair ... supers)
                             can-impersonate?))

(define-simple-macro
  (make-generic-struct-type-property gen-interface:id method-def:expr ...)
  (let-values [((prop _pred _ref)
                (make-struct-type-property/generic 'gen-interface
                  #:methods gen-interface
                  [method-def
                   ...]))]
    prop))

(module+ test
  (test-case "silly-dict"
    (define prop:silly-dict
      (make-generic-struct-type-property
       gen:dict
       (define (dict-ref self k [default #f])
         'i-am-a-dict)))
    (struct example ()
      #:transparent
      #:property prop:silly-dict #f)
    (check-equal? (dict-ref (example) 42) 'i-am-a-dict)))
```

**Comment by rocketnia** [comment]
I'm happy to see that implementation, but... `pmreotpheordtsy`? I'm afraid I don't understand what you're going for there. How about `property-option` or `property-or-methods`?

**Comment by samth** [comment]
Now that @AlexKnauth has created a PR #3627  implementing some of the ideas discussed here, I hope that people who were involved in this discussion can comment there about whether it will solve your use cases.
