### ISSUE TITLE
Suggestion: struct/contract & struct/derived

### ISSUE THREAD

**Issue by winny-** [racket/racket#1699]
I really like contract programming, but was surprised when I noticed there is a define-struct/contract, but no struct/contract. Maybe racket should ship with a struct/contract syntax?

**Comment by LiberalArtist** [comment]
+1

**Comment by LiberalArtist** [comment]
And relatedly, a `struct/derived` similar to `define-struct/derived` would be very useful.

**Comment by hashimmm** [comment]
Additionally, since `define-struct/contract` supports `#:property`, it should be able to support `#:methods`, yes? Maybe `struct/contract` version could do that, too. Does that suggesteion merit a separate issue?

**Comment by LiberalArtist** [comment]
`struct` is actually implemented via `define-struct/derived`, so that part would be a particularly easy pull request, I think. I've never looked at the implementation of `define-struct/contract`, but I imagine it would be similar. The only difference between `struct` and `define-struct` is that `struct` adds a `#:constructor-name` option unless there already is one.

https://github.com/racket/racket/blob/5c775fa04c11697a25655b1738aa96f14368745a/racket/collects/racket/private/struct.rkt#L11-L28

**Comment by spdegabrielle** [comment]
Potential "Good first bug"?
If so - please add label.

**Comment by spdegabrielle** [comment]
Potential "Good first bug"?
If so - please add label.
Was suggested at https://github.com/racket/racket/wiki/Racketeer-Office-Hours-2017-Task-Ideas
