### ISSUE TITLE
Documentation: call-with-immediate-continuation-mark

### ISSUE THREAD

**Issue by mnieper** [racket/racket#1747]
In the documentation https://docs.racket-lang.org/reference/contmarks.html#%28def._%28%28quote._~23~25kernel%29._call-with-immediate-continuation-mark%29%29 it says that `call-with-immediate-continuation-mark` can be implemented with a combination of `with-continuation-mark`, `current-continuation-marks`, and `continuation-mark-set->list`.

I don't see how this can be done without using `continuation-mark-set->list*`.

**Comment by soegaard** [comment]
The trick is to use `wcm` to test whether the mark was set in the first frame.

```
#lang racket
(define-syntax wcm (syntax-rules () [(_wcm . more) (with-continuation-mark . more)]))

(define (call/icm key proc [default #f])
  (define marks (current-continuation-marks))
  (define vals  (continuation-mark-set->list marks key))
  (define val   (if (null? vals) default (car vals)))
  ; check whether val is from the first frame
  (define unique (list 'unique))
  (with-continuation-mark key unique
    (let ()
      (define new-marks (current-continuation-marks))
      (define new-vals  (continuation-mark-set->list new-marks key))
      ; The first value in new-vals is  unique.
      ; If the value after is val, then the mark wasn't immediate.
      (if (and (not (null? (cdr new-vals)))
               (eq? (cadr new-vals) val))
          (proc default)
          (proc val)))))

(define-syntax (test stx)
  (syntax-case stx ()
    [(_test expected expr)
     (syntax/loc stx
       (let ()
         (define res expr)
         (define ok? (equal? expected res))
         (unless ok?
           (displayln (list res expected '(call/icm . args))))))]))

; uncomment to test with Racket builtin primitives
; (define call/icm call-with-immediate-continuation-mark)

(define id (λ (v) v))
(test #f    (call/icm 'x id))
(test 10    (call/icm 'x id 10))
(test 12    (wcm 'x 12
                 (call/icm 'x id)))
(test '(#f) (wcm 'x 42
                 (list (call/icm 'x id))))
(test 12    (wcm 'x 12 
              (wcm 'y 13
                   (call/icm 'x id))))
(test 13    (wcm 'x 12 
              (wcm 'y 13
                (call/icm 'y id))))
(test 14    (wcm 'x 12 
              (wcm 'y 13
                (wcm 'x 14
                  (call/icm 'x id)))))

```

**Comment by mnieper** [comment]
Thank you very much for your reply!

The solution you propose is similar to what my first attempt was in trying to define `call-with-immediate-continuation-mark` through `with-continuation-mark`, `current-continuation-marks`, and `continuation-mark-set->list`. (The only difference between your solution and my first attempt is that I compared the length of the continuation mark lists instead of using a unique value.)

However, both solutions are not correct because the continuation mark set (for the given key) for the continuation of the call to `proc` will have been modified. For example,

```scheme
(with-continuation-mark 'x 10
  (call-with-immediate-continuation-mark 'x
   (lambda (y)
    (call-with-immediate-continuation-mark 'x values))))
```
should evaluate to `10`, but would evaluate to the unique value in your solution.

The working solution with `continuation-mark-set->list*` I am having in my mind is

```scheme
(define (call-with-immediate-continuation-mark key proc)
  (with-continuation-mark %secret-key #f
    (let ((marks
           (continuation-mark-set->list* (current-continuation-marks)
                                         (list key %secret-key))))
      (proc (vector-ref (car marks) 0)))))
(define %secret-key (vector 'secret))
```

(For simplicity, this solution assumes that the default value is `#f`, but this is easy to fix.)

Marc

P.S.: As a side note, does Racket compare keys for continuation marks using `eq?`, `eqv?`, or `equal?`. I couldn't find it anywhere in the documentation.

**Comment by soegaard** [comment]
You are right: we need to make sure the continuation of the call to `proc` isn't affected.
What if we simply restore the mark?

```
(define (call/icm key proc [default #f])
  (define marks (current-continuation-marks))
  (define vals  (continuation-mark-set->list marks key))
  (define val   (if (null? vals) default (car vals)))
  ; check whether val is from the first frame
  (define unique (list 'unique))
  (with-continuation-mark key unique
    (let ()
      (define new-marks (current-continuation-marks))
      (define new-vals  (continuation-mark-set->list new-marks key))
      ; The first value in new-vals is  unique.
      ; If the value after is val, then the mark wasn't immediate.
      (define immediate? (or (null? (cdr new-vals))
                             (not (eq? (cadr new-vals) val))))
      (with-continuation-mark key val
        (if immediate?
            (proc val)
            (proc default))))))

```

/Jens Axel

**Comment by mnieper** [comment]
This won't work either. In case of a non-immediate continuation mark, this solution would leave an extra continuation mark on the stack when `proc` is invoked.

The expression

```scheme
(with-current-continuation-mark 'x 0
  (+ 1
   (with-current-continuation-mark 'x 1
    (+ 1 (call-with-immediate-continuation-mark 'x
            (lambda (y)
             (cadr (continuation-mark-set->list (current-continuation-marks) 'x))))))))
```

should evaluate to `2`, and not to `3`. (Note that I introduced the increments by `1` to avoid tail-calls and to generate frames.)

Marc

**Comment by soegaard** [comment]
So we need a procedure that can remove a mark from an immediate frame.
I don't think there is a light-weight one. But it doesn't sound too hard to implement on a low level.

I attempted to make a version that used `call/cc` to capture the continuation before the test, and the then restore it after - but could not make it work.

FWIW here is the implementation of `call-with-immediate-continuation-mark` for the Chez Scheme backend:

[https://github.com/racket/racket7/blob/master/racket/src/cs/core/control.ss#L796](https://github.com/racket/racket7/blob/master/racket/src/cs/core/control.ss#L796)

Note that in Chez Scheme the expresison `(call/cc (lambda (k1) (call/cc (lambda (k2) (eq? k1 k2)))))` evaluates to true.

Wrt to the equality predicate used: I couldn't find it in the manual, but since

```
> (with-continuation-mark +0.0 'pos
    (with-continuation-mark -0.0 'neg
      (continuation-mark-set->list (current-continuation-marks) +0.0)))
'(pos)

```

it must mean that `eq?` is being used.

**Comment by mflatt** [comment]
I think @mnieper's original report is right. Looking back at the operation that we replaced when adding `call-with-immediate-continuation-mark`, it's essentially @soegaard's solution, so that implementation would leave an extra mark behind if it wasn't present already (which was good enough for the use in implementing contracts at the time).

I also agree that `continuation-mark-set->list*` can solve the problem by using a private key, so that it doesn't matter if a mark using that key is left behind.

**Comment by mnieper** [comment]
For your information: the issue I reported got my attention when I prepared a SRFI on continuation marks whose first draft was just put online: https://srfi.schemers.org/srfi-157/srfi-157.html. (Of course, I am always happy to receive comments helping to improve this SRFI. Without the pioneering work of Racket, it wouldn't have been possible.)

As for the issue itself, which I opened here, I'd suggest to change Racket's documentation so that `continuation-mark-set->list*` is mentioned (because a solution using only `continuation-mark-set->list` does not seem possible) so that this issue can be closed.

--

Marc

P.S.: I recently got interested in continuation marks while thinking of delayed evaluation in Scheme. R7RS has the primitives `delay`, `force`, and `delay-force`; there (rough) Racket equivalents are `delay`, `force`, and `lazy` (as in SRFI 45). By using `call-with-immediate-continuation-mark`, it is possible to get rid of `delay-force`/`lazy`. As Racket does have `call-with-immediate-continuation-mark` it would make sense to make `lazy` obsolete. The recipe is here: https://srfi-email.schemers.org/srfi-155/msg/6072673.

**Comment by mflatt** [comment]
@mnieper - Thanks!

In case you haven't already seen it, you may be interested in the implementation of continuation marks within https://github.com/racket/racket7/blob/master/racket/src/cs/core/control.ss
That implementation is not portable, because it relies on `eq?` comparisons of continuations. (The delimited-control part also uses a few `#%$...` internal primitives of Chez Scheme.) It may be useful in discussions of implementation strategies, though.
