### ISSUE TITLE
Recursive contract

### ISSUE THREAD

**Issue by zaoqi** [racket/racket#1787]
```racket
(define (not-promise? x) (not (promise? x)))
(define (promise+/c t)
  (or/c
   t
   (promise/c (recursive-contract (promise+/c t)))))
(define (spromise+/c t)
  (or/c
   (and/c not-promise? t)
   (promise/c (recursive-contract (promise+/c t)))))
(define/contract (promise+-fmap-flip x f)
  (let ([a (new-∀/c 'a)] [b (new-∀/c 'b)])
    (-> (spromise+/c a) (-> a b) (promise+/c b)))
  (if (promise? x)
      (delay (promise+-fmap-flip (force x) f))
      (f x)))
```
How to define `promise+-fmap-flip`?

**Comment by bennn** [comment]
What are you trying to do?

What's the error message you're seeing?

**Comment by zaoqi** [comment]
```
> (promise+-fmap-flip (delay 0) (λ (x) (+ x 1)))
. . promise+-fmap-flip: broke its own contract
  two of the clauses in the or/c might both match: b and (promise/c (recursive-contract (or/c b (promise/c (recursive-contract (promise+/c t))))))
  produced: #<promise:unsaved-editor:15:6>
  in: the range of
      (->
       (or/c
        (and/c not-promise? a)
        (promise/c
         (recursive-contract (promise+/c t))))
       (-> a b)
       (or/c
        b
        (promise/c
         (recursive-contract (promise+/c t)))))
  contract from: (function promise+-fmap-flip)
  blaming: (function promise+-fmap-flip)
   (assuming the contract is correct)
  at: unsaved-editor:11.18
```

**Comment by bennn** [comment]
Ok, so the problem is that:

```
two of the clauses in the or/c might both match: b and (promise/c ....)
```

This is because `b` can match anything, including a promise.

I think you want `b` to be parametric over anything but a promise. But `racket/contract` can't express bounded parametric polymorphism.

Here's two ideas:
1. use a weaker contract; instead of `(spromise+/c a)` use `(spromise+/c any/c)` and explain the function's behavior with a comment
2. try the contracts in this library: https://github.com/thinkmoore/bounded

**Comment by zaoqi** [comment]
@bennn `(spromise+/c any/c)`=`any/c`

**Comment by zaoqi** [comment]
@bennn `b` can is a promise.

**Comment by bennn** [comment]
Then maybe you don't want an `or/c` ?

**Comment by zaoqi** [comment]
?

**Comment by jackfirth** [comment]
You could wrap the contents of the promise in a single-field struct. That would let `or/c` tell the difference between a recursive promise and a non-recursive promise:

```
(struct done ([value #:mutable]) #:transparent)
(define (done/c t) (struct/c done t))
(define (done-map f d) (done (f (done-value d))))

(define (promise+/c t)
  (or/c
   (done/c t)
   (promise/c (recursive-contract (promise+/c t)))))

(define/contract (promise+-fmap-flip x f)
  (let ([a (new-∀/c 'a)] [b (new-∀/c 'b)])
    (-> (promise+/c a) (-> a b) (promise+/c b)))
  (if (promise? x)
      (delay (promise+-fmap-flip (force x) f))
      (done-map f x)))

;; evaluates to (done 1)
(force (promise+-fmap-flip (delay (done 0)) add1))
```

The struct is used as an immutable wrapper even though the `value` field is marked mutable. This is because [`struct/c`](http://docs.racket-lang.org/reference/data-structure-contracts.html?q=struct%2Fc#%28form._%28%28lib._racket%2Fcontract%2Fprivate%2Fstruct-dc..rkt%29._struct%2Fc%29%29) only allows [flat](http://docs.racket-lang.org/reference/contracts.html?q=struct%2Fc#%28tech._flat._contract%29) and [chaperone](http://docs.racket-lang.org/reference/contracts.html?q=struct%2Fc#%28tech._chaperone._contract%29) contracts on immutable fields, but [`new-∀/c`](http://docs.racket-lang.org/reference/parametric-contracts.html?q=new#%28def._%28%28lib._racket%2Fcontract%2Fparametric..rkt%29._new-~e2~88~80%2Fc%29%29) is an [impersonator](http://docs.racket-lang.org/reference/contracts.html?q=impersonator#%28tech._impersonator._contract%29) contract. Impersonator contracts can pretend to be arbitrarily different values when wrapping a value, which can violate the semantics of immutability.

**Comment by jackfirth** [comment]
Also, I think the [`lazy`](https://docs.racket-lang.org/reference/Delayed_Evaluation.html?q=lazy#%28form._%28%28lib._racket%2Fpromise..rkt%29._lazy%29%29) form does what you're trying to do. It allows you to return either a normal value or a promise, and the result promise automatically forces the inner promise (if present).

**Comment by zaoqi** [comment]
@jackfirth 
`promise+` is sized.
```racket
(define r (delay r))
```
The lazy form doesn't do what I'm trying to do.
https://github.com/jasonhemann/microKanren/blob/master/microKanren.scm

**Comment by Syntacticlosure** [comment]
You could write in this way:
```
(define (not-promise? x) (not (promise? x)))
(define (promise+/c t)
  (first-or/c
   (promise/c (recursive-contract (promise+/c t)))
   t
   ))
(define (spromise+/c t)
  (first-or/c
   (promise/c (recursive-contract (promise+/c t)))
   (and/c not-promise? t)
   ))
(define/contract (promise+-fmap-flip x f)
  (let ([a (new-∀/c 'a)] [b (new-∀/c 'b)])
    (-> (spromise+/c a) (-> a b) (promise+/c b)))
  (if (promise? x)
      (delay (promise+-fmap-flip (force x) f))
      (f x)))
(force (promise+-fmap-flip (delay 0) (λ (x) (+ x 1))))
```
I suggest you asking questions on StackOverflow, not here.
