### ISSUE TITLE
!

### ISSUE THREAD

**Issue by zaoqi** [racket/racket#1822]
```racket
#lang racket
(require (only-meta-in 1 racket/port))
(displayln (include/reader "prelude.scm" (λ (source-name in) (port->string in))))
```
```
port->string: unbound identifier in module (in phase 1, transformer environment) in: port->string
```

**Comment by AlexKnauth** [comment]
In the require, [`only-meta-in`][only-meta-in] and `for-meta` are very different. `only-meta-in` doesn't shift phases at all, it only filters. Since `racket/port` provides `port->string` at phase 0, `only-meta-in 1` filtered it out. You probably meant `for-meta 1`, which does shift the phase up by 1.

  [only-meta-in]: http://docs.racket-lang.org/reference/require.html#(form._((lib._racket%2Fprivate%2Fbase..rkt)._only-meta-in))
  [for-meta]: http://docs.racket-lang.org/reference/require.html#%28form._%28%28lib._racket%2Fprivate%2Fbase..rkt%29._for-meta%29%29
