### ISSUE TITLE
syntax/parse: failure messages produced by #:fail-when do not respect #:context

### ISSUE THREAD

**Issue by lexi-lambda** [racket/racket#1835]
The following program does not produce the error message I would expect:

```racket
#lang racket

(require syntax/parse)

(syntax-parse #'foo
  #:context #'(bar)
  [_
   #:fail-when #t "failure message"
   #f])
```

It produces the following message:

```
bar: failure message
  in: (foo)
```

However, I would expect it to produce the following message:

```
bar: failure message
  in: (bar)
```

Interestingly, the form raising the error is `bar` in both messages, but the current message does not use the context for the term. Additionally, the behavior is the same with `#:fail-unless`, but it is *not* the same with `#:when`. Furthermore, I get the same behavior if I use `(~fail "failure message")`, but *not* when I use `(~fail)` with no message! The custom message reporting logic seems to be at fault here.

Without looking at the code, my guess is that it has to do with the behavior of `#:fail-when` (and the `#:when` clause from `~fail`) that allows the condition expression to produce a syntax object, which will be used as a custom term in the error message. If the condition is non-`#f`, but isn’t a syntax object, the term should default to the context provided by the `#:context` option; currently it ignores the context.

**Comment by rmculpepper** [comment]
If you run your program at the repl, it produces the following error:

    readline-input:3.16: bar: failure message
      at: foo
      in: (bar)

That is, the context you supplied is used for the "in-term", but the syntax actually being destructured is used for the "at-term". That's the intended behavior: the at-term is supposed to identify the most specific term for which syntax-parse can articulate a problem. If there's no error message (because you used `#:when` or `(~fail)`), then syntax-parse decides it has nothing to say about the term that actually caused the error, and so it falls back to the context term. (If the failure were within a `~describe` pattern, it would fall back to that term and its description.)

DrRacket, when it displays syntax errors, throws away the in-term and relabels the at-term with "in: ". I'm not sure why, but my guess is to simplify errors that students get from the teaching languages. If that's the case, maybe that behavior should be narrowed to just the teaching languages?

Meanwhile, you can get the combination of the failure message and the context syntax like this:

    (syntax-parse #'foo
      #:context #'(bar)
      [_
       #:fail-when (current-syntax-context) "failure message"
       #f])

If the first argument to `#:fail-when` is a syntax object rather than a boolean, it is used as the at-term (unless there are multiple failures, in which case it gets more complicated).

**Comment by lexi-lambda** [comment]
Apparently I really need to stop trusting DrRacket when I’m trying to reproduce issues… this is not the first time I have been bitten by it doing different things. :(

Anyway, I think I see what you’re getting at, I just find it a little unintuitive. I’ll add the explicit reference to `(current-syntax-context)` for my failure pattern.

**Comment by rfindler** [comment]
@lexi-lambda DrRacket does do a whole bunch of stuff (in many different ways) and running by putting the code in a file and doing `racket x.rtk` is a good way to do a lot less stuff. That said, for most programs, you shouldn't be able to tell the difference, so I certainly appreciate you help ferret out the differences and fixing them!

**Comment by lexi-lambda** [comment]
Don’t get me wrong, I love DrRacket—it’s pretty amazing, and I think it’s one of my favorite parts of the Racket ecosystem—I just feel bad about reporting a couple of bugs without actually testing to check if they happen outside of DrRacket (and then having them pointed out to me that they don’t). I need to get in the habit of actually *checking* outside of DrRacket before opening issues.

**Comment by rfindler** [comment]
Thanks. And yeah, that's a habit I had to learn too. :)
