### ISSUE TITLE
Defined something while the head of the name contain with the symbol quote

### ISSUE THREAD

**Issue by ldcc** [racket/racket#1946]
I don't know what is it, just a bug or something?
just like this:
![image](https://user-images.githubusercontent.com/18207721/35864355-804b6516-0b8c-11e8-837b-cc994c24e969.png)

**Comment by ldcc** [comment]
And the same problem in r5rs

**Comment by abmclin** [comment]
It's not a bug.

What's happening is you redefined `quote` to be a function of one variable which returns 1.

You may not be aware, but the quote mark `'` is a shortcut for `quote` which is a special form. Each time Racket sees `'...` it replaces `'` with `(quote...)`

So when you do `(define '+ 1)` it is first converted to `(define (quote +) 1)` which evaluated as meaning you wanted create a new function called `quote` which has one formal argument called `+` and returns `1` The newly created function having the same name as the special form `quote` will override it (or as we usually say it, shadowed) in your Racket session.

You can see it more clearly by starting a fresh session, then typing in `quote`, you'll get an error message saying `bad syntax`

In a fresh Racket session, the following interactions will occur.

`quote` will throw `bad syntax` error since it cannot be used by itself
`(quote +)` will return `'+`
`(quote a)` will return `'a` as expected.

Then you type in `(define '+ 1)` which will hide the original `quote` with a new ordinary function also named `quote`

Then type in `quote` again, and instead of `bad syntax` error message you'll get back a procedure called quote.

The reason 'a results in a undefined identifier error after you  `quote` is because `quote` is now a procedure so you're trying to pass `a` to a procedure, `a` will be evaluated to find its value, but it's not a defined variable so it'll result in an undefined identifier error.

`a and `'a still works fine because the backtick ` is bound to the `quasiquote` special form which works similarly to `quote` special form, and you haven't accidentally redefined it to be something else.

**Comment by ldcc** [comment]
Well, i got it, i close it.
