### ISSUE TITLE
Unicode REPL Input Seems Broken

### ISSUE THREAD

**Issue by nixpulvis** [racket/racket#1956]
Within a `racket` REPL I am having trouble pasting or entering unicode values like `λ` or `∃`. Pasting a lowercase lambda yields the following result.

```
> Î»
```

Output of `uname -a`:

```
Linux pukak 4.14.15-1-ARCH #1 SMP PREEMPT Tue Jan 23 21:49:25 UTC 2018 x86_64 GNU/Linux
```

**Comment by mflatt** [comment]
The problem is most likely that `racket` is using `libedit` and `libedit` is not built with Unicode support. (I think `libedit` switch to Unicode-enabled by default only recently.)

Although `racket` uses `libedit` by default for license reasons, you can select `readline` by installing the `readline-gpl` package. That should make Unicode input work on a typical Linux installation.

**Comment by nixpulvis** [comment]
Thanks. running `raco pkg install readline-gpl` worked like a charm.
