### ISSUE TITLE
find-relative-path can't return #<path:.>

### ISSUE THREAD

**Issue by sorawee** [racket/racket#1980]
`find-relative-path` works incorrectly when `base` and `path` are the same.

```
> (require racket/path)
> (find-relative-path "/home/user" "/home/user")
"/home/user"
> (find-relative-path "/home/user" "/home/user/a")
#<path:a>
> (find-relative-path "/home/user" "/home/")
#<path:..>
```

I would expect to get `#<path:.>` as a result. Note that both `base` and `path` do share subpath in common.

(Also note that the documentation for `find-relative-path` (https://docs.racket-lang.org/reference/More_Path_Utilities.html#%28def._%28%28lib._racket%2Fpath..rkt%29._find-relative-path%29%29) is slightly confusing... 

> The case when path is returned and is a string is the only case when find-relative-path returns a string result.

is a tautology...)

**Comment by mflatt** [comment]
I worry about changing the behavior in a way that potentially breaks an existing program, so I'll add a `#:more-than-same?` argument that default to #f. The optional argument will provide a way to get the (almost certainly) better behavior.

I'll also adjust the docs so that the statement doesn't appear to be a tautology. That sentence is intended to say that the result is a path (as opposed to a string) unless `path` is given a a string and returned as the result.

**Comment by sorawee** [comment]
@mflatt you said that `#:more-than-same?` should default to `#f`, but in the above commit, it defaults to `#t`, for both documentation and implementation.

However, the behavior appears to be flipped, and the documentation contradicts what actually happens.

To elaborate further: the documentation states the following.

> If path is the same as base, then ([build-path](https://docs.racket-lang.org/reference/Manipulating_Paths.html#%28def._%28%28quote._~23~25kernel%29._build-path%29%29) 'same) is returned only if more-than-same? is true. Otherwise, path is returned when path is the same as base.

Consider:

```
> (find-relative-path "/a/b/c" "/a/b/c")
"/a/b/c"
> (find-relative-path "/a/b/c" "/a/b/c" #:more-than-same? #t)
"/a/b/c"
> (find-relative-path "/a/b/c" "/a/b/c" #:more-than-same? #f)
#<path:.>
```

Since path is the same as base and more-than-same? is true, `#<path:.>` should be returned for the first and second evaluation. But the opposite happens.

**Comment by mflatt** [comment]
I agree that documentation is backwards with respect to the implementation. My comment here was also backwards compared to the implementation. It's difficult to reason about this name `#:more-than-same?`, though, so I keep feeling like I might be getting things backward again.

Since the implementation has been in place so long, I'm inclined to fix the documentation by changing `true` to `#f`, and then live with the unclear keyword. Does that seem like an ok choice?

**Comment by sorawee** [comment]
I think that's reasonable.
