### ISSUE TITLE
Contracted values cannot be sent to places

### ISSUE THREAD

**Issue by pmatos** [racket/racket#2001]
As pointed out in the mailing list by myself and Daniel Feltey, contracted values cannot, it seems be passed to places. Daniel points out that:

> I think the issue here is that both contracted vectors and structs are wrapped in chaperones in order to enforce the contract, but that the place machinery doesn't know what to do with chaperoned values so it just prohibits them from being used as place messages.

The simplest example comes from Daniel:
```racket
#lang racket
(define v (vector 1 2))
(define/contract vc (vectorof integer?) (vector 1 2))
(place-message-allowed? v)
(place-message-allowed? vc)
```

the same happens if the contract boundary is a module. The other example can be found here: https://groups.google.com/d/msg/racket-users/vpoluvF4mPw/tyIno9-BBwAJ

**Comment by LiberalArtist** [comment]
To be more specific, this restriction is with chaperoned or impersonated values, not with contracted values per se.

A non-contract chaperone, even one that does nothing, has the same effect, so e.g. `(place-message-allowed? (chaperone-vector (vector 1 2) #f #f))` returns `#f`. In contrast, flat contracts do not interfere with sending values over place channels, so the following program evaluates to `#t`:
```racket
#lang racket
(define/contract v
  (vectorof integer? #:flat? #t)
  (vector 1 2))
(place-message-allowed? v)
```
(Of course, that contract is unsound on a mutable vector.)

I am not immediately sure what the right behavior should be. When the [docs](http://docs.racket-lang.org/reference/places.html) for places say that "to a first approximation, place channels support only immutable, transparent values as messages," it does seem like there is an argument to be made that chaperoned/impersonated values aren't "transparent", since the impersonator code can interpose in arbitrary ways (subject to the extra restrictions on chaperones, of course). On the other hand, contracts in particular are something we want to encourage, so making it harder to use contracted values with places seems like a downside worth considering. Also, most other parts of Racket try hard to prevent programmers from having to think about whether values have been chaperoned/impersonated or not. For example, `serialize` works on impersonated values, even though `(deserialize (serialize x))` effectively strips any impersonators from `x`.

It seems like the thorniest issues come with mutable values, which need non-flat contracts for soundness, even though sending them over a place-channel replaces them with immutable variants.

**Comment by mfelleisen** [comment]
> On Mar 21, 2018, at 4:38 AM, Philip McGrath <notifications@github.com> wrote:
> 
> To be more specific, this restriction is with chaperoned or impersonated values, not with contracted values per se.A non-contract chaperone, even one that does nothing, has the same effect, so e.g. (place-message-allowed? (chaperone-vector (vector 1 2) #f #f)) returns #f. 
> 

Let’s think about this. A contract (proxy) monitors a value for inappropriate operations in an unknown context. A local context is controllable in this way but it is not clear whether a remote context is controllable in this way. So the places mechanism takes a conservative approach to protect the integrity of monitored values — don’t send them. I consider this appropriate for a language designer who wishes to provide sound contracts.

**Comment by mfelleisen** [comment]
> On Mar 21, 2018, at 4:38 AM, Philip McGrath <notifications@github.com> wrote:
> 
> A non-contract chaperone, even one that does nothing, has the same effect, so e.g. (place-message-allowed? (chaperone-vector (vector 1 2) #f #f)) returns #f. In contrast, flat contracts do not interfere with sending values over place channels, so the following program evaluates to #t:
> 
> #lang racket
> (define/contract v
>   (vectorof integer? #:flat? #t)
>   (vector 1 2))
> (place-message-allowed? v)
> (Of course, that contract is unsound on a mutable vector.)
> 


@rfindler 

I don’t know when those unsound contract got stuck into the library but I am horrified that they ended up there. Why bother?

**Comment by rfindler** [comment]
This is a backwards compatible accommodation dating back to when we had vector contracts but no chaperones.

**Comment by mfelleisen** [comment]
Hah. I should have remembered. Stevie carefully explained this at some point.

**Comment by pmatos** [comment]
@mfelleisen However, if a library returns a vector, you don't necessarily know if it's under a contract. Contracts are supposed, I think, to be transparent. The user of the library therefore assumes that a vector can be sent through a channel until it notices it actually can't. This breaks the transparency. 

Assuming this cannot be changed, how can the user remove the contract/chaperone from the value before sending it into the channel?

**Comment by rfindler** [comment]
I agree with both points of view here, and don't think they are contradictory. That is, I think the conservative thing is to not allow them if we don't know how to do it, but that we wish we did know how to do it. As I understand it, there are arbitrary procedures associated with the chaperone, which is what keeps them from being sent.

Probably one could design a more complex api that would allow the contract library to tell places how to communicate values across and then some contracts could be supported.

**Comment by mflatt** [comment]
I think copying the vector to one without a chaperone/impersonator is the consistent thing to do for places – similar to mutable-vector handling and `serialize`. (A protocol that communicates contracts across place channels would be neat, but that's well beyond the kind of thing that place channels do now.)

The only reason the conversion doesn't happen automatically right now is that place communication is at a low enough layer that chaperones and impersonators must be handled explicitly. Doing that isn't trivial, but it shouldn't be too difficult.

**Comment by rfindler** [comment]
I am good with that approach. I assume the copying would run the chaperone callbacks and then produce an immutable vector (so there won't be a soundness hole).

**Comment by mflatt** [comment]
Right – like `vector-copy`, the callback would get triggered for each element of the vector.

**Comment by pmatos** [comment]
In the meantime, is there a way to clean up the chaperones manually before I send the vector in through the channel? Alternatively I will temporarily remove the contracts.

I was thinking of something along the lines:
```racket
(define (cleanup-for-channel v)
  (if (with-chaperone? v)
      (remove-chaperone v)
      v))
```

**Comment by mflatt** [comment]
You could use` vector-copy`.

**Comment by pmatos** [comment]
@mflatt Makes sense... although then I will need a more complicated `cleanup-for-channel`. Good enough for now though. Thanks
