### ISSUE TITLE
“Wrong number of values” errors at phase 1 in modules are weird in Racket 7

### ISSUE THREAD

**Issue by lexi-lambda** [racket/racket#2029]
See below:

```
$ racket
Welcome to Racket v6.90.0.24.
> (module m racket
    (define-values [x] (values)))
> (require 'm)
; define-values: result arity mismatch;
;  expected number of values not received
;   expected: 1
;   received: 0
;   from:
;   in: definition of x
;   values...:
; [,bt for context]
> (module m racket
    (begin-for-syntax
      (define-values [x] (values))))
; wrong number of results ( 0 "vs." 1 ")" "from" #(struct:parsed-app #f ...)
;   [,bt for context]
> (module m racket
    (define-syntaxes [x] (values)))
; wrong number of results ( 0 "vs." 1 ")" "from" #(struct:parsed-app #f ...)
;   [,bt for context]
```

This appears to only happen in modules; the errors are the usual ones at the top level.

**Comment by AlexKnauth** [comment]
The error message appears to be coming from `eval-for-bindings` here:
https://github.com/racket/racket/blob/5ed0cdf563aa8585e99142aa51d44762c8562673/racket/src/expander/expand/main.rkt#L659-L661
```racket
  (unless (= (length vals) (length ids))
    (error "wrong number of results (" (length vals) "vs." (length ids) ")" 
           "from" p))
```

It's printing strings like the `"vs."` and the `")"` with the quotes because `(error msg v ...)` with no symbol before the `msg` isn't meant to mix extra `msg` strings in between the `v`s.

I don't know whether there's some other mechanism for catching this error the exact same way it would be caught in a normal phase 0 `define-values`. But if there isn't, this could be made to look a little better if it used
```
(error 'expand "wrong number of results (~a vs. ~a) from ~v" (length vals) (length ids) p)
```
or some variant of that.
