### ISSUE TITLE
Where is drracket installed?

### ISSUE THREAD

**Issue by Vm900** [racket/racket#2083]
Hi,
I just compiled racket minimal (in-place) and installed drracket via raco.Now where in the
directory structure is drracket installed?I can't seem to find it.
I am on linux by the way.
All i have is this
![racketbuild](https://user-images.githubusercontent.com/9399631/40200779-12e24404-5a15-11e8-9685-11b2f12adb63.png)

Thanks

**Comment by jbclements** [comment]
After re-reading your message and deleting my original response (oops…), it sounds to me like you already know where binaries such as `racket` and `raco` are. The `drracket` binary should be in the same place. I suspect that you’re saying that it’s not there, and I suspect that in order to re-build launchers you need to run

raco setup

… with no arguments, to allow setup to run quickly over all installed directories and produce executables.

Let me know if I misunderstood your question!

John Clements

**Comment by Vm900** [comment]
@jbclements Hi,thanks a million.raco setup did it.And it places the launchers in .racket folder

**Comment by Vm900** [comment]
@jbclements  I just need to know one more thing though.I'm failing to open help-desk.If possible i would like to use firefox as my default browser.
![helpdeskbrowsererror](https://user-images.githubusercontent.com/9399631/40207871-96902cb2-5a2e-11e8-84dd-732e865251e0.png)

Thanks

**Comment by mflatt** [comment]
Follow up to the original question: if you install packages with `raco pkg install -i`, then executables go in the installation directory (instead of "~/.racket"), which may have been what you wanted.

To configure the way that DrRacket opens a web browser, there's a "Browser" tab in the preferences dialog (open via "Preferences" in the "Edit" menu) to let you configure that.

**Comment by Vm900** [comment]
@mflatt Thanks.It's sorted
