### ISSUE TITLE
Importing exports that are gensyms doesn't seem to work

### ISSUE THREAD

**Issue by endobson** [racket/racket#2133]
The following program fails, but if the other definition of sym is uncommented then it works.

```racket
#lang racket/base

(define-namespace-anchor anchor)


(define sym (gensym 'the-gensym))
;(define sym 'not-gensym)
(define mod-a
  `(module a racket/base
     (provide (all-defined-out))
     (define ,sym 4)))

(define ns (namespace-anchor->empty-namespace anchor))
(parameterize ([current-namespace ns])
  (namespace-require 'racket/base))

(eval
  `(begin
     ,mod-a
     (let-values ([(vars syntax) (module->exports ''a)])
       (displayln vars)
       (displayln (caadar vars))
       (displayln (equal? (caadar vars) ',sym))
       (displayln syntax))
     (require (only-in 'a ,sym))
     )
  ns)
```

Broken version:
```
% racket expand-test.rkt                                                                                                                                                                                      (1)
((0 (the-gensym26 ())))
the-gensym26
#t
()
require: not in nested spec
  at: the-gensym26
  in: (quote a)
  context...:
   raise-syntax-error
   for-loop
   perform-require!78
   for-loop
   [repeats 2 more times]
   expand-capturing-lifts
   expand-single
   temp74_0
   compile16
   temp68_2
   "/Users/endobson/tmp/expand-test.rkt": [running body]
   for-loop
   run-module-instance!125
   perform-require!78
```

Working version:
```
% racket expand-test.rkt                                                                                                                                                                                      (1)
((0 (not-gensym ())))
not-gensym
#t
()
```

This is running with 6148adf45287fc287b3f508f5ccb82c20fcf55da (latest commit of release branch).

**Comment by endobson** [comment]
It looks like this failed in 6.12 as well.

```
~/proj/racket/plt-6.12/racket/bin/racket expand-test.rkt                                                                                                                                                    (0)
((0 (the-gensym7 ())))
the-gensym7
#t
()
/Users/endobson/proj/racket/plt-6.12/racket/collects/racket/private/reqprov.rkt:382:18: #%require: no such provided variable
  at: the-gensym7
  in: (#%require (just-meta 0 (rename (quote a) the-gensym7 the-gensym7)) (only (quote a)))
  context...:
   /Users/endobson/tmp/expand-test.rkt: [running body]
```

**Comment by mflatt** [comment]
The module system discards an identifier at `require` when the identifier's symbol is not interned, and it has done that for a very long time (possibly always). If I remember correctly, the intent was to filter out unreadable symbols (as opposed to completely uninterned symbols) to avoid unpredictable collisions.

At a minimum, the documentation should be updated.

**Comment by rocketnia** [comment]
Over the past couple of days I've been updating a library I made for convenient namespace manipulation and run time module generation. It used a module gensym-named exports in order to ensure a generated module's namespace didn't have bindings like `#%module-begin` that could collide with symbols the user supplies to the library. I'm not really sure anyone needs this library, even me, but I've kept it maintained for a while anyway ([since 2011](https://github.com/arclanguage/anarki/commits/master/lib/ns.arc)), and I've been able to keep it working until Racket 7.0.

In my case, I'm not using an explicit `require` to get the identifiers; I'm getting them from the module's language. Here's a simple example that reproduces the kind of error I'm seeing:

```
#lang racket/base

(let ([g-module-begin (gensym '#%module-begin)])
  (eval
    #`(module a racket/base
        (provide (rename-out [#%module-begin #,g-module-begin]))))
  (eval
    #`(module b 'a
        (#,g-module-begin))))
```

In Racket 6.11 and 6.12, this file executes and does nothing. (It looks like it just defines modules `'a` and `'b` successfully.) On Racket 7.0, it fails with the following error:

```
#%module-begin34: unbound identifier
  in: #%module-begin34
  context...:
   raise-unbound-syntax-error
   for-loop
   finish-bodys
   lambda-clause-expander
   for-loop
   loop
   [repeats 1 more time]
   module-begin-k
   expand-module16
   expand-capturing-lifts
   expand-single
   temp74_0
   compile16
   temp68_2
   "/home/nia/mine/drive/repo/mine/prog/repo/not-mine/anarki/lib/ns2.rkt": [running body]
   for-loop
   ...
```

As endobson did, I poked around with `module->exports` to verify that the export list still contained the gensym, even though I couldn't use it for some reason.

Given what @mflatt just said, perhaps this error is something I should expect, and the behavior from 6.12 and earlier wasn't supposed to be stable. If that's the case, does there happen to be another way at run time to generate a module like `'b` whose `module->namespace` doesn't contain any non-gensym bindings?

If there isn't, I can just accept that and redesign my library's interface to avoid relying on this; perhaps I'll just document that the generated modules do contain a few identifiers that the library's users shouldn't try to overwrite. Still, I hope my use case and my experiences have added some more context to this issue.

**Comment by rocketnia** [comment]
I thought some more about my library's design, and I determined I didn't actually want to use `module->namespace`; I wanted to create a fresh namespace and populating it with `namespace-require`.

At that point I no longer needed the generated modules to use gensyms in their internal namespaces, so I switched to using interned symbols. The library is doing all right on Racket 7.0 now. :)
