### ISSUE TITLE
Inconsistent checking order of unbound identifiers in expander

### ISSUE THREAD

**Issue by leafac** [racket/racket#2167]
```racket
#lang racket
;; Version 7.0.0.6--2018-07-07(4d158a8cb8/a) [3m]

#;
(define (f a)
  (g (h)))
;; ⇒ g: unbound identifier in: g

#;
(define-syntax (f a)
  (g (h)))
;; ⇒ h: reference to an unbound identifier
;;   at phase: 1; the transformer environment in: h
```

I expected the `define-syntax` version to complain about `g`, like the `define` version does.

**Comment by bennn** [comment]
It will complain about `g` if the expander finds it first --- e.g. if the body is `(g 1)` instead. Do you want expansion order* to be the same as evaluation order?

`*` I think expansion order is currently unspecified

**Comment by leafac** [comment]
I expect DrRacket to complain about unbound identifiers in compile-time functions the same way it complains about unbound identifiers in runtime functions.

This is relevant, for example, when a programmer writes a macro and forgets to require the necessary modules:

```racket
#lang racket

(define-syntax (m stx)
  (syntax-parse stx
    [(_) #'hi]))
```

I wanted this to complain about `syntax-parse`, which would remind me to `(require (for-syntax syntax/parse))`. This is what happens with runtime functions—DrRacket complains about unbound identifiers “from the outside in.”

But, because this is a compile-time function, DrRacket complains about unbound identifiers “from the inside out,” which results in the following error message about `_`:

```
_: wildcard not allowed as an expression in: (_)
```

A lot less helpful to figure out the missing `require`.

**Comment by lexi-lambda** [comment]
I believe that the two cases you mention are not necessarily the same. I am not completely sure why your first example behaves the way it does, but to understand your second example (the one with the missing import for `syntax-parse`), a [comment](https://github.com/racket/racket/issues/2150#issuecomment-400886419) from @mflatt on a recent issue of mine hints at the problem:

> I have never found a workable alternative to this compromise. To put it all another way, **phase > 0 within a module is distressingly like the top level**, because it has to make certain decisions before seeing the whole module.

Emphasis mine. At phase > 0, compilation and expansion must be interleaved in a similar way to top-level evaluation, since compilation of a subsequent form might use a previous syntax-time definition. This means that phase > 0 code defers errors about unbound identifiers until later, since they might be defined later in the module. However, it does have to assume that unbound identifiers will be defined *as non-syntax bindings*, since otherwise, they would dramatically affect compilation of the form itself, as the expander wouldn’t be able to make any forward progress at all.

By assuming that unbound identifiers, such as `syntax-parse` in your program, are non-syntax bindings, they expander can continue expansion under the assumption that it is looking at a function application form. Therefore, it continues recursively expanding subforms in expression position until it finds `_`. The problem is that `_` *is* a syntax binding, and it always raises an error when expanded—it’s only recognized specially by other forms—so expansion halts. This means that deferring the error from the unbound `syntax-parse` identifier has, sadly, led to a significantly worse error message. Unfortunately, it would be an equally legal program for `syntax-parse` to genuinely refer to a phase 1 function defined later in the module that the expander just hasn’t found yet.

I don’t know how to resolve that problem. It’s significantly trickier than it first appears.

**Comment by leafac** [comment]
@lexi-lambda: Can you clarify how my first (`(g (h))`) and second (`syntax-parse`) examples differ? I intended them to mean the same, the first as a minimal working example of the motivating issue, which is the second.

**Comment by lexi-lambda** [comment]
@leafac Let me add a clarifying comment, which, combined with my previous comment, should hopefully make it clear why your two programs are different. In your first example, `g` and `h` are both unbound identifiers. In your second example, `syntax-parse` is unbound, but `_` is bound to a syntax binding that always raises a syntax error when expanded. Those are quite different scenarios!

**Comment by mflatt** [comment]
I agree that we know no good way to complain about `syntax-parse` instead of `_`.

The problem in the original example was a missing `reverse`, as we suspected.

**Comment by mflatt** [comment]
On further thought, here's a possibility for improving the `syntax-parse` example's error.

At the point where a syntax error is reported, the module expander knows that it saw `syntax-parse` without a binding. Maybe `raise-syntax-error` should add to the error message by listing any identifiers that it encountered without a binding and by suggesting that those identifiers may be relevant. (This would apply only to phase level >= 1, since that's where unbound-identifier errors can be deferred.)

**Comment by samth** [comment]
Maybe `raise-syntax-error` could indicate when prior unbound identifiers should be mentioned and/or should be reported instead of this error?

**Comment by abmclin** [comment]
I understand this is a difficult problem in general. I was thrown by the same error earlier in the week and wished for more reported information so I think your changes would be very much welcomed.

If there is concern about reporting too much information, is it possible to have an adjustable verbosity level parameter for `raise-syntax-error`?

**Comment by mflatt** [comment]
I don't think the author of `_` would have specifically considered the case that an earlier unbound identifier might be the problem, and it may be that practically any syntax error might be the result of treating a pattern as an expression. So that's why I suggest that `raise-syntax-error` just always add to the error message if has pending unbound identifiers.

Note that the change wouldn't affect most error messages, since it wouldn't affect messages at phase 0.

**Comment by lexi-lambda** [comment]
I think the change @mflatt suggests sounds like a significant improvement.

**Comment by leafac** [comment]
Thank you 😃
