### ISSUE TITLE
error when requiring readline on windows 10

### ISSUE THREAD

**Issue by vityou** [racket/racket#2171]
I get the error:
```
; ffi-lib: couldn't open "libreadline-5.dll" (The specified module could not be
;   found.; errid=126) [,bt for context]
```

**Comment by LeifAndersen** [comment]
Right now Racket doesn't really support readline. This is because we don't provide the actual readline library, and it expects it to be already installed, which is true for macos and many forms of linux, but not windows.

A possible solution would be to compile and install a readline compatible library for windows on your machine. Perhaps something like this: https://github.com/winlibs/wineditline
