### ISSUE TITLE
what is racket natipkg build? please clarify

### ISSUE THREAD

**Issue by milahu** [racket/racket#2422]
i have read [About Package Builds#Working with Native Libraries](https://pkg-build.racket-lang.org/about.html#foreign) but i still dont get it ...

what is the difference between the two 'platforms' ... ?

- x86_64-linux-natipkg
- x86_64-linux

it seems to be about package management, dependency resolution and fallback behavior.

in other words: will the natipkg build run faster? [assuming i need native libs]

or: will the non-natipkg build link to slower [but cross-platform] libraries?

can you give more examples for 'native libraries'? GTK? QT?

please clarify.

> Working with Native Libraries
> 
> The “minimal” versus “extended” VM distinction begs the question of how the package-build service can support a package that relies on a native library—one that is not installed even on the extended VM.
> 
> It would be nice to have a bridge between the Racket package system and the OS package manager so that dependencies on OS packages could be declared and installed. [...]
> 
> For now, the package-build installation identifies itself as running on the "x86_64-linux-natipkg" platform, as opposed to plain "x86_64-linux". **On the plain "x86_64-linux" platform, native libraries as needed by Racket packages are expected to be installed by a user through the OS’s package manager.** **On the "x86_64-linux-natipkg" platform, however, native libraries** are handled as on Windows and Mac OS: they **are expected to be provided by platform-specific packages.**
> 
> For example, on the "x86_64-linux-natipkg" platform, the "math-lib" package depends on the "math-x86_64-linux-natipkg" package, which provides 64-bit Linux builds of GMP and MPFR. [...]
> 
> **If your package depends on a native library**, then you currently have two main options:
> 
> Accomodate Unavailable Libraries
> 
> One option is to make the package behave when the native library is unavailable.
> 
> [...]
> 
> Distribute Native Libraries
> 
> Another option is to build a 64-bit Linux version of the library, distribute it as a package, and make the package a platform-specific dependency of your package for the "x86_64-linux-natipkg" platform.
> 
> **This option is in many ways the best one** for users and for testing—especially if Windows and Mac OS native-library packages are also provided—**but it’s more work.**
>

**Comment by mflatt** [comment]
The natipkg build is unlikely to be faster. It's likely to be slower, since native libraries that are distributed in a Racket package won't be shared with other running applications, and their compilation might be less tuned to your installation that ones installed and managed by the operating system.

As you say, it's just about packaging and management. The only reason to use natipkg is when working in a constrained environment where access to the OS's package manager is not available (perhaps for permission reasons).

Gtk and Qt are good examples of native libraries. Most any library that is normally installed with the OS's package manager would be in that category.
