### ISSUE TITLE
how to implement chez scheme's unread-char on racket?

### ISSUE THREAD

**Issue by zhu-fei** [racket/racket#2437]
hi: 
  I want to use unread-char in racket, but I do not know how to implement ?  Anyone can help me?
Thank you!

**Comment by lexi-lambda** [comment]
I think you could implement `unread-char` using [`input-port-append`](http://docs.racket-lang.org/reference/port-lib.html#%28def._%28%28lib._racket%2Fport..rkt%29._input-port-append%29%29), like this:

```racket
(define (unread-char c in)
  (input-port-append #t (open-input-string (string c)) in))
```

**Comment by lexi-lambda** [comment]
…on second thought, the above is not the same, since `unread-char` mutates the underlying port, but `input-port-append` returns a new port. I don’t know if there’s a way to do what `unread-char` does directly in Racket, without wrapping the port entirely (which seems possible but maybe a little complicated), but `peeking-input-port` allows arbitrary lookahead, which I think subsumes the main use case `unread-char` is intended for.

**Comment by zhu-fei** [comment]
I going to close this issue , because I think there isn't any  directly way to achieve such thing, I going to use other solution! thanks anyway!
