### ISSUE TITLE
Namespace mismatch error from `syntax-local-lift-require` + `make-syntax-delta-introducer`

### ISSUE THREAD

**Issue by lexi-lambda** [racket/racket#2542]
This sort of thing doesn’t seem to regularly happen anymore post-Racket 7, so I was surprised to find a program that raises a compile-time error in DrRacket but not on the command line. Here’s the program:

```racket
;; introduce.rkt
#lang racket/base

(module foo racket/base
  (provide foo)
  (define foo 42))

(module introducer racket/base
  (require (for-syntax racket/base
                       racket/syntax)
           syntax/parse/define)

  (provide begin-foo)

  (begin-for-syntax
    (define scopeless-stx (datum->syntax #f #f)))

  (define-syntax-parser define-cached-require-introducer
    [(_ x:id mod-path)
     #:with scoped-stx (syntax-local-lift-require (syntax->datum #'mod-path) scopeless-stx)
     #'(begin-for-syntax
         (define x (make-syntax-delta-introducer (quote-syntax scoped-stx) scopeless-stx)))])

  (define-cached-require-introducer introduce-foo (submod ".." foo))

  (define-syntax-parser begin-foo
    [(_ form ...)
     (introduce-foo
      #'(begin form ...))]))

(require 'introducer)
(begin-foo foo)
```

When run from the command-line, the program compiles, runs, and prints out `42`. When run from inside DrRacket, it produces the following error:

```
expand: namespace mismatch; cannot locate module instance
  module: #<module-path-index:(submod ".." foo) + (submod '|expanded module| introducer)>
  use phase: 0
  definition phase: 0
  for identifier: #<syntax:introduce.rkt:31:11 foo>
```

If I add another file to the equation, then command-line Racket also begins to barf:

```racket
;; use.rkt
#lang racket/base

(require (submod "introduce.rkt" introducer))

(begin-foo foo)
```
```
$ racket use.rkt
expand: namespace mismatch; cannot locate module instance
  module: #<module-path-index:(submod ".." foo) + (submod 'introduce[3388] introducer)>
  use phase: 0
  definition phase: 0
  for identifier: #<syntax:use.rkt:5:11 foo>
  context...:
   binding->module-instance
   binding-lookup52
   expand-identifier
   do-local-expand50
   /Users/alexis/gits/racket/racket/racket/collects/syntax/wrap-modbeg.rkt:46:4: do-wrapping-module-begin
   apply-transformer-in-context
   apply-transformer52
   dispatch-transformer41
   loop
   finish
   [repeats 1 more time]
   pass-1-and-2-loop
   module-begin-k
   expand-module16
   expand-capturing-lifts
   temp118_0
   ...
```

I don’t know if the fact that the error happens at all or not is a bug, or if this program is just broken, but the fact that Racket and DrRacket disagree about when the bug is triggered definitely seems like a bug to me.

**Comment by greghendershott** [comment]
FWIW racket-mode's `racket-run` produces exactly the same error as does DrRacket. As a result, I'd guess the issue is related to using `module->namespace`.

**Comment by greghendershott** [comment]
Using command-line Racket, but with `,enter`, also produces an error (but different message):

```
$ racket introduce.rkt 
42
$ racket
Welcome to Racket v7.2.
> ,enter introduce.rkt 
no module instance found: #<resolved-module-path:(submod 'introduce[10722] foo)> 0
"introduce.rkt"> 
```

**Comment by mflatt** [comment]
I think the problem is that `syntax-make-delta-introducer` transfers scopes, but it does not transfer module path index (MPI) shifts. Without shifts, the binding's original MPI is reported, which is the gensymed name. Applying the shift takes that to the instantiation-time MPI and find the right module.

Changing `(add-scopes s delta-scs)` to `(syntax-transfer-shifts (add-scopes s delta-scs) ext-s)` in the implementation of `syntax-make-delta-introducer` makes the error go away, at least for this example. I'll have to think more about whether that kind of change is on the right track.

The difference between DrRacket and Racket is re-expansion for errortrace. Racket behaves like DrRacket if you use `racket -l errortrace -t "introduce.rkt"`.

**Comment by lexi-lambda** [comment]
Thank you! I spent some time last night after reading your comment trying to understand MPIs better and the role of MPI shifting, but while I sort of muddled through some of it, I don’t think I really understood the whole picture. What necessitates it in the first place? Which is to say: what prevents bindings’ modules from being absolute references instead of relative ones that need this kind of adjusting?

**Comment by mflatt** [comment]
I've been thinking about this, too.

The problem that MPIs solve is a combination of

 * referring to a module through a without installing it as a package/collection;

 * compiling package/collections without tying them to specific filesystem paths (since the installation target is unlikely to be the same filesystem – maybe not even with the same path conventions); and

 * layering file/collection handling on a REPL view of module expansion/compilation, where there is no filesystem path or module path, and modules are ideally anonymous and given names externally (like `lambda`).

It might have been better to pick a different combination problems, though, which is what most other languages have done.

**Comment by lexi-lambda** [comment]
That makes sense. My one remaining big-picture question is this: when do the shifts actually get attached in the first place? That is, how does `ext-s` in this particular example end up with the shifts necessary to locate the correct binding? Are these shifts added on module visit time? When code is loaded from bytecode? I think I’m missing some piece of the puzzle.

**Comment by mflatt** [comment]
The shift is added at module instantiation time (which includes visiting). A phase shift, if any, is applied at the same time.

One way to see how how things are put together at the linklet level is to load something like
```
#lang racket/kernel
(quote-syntax hi)
```
in Racket CS with the `PLT_LINKLET_SHOW` enviornment variable set. The last linklet shown is the facet of the module that holds the syntax objects specific to a module instance, all combined into a vector. The linklet has a `syntax-module-path-index-shift` import that is the shifting operation on a  vector of syntax objects, and it has a `.self` import that is the MPI created for that instance (i.e., the "destination" of the shift). The "source" for the shift is extracted from the `.mpi-vector` import, which comes from another linklet that centralizes all of the MPIs in the module's compiled form. The actual shifting operation happens when one of the syntax objects is demanded.

You can see the same information with `raco decompile --linklet` on non-CS bytecode, but it's somewhat further obfuscated.
