### ISSUE TITLE
typed/racket: can't cast Any to function type

### ISSUE THREAD

**Issue by MichaelMMacLeod** [racket/racket#2557]
### What version of Racket are you using?
Racket v7.2

### What platform are you using?
Linux x86-64 

### What program did you run?
```racket
#lang typed/racket

(define x : Any
 (lambda ([n : Integer]) (add1 n)))

((cast x (-> Integer Integer)) 42)
```
(The original program I had was more complex; @lexi-lambda broke it down to this simplified version here https://racket.slack.com/archives/C06V96CKX/p1553449058179800).
### What should have happened?
The `cast` should successfully coerce the `Any` into `(-> Integer Integer)`, and the program should not throw an error.
### If you got an error message, please include it here.
```racket
contract violation
  Attempted to use a higher-order value passed as `Any` in untyped code: #<procedure:x>
  in: Any
  contract from: typed-world
  blaming: cast
   (assuming the contract is correct)
  at: unsaved-editor:6.1
```
### Extra details
This problem originally arose when I tried to `cast` a dynamically required function. See https://stackoverflow.com/questions/55321755/applying-cast-to-dynamically-required-function-in-typed-racket for more information. Since `dynamic-require` returns a value of type `Any`, there doesn't seem to be any clever ways to get around `cast`ing it, like there are with the example above.

See @AlexKnauth suggestions regarding a possible `DynamicAny` type here https://groups.google.com/forum/#!msg/racket-users/cCQ6dRNybDg/faPYhKNZBwAJ and, more recently, on the Racket Slack channel here https://racket.slack.com/archives/C06V96CKX/p1553450324186000.

**Comment by AlexKnauth** [comment]
This is supposed to fail, because values of type `Any` need to have restrictions on how they are used for type safety. Once a value is of type `Any`, it should not be called as a function and also should not be mutated. This is so that programs like this raise the correct error:

```racket
#lang typed/racket

(define x : Any
   (lambda ([n : (Boxof Any)]) (unbox n)))

((cast x  (-> String Any)) "I am not a box")
```
Without this restriction, programs like this could have arbitrary unsound memory accesses. If I remove this contract check on the program above, it prints out `#<macro>`. If I change the string to a byte string I get `#<bad-value>`, and if I change it to a symbol, I get a segfault. Some restrictions on `Any` are necessary for soundness and memory safety.

Also, note that the program in this issue would not benefit from `DynamicAny`. The `DynamicAny` type can only be assigned to either values that are known to come from untyped code, or flat-first-order-immutable values from typed code.

**Comment by MichaelMMacLeod** [comment]
Thanks for the clarification; it makes sense to me now why throwing an error in this case is the intended behavior.

Am I correct in assuming that the issue is then with how the result of a `dynamic-require` cannot be `cast`ed to a function type, like in the stackoverflow post? If so, I may close this issue and open another one with that problem instead.

**Comment by AlexKnauth** [comment]
Yes.
