### ISSUE TITLE
Rackunit test-case allows stray function name after test-case descriptor w/o error

### ISSUE THREAD

**Issue by cmdoffing** [racket/racket#2573]
I accidentally coded:
(test-suite "Section Lines"  stray-function-name
     (test-case ....

and got no error when I ran the tests.

**Comment by LiberalArtist** [comment]
This happens for the same reason that 
```racket
(let ()
  + 1 2)
```
evaluates to `2` with no error.

Functions are first-class values, so `stray-function-name` is a perfectly valid expression that evaluates to a function (i.e. a value that would satisfy `procedure?`). Meanwhile, forms with `begin`-like sequence-of-expression bodies (including `test-suite`)—say `(begin e_0 ... e_n e_n+1)` evaluate the expressions `e_0 ... e_n`, in order, for their side-effects only, and the value of the `begin`-like expression is the value of `e_n+1`.

Since evaluating the expression `stray-function-name` has no side effects (in particular, it does not raise an exception), you get the occasionally-unfortunate result you encountered here.

**Comment by cmdoffing** [comment]
Phillip, thanks for the extended -- and very clear -- explanation. That wraps it up for me.

**Comment by sorawee** [comment]
Closing, as it works as expected.
