### ISSUE TITLE
Feature request: allow signatures to import signatures

### ISSUE THREAD

**Issue by lexi-lambda** [racket/racket#2604]
I would like signatures to be able to import other signatures. What does that mean? Well, I’d like to be able to write this:

```racket
#lang racket

(define-signature cell^
  [(contracted
    [cell? (-> any/c boolean?)]
    [make-cell (-> any/c cell?)]
    [cell-ref (-> cell? any/c)]
    [cell-set! (-> cell? any/c void?)])])

(define-unit box@ (export cell^) ....)
(define-unit thread-cell@ (export cell^) ....)

(define-signature cell-swapper^
  [(import cell^)
   (contracted
    [cell-swap! (-> cell? cell? void?)])])

(define-unit simple-cell-swapper@
  (import cell^)
  (export cell-swapper^)
  (define (cell-swap! a b)
    (define tmp (cell-ref a))
    (cell-set! a (cell-ref b))
    (cell-set! b tmp)))
```

Specifically, look at the `cell-swapper^` signature. It defines a contract on `cell-swap!` that uses `cell?`, which is exported by `cell^`, so it needs to have access to the bindings. But it can’t use `(open cell^)`, since that means `simple-cell-swapper@` will need to export `cell^`, but it can’t, since it needs to *import* `cell^`.

Put another way, `extends` and `open` essentially allow a signature to require that implementing units `export` a particular signature, but there is no equivalent feature for `import`s, despite it sometimes being necessary in order to write the appropriate contracts.

**Comment by LiberalArtist** [comment]
I have also wanted this feature, and I think (from my limited experience with units) that the issue is not uncommon. [The Racket Guide](https://docs.racket-lang.org/guide/Signatures_and_Units.html)'s running example uses interrelated `toy-factory^` and `toy-store^` signatures. It shows how to define a version of `toy-factory^` [with contracts](https://docs.racket-lang.org/guide/Contracts_for_Units.html#%28part._.Adding_.Contracts_to_.Signatures%29), but I believe it is impossible to do likewise for `toy-store^` without this feature. At least, I asked about it on the [mailing list](https://groups.google.com/d/topic/racket-users/dD3xjPLQI8Y/discussion), and I haven't heard or seen any other solution.

**Comment by lexi-lambda** [comment]
Closing this issue in favor of #4550, which is about the same thing but has a much more substantial discussion.
