### ISSUE TITLE
`call-with-custodian-shutdown` fails to shutdown the custodian if the parent thread is killed

### ISSUE THREAD

**Issue by lexi-lambda** [racket/racket#2615]
This program produces `#t`, but I think it should produce `#f`:

```racket
#lang racket

(require racket/sandbox)

(define sema (make-semaphore))
(define cust-box #f)

(define t
  (thread
   (λ ()
     (call-with-custodian-shutdown
      (λ ()
        (set! cust-box (make-custodian-box (current-custodian) #t))
        (semaphore-post sema)
        (sync never-evt))))))

(semaphore-wait sema)
(kill-thread t)
(custodian-box-value cust-box) ; => #t
```

The issue is that `call-with-custodian-shutdown` doesn’t make sure that the custodian it creates is shutdown if the parent thread is killed, but its custodian is not shutdown. I think this is fixable, since the semantics of `call-with-nested-thread` makes it possible to observe if the parent thread is killed by catching a break delivered to the child.

**Comment by mflatt** [comment]
I doubt that it makes sense to try to detect termination of the thread that calls `call-with-custodian-shutdown`. Concretely, break signals are asynchronous, so knowing that the thread is terminated would not tell you anything about whether the custodian has been shut down, yet. Generally, about the only thing an API can say about thread termination is whether the API is kill-safe; otherwise, custodians are the way to get more guarantees (i.e., if the custodian of the thread that calls `call-with-custodian-shutdown` is shutdown, then the nested custodian is reliably shut down).

**Comment by lexi-lambda** [comment]
I think maybe I didn’t include some context: I realized this “issue” when looking at the implementation of `call-with-custodian-shutdown`, since I was curious if it did anything more than `dynamic-wind` + `custodian-shutdown-all`, and I was surprised to find a use of `call-with-nested-thread` in there. I assumed that the use of `call-with-nested-thread` was there to protect against something, but after your comment, I’m no longer sure what (since if it isn’t protecting against the thread being killed, then I don’t know what it *is* protecting against).

So maybe this isn’t a bug, but in that case, it’s a question: why does `call-with-custodian-shutdown` use `call-with-nested-thread` at all?

**Comment by mflatt** [comment]
I think it's just a convenient way to wait and propagate breaks to/from the nested thread.

**Comment by lexi-lambda** [comment]
I am not sure I understand your answer… my question was why a nested thread is involved at all, not why it uses the `call-with-nested-thread*` function inside `racket/sandbox`, specifically. But it doesn’t really matter—I get the impression that whatever it’s doing isn’t relevant to me (but is maybe relevant for sandboxed evaluation), so I should just combine `parameterize` with `dynamic-wind` and call it a day.
