### ISSUE TITLE
Errortrace’s compilation handler doesn’t instrument modules if their compilation is triggered inside `local-expand`

### ISSUE THREAD

**Issue by lexi-lambda** [racket/racket#2621]
I discovered this issue as an issue with errortrace, but I’m reporting it here, since I think it’s actually a bug in the expander. If I have a module that `local-expand`s in a `#%module-begin` context, like this:

```racket
;; bar.rkt
#lang racket
(module modbeg-local racket
  (provide require (rename-out [modbeg #%module-begin]))
  (require (for-syntax syntax/parse))
  (define-syntax modbeg
    (syntax-parser
      [(_ form ...)
       (local-expand #'(#%plain-module-begin form ...) 'module-begin '())])))

(module m (submod ".." modbeg-local)
  (#%module-begin
   (require "foo.rkt")))
```

…then even if I run `racket -l errortrace -t bar.rkt`, `foo.rkt` will never be instrumented by errortrace.

The reason for this is that errortrace’s compilation handler cares about the value of `(namespace-base-phase (current-namespace))`, but when a module’s compilation is triggered from inside `local-expand`, `current-namespace` remains the namespace of the macro that called `local-expand`. I’m not sure what the right fix is, but one fix would be to re-parameterize `current-namespace` here:

https://github.com/racket/racket/blob/55dcdf553878f475fc4c59ba83556482d11499c9/racket/src/expander/namespace/module.rkt#L377

**Comment by mflatt** [comment]
Would it make sense to not require `(namespace-base-phase (current-namespace))` to match if the form to expand is a `module` form?

**Comment by lexi-lambda** [comment]
I’m not sure. I don’t really understand well enough what the check is intended to do or protect against.

**Comment by mflatt** [comment]
I see that the check was added specifically in 2012 in response to a bug report.

Unfortunately, the machine that provided access to that report recently died, so I'll need to figure out how to dig it up...

**Comment by mflatt** [comment]
@samth helped dig out the old bug report. It wasn't helpful, unfortunately, because the report is mostly in an example program in a GitHub repo that no longer exists.

I'm still convinced that annotating a phase-1 `module` form is a good idea. It might even work to allow annotation at phase 1 in general, since 2012 was probably before improvements to make errortrace generally work at phase 1. Being more conservative by only instrumenting modules seems reasonable and probably useful enough, though.

**Comment by lexi-lambda** [comment]
I agree that instrumenting phase 1 modules seems like a good idea, but is this really a case of instrumenting a module at phase 1? The `require` is an unshifted, phase 0 `require`. If the program didn’t use `local-expand`, `(current-compile)` would be called with `(current-namespace)` set to the original compilation namespace, with a base phase of 0.

**Comment by mflatt** [comment]
Closed by racket/errrortrace@cea390ea1b9755c5ae380557e752206f987bc88e (but I typed hte wrong issue reference there)

**Comment by samth** [comment]
One thing I noticed in the mailing list conversation -- maybe the bug report was for a program running in the "Pretty Big" language (ie, at the top level).

**Comment by mflatt** [comment]
I think viewing it as a phase-1 module expansion is probably the most general view of the issue. For example, I think `lazy-require` would also have that effect.

**Comment by rfindler** [comment]
Lets assume that a test case was added at the time so we'll find out if that same symptom shows up after a drdr run?

**Comment by lexi-lambda** [comment]
> I think viewing it as a phase-1 module expansion is probably the most general view of the issue. For example, I think `lazy-require` would also have that effect.

I guess I don’t understand what `(current-namespace)` is supposed to mean inside a `(current-compile)` handler. Obviously its value is relevant, since it’s used to expand the module, but I don’t know how to interpret the meaning of `(namespace-base-phase (current-namespace))` in that context.

**Comment by samth** [comment]
For posterity, the change was originally made in 284ba01db6. The test case added then is now here: https://github.com/racket/errortrace/blob/cea390ea1b9755c5ae380557e752206f987bc88e/errortrace-test/tests/errortrace/phase-1-eval.rkt and the comment there should probably be updated, but it shines less light on the question than you might hope.

**Comment by mflatt** [comment]
@rfindler  Good point that I could have just trusted the test case to reflect whatever was important about the change, instead of trying to recover the original report.

@lexi-lambda It's possible and maybe even reasonable for a macro to create a fresh namespace and start `eval`ing there. That namespace needs to live at phase 1 (or whatever the macro implementation's phase) for things to work out in terms of phase shifts and sharing within a phase. Maybe the phase could be shifted back to 0 in some cases earlier than in the `module` expander, but I think the current evaluator will sometimes need to be able to deal with module forms at phase 1.

**Comment by lexi-lambda** [comment]
Yes, that explanation makes sense to me, after thinking about it a little. I guess the idea behind the fix is that it doesn’t matter what phase a module is declared at, only what phase it’s instantiated at? I’m not entirely confident that’s correct, but it seems right. In any case, thank you for the fix.
