### ISSUE TITLE
bad interaction between serialization, places and raco exe/distribute

### ISSUE THREAD

**Issue by Bogdanp** [racket/racket#2693]
I've recently introduced places into my app and noticed that, upon deployment, the app would fail to start with an error when it tried to deserialize some data off of disk. The error looks something like this:

```racket
dynamic-require: unknown module
  module name: #<resolved-module-path:'#%embedded:g764:cart>
  context...:
   do-dynamic-require5
   /Applications/Racket v7.3/collects/racket/private/serialize.rkt:693:8: loop
   /Applications/Racket v7.3/collects/racket/private/serialize.rkt:688:2: deserialize
   /Users/bogdan/tmp/example/cart.rkt:23:6: temp4
   '#%mzc:dynamic: [running body]
   temp37_0
   for-loop
   run-module-instance!125
   perform-require!78
   top-level: [running body]
   eval-one-top12
   loop
   [repeats 1 more time]
```

The issue seems to have to do with how serialization and places interact but I'm unsure how to dig in further at this point.  I've been able to reproduce the issue both on macOS and on Linux, each running the latest stable builds of Racket 7.3 for their respective platforms.  The issue is only present when you create a distribution from the code.  Running `racket example/dynamic.rkt` does not reproduce this problem.

After deleting the serialized file, the problem disappeared and I have been able to successfully deploy new versions of the app since so it seems that introducing places into a program is currently a backwards-incompatible change as far as serialization is concerned. Distributions built before the places were introduced into the program seem to be able to deserialize data that was serialized after they were introduced.

I've created a [minimal example repo](https://github.com/Bogdanp/racket-serialization-issue-with-places) that you can use to reproduce this issue. The steps to reproduce are:

1. clone the repository and cd into its parent folder,
2. build a distribution with 

```bash
mkdir -p build && \
  raco exe -o build/example example/dynamic.rkt && \
  raco distribute dist build/example
```

3. run the distribution `./dist/bin/example`,
4. uncomment lines 4 and 9 in `example/dynamic.rkt`,
5. build another distribution with the same series of commands as above,
6. run the distribution again and you should receive an error akin to what I've posted above.

Note that the code will write a file to `/tmp/example-cart.dat` unless modified.

Thanks!

EDIT:

I tested this against Racket 7.2 and the problem is present there as well.

**Comment by mflatt** [comment]
The problem is that `raco exe` generates a name for each embedded module where the name can depend on the set of included modules or the order that they're encountered. It's not really about places, but about pulling in new modules or reaching them in different orders. For example, adding "dummy.rkt" before "cart.rkt" in "dynamic.rkt" has the same problem, even if "dummy.rkt" is an empty module. So, it's very easy to make a backward-incompatible change.

At the `create-embedding-executable` level, you can specify the embedded name of a module through the `#:modules` argument to avoid the auto-generated name. Besides using `create-embedding-executable`  instread of `raco exe`, you'd have to explicitly list the modules that have `serializeable-struct` declarations, though.

Probably it would be better for the generated names to be deterministic, and then your example would just work. I'll look into that.

**Comment by Bogdanp** [comment]
I see. Thanks for taking the time to explain this! I'll work `create-embedding-executable` into my build process for now.

**Comment by Bogdanp** [comment]
@mflatt would it be enough to make [`generate-prefix`](https://github.com/racket/racket/blob/0fefd6936a73752eea25b5ccc01dc39d37810c98/racket/collects/compiler/embed.rkt#L343) in `compiler/embed` deterministic?

If so, what do you think about changing it to take the "file" as a parameter and generate a hash instead of using `gensym`?

```racket
;; FNV-1a 32 bit variant.
(define (make-string-hash s)
  (define basis 2166136261)
  (define prime 16777619)
  (define scale (expt 2 32))

  (for/fold ([h basis])
            ([b (in-bytes (string->bytes/utf-8 s))])
    (((bitwise-xor h b) . * . prime) . modulo . scale)))

(define KNOWN-HASHES
  (make-hash))

(define (generate-prefix f)
  (define f:str (call-with-output-string (curry write f)))
  (define the-hash
    (do ([h (make-string-hash f:str) (add1 h)])
        ((equal? (hash-ref KNOWN-HASHES h f) f) h)
      h))

  (hash-set! KNOWN-HASHES the-hash f)
  (format "#%embedded:h~a:" the-hash))
```

It still wouldn't be fully deterministic, but it would for sure improve things for a relatively small increase in complexity.  The generated prefixes would look like this: `#%embedded:h2007112287:`

I'd be happy to PR the change if you think this approach is OK.

**Comment by mflatt** [comment]
Hi @Bogdanp - I just saw your suggestion, and it turns out that I was working on something similar, now pushed. So, yes, good idea!

Instead of hashing, the commit tries converting to a `lib` path and falls back to using paths relative to the executable's main module. There are some subtleties, but I think it works out.

**Comment by Bogdanp** [comment]
Excellent! Thank you!
