### ISSUE TITLE
rktio: Strategy for opening FIFO files for writing in nonblocking mode can cause lost data

### ISSUE THREAD

**Issue by lexi-lambda** [racket/racket#2784]
The strategy used by rktio for opening FIFO files in nonblocking mode is, in my opinion, buggy. To give an example of what can go wrong, see this program:

```racket
#lang racket/base
(require racket/system)

(void (thread (λ () (call-with-output-file "test.fifo" #:mode 'text #:exists 'update
                      (λ (out) (displayln "hello, world!" out))))))
(sleep 1)
(system* (find-executable-path "cat") "test.fifo")
```

Given a FIFO file named `test.fifo` in the current directory, the program ought to print `hello, world!`, but if you try it on macOS, it will hang forever:

```
$ mkfifo test.fifo
$ racket fifo.rkt
(hangs forever)
^Cuser break
```

### The source of the bug

I’ve found the source of this issue, and it is caused by rktio trying to avoid the fact that—at least on macOS—if you open a FIFO file for writing in nonblocking mode that is not currently open for reading by any process, it will fail with the `ENXIO` error code. To work around this, it retries with `O_RDWR` set instead of `O_WRONLY` (which I believe is technically undefined behavior according to POSIX but at least does mostly what you would expect on macOS). This opens the file successfully, and rktio’s `open_write` procedure returns.

There’s a problem with that, though: now the Racket process writes to the FIFO, and since the amount of data is smaller than `PIPE_BUF`, the write completes successfully without blocking. Now, catastrophically, the host process *closes* the FIFO (since control leaves `call-with-output-file`), which destroys any bytes that were still in it. When `cat` opens the FIFO for reading again a moment later, there isn’t any data in the FIFO anymore, and it just hangs forever.

### Possible solutions

I think the only fix for this is to accept that opening a FIFO is fundamentally a blocking operation, so a failure to open a FIFO in nonblocking mode needs to communicate with the thread scheduler to yield and try again later. The question, however, is how to detect the issue and how to properly wait for it to go away.

I am not an expert in this area by any means, but it does seem like just assuming any `open` call that produces `ENXIO` is blocked on a FIFO would be quite wrong. Maybe the right thing to do then is to `stat` the file, check if it’s a FIFO, and if it is, block. Of course, there’s a small race condition there, but it seems harmless: if the file changed between `open` and `stat`, erroring is alright, anyway.

The other question seems harder. Polling the FIFO is easy, but I don’t know how to efficiently block on it, since you need a file descriptor to be able to `select`/`poll`/whatever else! I took a peek at how GHC handles it, and they just bite the bullet and run every `open` call on its own OS thread. I don’t know if that’s a feasible solution for Racket based on the way Racket’s I/O and scheduling systems work, but I can’t think of another way.

**Comment by mflatt** [comment]
I think it makes sense to use a pthread (where supported) in place of the current `ENXIO` fallback, and I'm inclined to mostly hide it behind `rktio_fd_t`.

Here's my current experiment:

https://github.com/mflatt/racket/commit/da3a3ca65ad7dd23714accbf69448ecb42d8a6f2

This implementation makes `open-output-port` return right away, but the port as a fifo write end is not ready for writing until there's a reader so that `open` returns. That avoids the problem of how to expose a way to wait on fifos. Then again, it creates a new problem in that `unsafe-port->file-descriptor` won't work for a "file descriptor" that is actually still blocked on `open`. At the moment, I'm inclined to push the new problem to users of `unsafe-port->file-descriptor` by providing a suitable predicate, but I'm not sure.

Allowing a not-really-opened port to be closed before it `open` returns requires thread cancellation at the pthread level. It's a little worrying that leak-free support for cancellation during `open` is apparently relatively modern (see https://ewontfix.com/2/ and the glibc bug report that it links), but I guess leaks will at worst be very rare.

**Comment by lexi-lambda** [comment]
I appreciate you looking into this. I read the post you linked and the associated bug report, and it was a little depressing, but I agree with your assessment that it probably isn’t worth worrying about.

I read through your linked implementation, and most of it makes sense to me, though I admit I didn’t take the time to understand what’s going on in the `rktio_pending_open_attach` and `rktio_pending_open_detach` functions. I do wonder, though: why go to the effort of making `open-output-port` return right away? In my mind, `open-output-port` blocking on opening a FIFO is a feature, not a bug.

The blocking nature of opening a FIFO is itself a way of inter-process communication. Imagine, for example, that there is a limited resource pool of a resource, such as database connections. Now imagine 100 threads each open a (different) FIFO for writing, connect to the database, make a query, and write the results to the FIFO:

```racket
(define db-pool (connection-pool connect #:max-connections 8))

(define (run-worker out-path)
  (call-with-custodian-shutdown
    (thunk
      (define out (open-output-file output-path #:mode 'text #:exists 'update))
      (define db-conn (connection-pool-lease db-pool))
      (write (perform-some-query db-conn) out))))

(define worker-threads
  (for/list ([i (in-range 100)])
    (thread (thunk (run-worker (~a "out-" i ".fifo"))))))
(for-each thread-wait worker-threads)
```

If `open-output-port` never blocks, then every single thread will immediately call `connection-pool-lease`, regardless of whether or not anyone has opened the other end of the FIFO. This will exhaust the connection pool immediately, and the majority of the threads will be blocked on `connection-pool-lease`. If set of threads that successfully acquire a database connection is not the same set of threads whose FIFOs are opened first, then a lot of time will be wasted. Worse, if the downstream processes are also pooled (i.e. they only open a certain number of FIFOs at a time), there’s the potential for deadlock!

To put things another way, FIFOs are not just a communication mechanism, they’re actually a synchronization mechanism. I think `open-output-port` *should* block when opening a FIFO, and that would conveniently avoid the problem of `unsafe-port->file-descriptor`. Is there a reason that you’d really like to avoid making `open-output-port` a potentially-blocking operation? Personally, it seems simpler to me than making every I/O operation check for a “blocked-on-open” file descriptor, but maybe that’s easier because those operations already have the potential to block, anyway?

**Comment by mflatt** [comment]
If `open-output-file` could block, then we'd need to add something like `open-output-file-evt` to support a way to wait on file opening while also waiting on other events — on the principle that any blocking operation should have a multiplex-friendly form. That's a lot of extra plumbing, especially if file-open events get the same capabilities as file-stream ports (e.g., allowed as place messages). The same things happens at the rktio layer; it's much easier to add a check for a pending fd in the handful of places where that's needed, instead of adding a new rktio polling sub-API and extra finalization requirements for file opens.

Your database example can be fixed for a non-blocking `open-output-file` by adding `(sync out)` before the definition of `db-conn`. I agree that this example would be nicer if `open-output-file` blocked, but I think other examples will look nicer with blocking behavior in the write operation (where it has always been) instead of the open operation.

**Comment by lexi-lambda** [comment]
> Your database example can be fixed for a non-blocking `open-output-file` by adding `(sync out)` before the definition of `db-conn`. I agree that this example would be nicer if `open-output-file` blocked, but I think other examples will look nicer with blocking behavior in the write operation (where it has always been) instead of the open operation.

I’m not totally convinced by your last sentence, but your point about `(sync out)` is reasonable—I hadn’t thought of just doing that—so I’m fine with a non-blocking `open-output-file` so long as a note about the irregular behavior on FIFOs is added to the documentation.

**Comment by lexi-lambda** [comment]
Thank you very much for fixing this so quickly! I can confirm that my use case that previously failed now works perfectly. :)
