### ISSUE TITLE
Update the evaluation model to include threads and parallelism

### ISSUE THREAD

**Issue by edom** [racket/racket#2834]
Dear Racket developers who implemented the Racket primitives (or anyone else who can help),

I'm using Racket v7.3 on Ubuntu 14.04.

The Racket Guide says this about threads https://docs.racket-lang.org/reference/threads.html

> All constant-time procedures and operations provided by Racket are thread-safe because they are _atomic_. For example, `set!` assigns to a variable as an atomic action with respect to all threads, so that no thread can see a “half-assigned” variable.

While trying to find out what "atomic" means, I found this strange example:

```
#lang racket

(define (add1 x) (+ x 1))
(define (sleep_add1 x) (sleep 1) (+ x 1))

(define counter 0)

;;  This produces an expected result (counter = 2).
(set! counter 0)
(for-each thread-wait (list
    (thread (lambda () (set! counter (begin (sleep 1) (+ counter 1)))))
    (thread (lambda () (set! counter (begin (sleep 1) (+ counter 1)))))))
counter

;;  This produces an expected result (counter = 2).
(set! counter 0)
(for-each thread-wait (list
    (thread (lambda () (set! counter (begin (sleep 1) (add1 counter)))))
    (thread (lambda () (set! counter (begin (sleep 1) (add1 counter)))))))
counter

;;  This produces an unexpected result (counter = 1).
(set! counter 0)
(for-each thread-wait (list
    (thread (lambda () (set! counter (sleep_add1 counter))))
    (thread (lambda () (set! counter (sleep_add1 counter))))))
counter

;;  This produces an unexpected result (counter = 1),
;;  but not too surprising, because this is merely inlined sleep_add1.
(set! counter 0)
(for-each thread-wait (list
    (thread (lambda () (set! counter [(lambda (x) (sleep 1) (+ x 1)) counter])))
    (thread (lambda () (set! counter [(lambda (x) (sleep 1) (+ x 1)) counter])))))
counter

;;  This produces an unexpected result (counter = 1),
;;  but not too surprising, because I have expected the equivalence:
;;      (let ((Param Arg)) Body) = ((lambda (Param) Body) Arg)
(set! counter 0)
(for-each thread-wait (list
    (thread (lambda () (set! counter (let [(x (+ counter 1))] (sleep 1) x))))
    (thread (lambda () (set! counter (let [(x (+ counter 1))] (sleep 1) x))))))
counter
```

Is this a problem in my understanding, in Racket, or in the documentation? Isn't `(sleep 1)` a "constant-time operation"? On the other hand, it is true that `counter` is never "half-assigned".

Thank you.

Best regards,

Erik

**Comment by rfindler** [comment]
The behavior your are seeing is legit. The point is that the interleaving between two threads can be very fine-grained (in between a variable look up and a set!, in fact). But it cannot be "inside" _just_ the set! itself.

**Comment by soegaard** [comment]
Den ons. 25. sep. 2019 kl. 16.48 skrev Robby Findler <
notifications@github.com>:

> The behavior your are seeing is legit. The point is that the interleaving
> between two threads can be very fine-grained (in between a variable look up
> and a set!, in fact). But it cannot be "inside" *just* the set! itself.
>
Erik: Just wanted to add, that if you need atomic update based on an
existing value, then due to what Robby mentions,
there is an atomic  compare-and-set operation:

https://docs.racket-lang.org/reference/boxes.html?q=atomic#%28def._%28%28quote._~23~25kernel%29._box-cas%21%29%29

 /Jens Axel

**Comment by rfindler** [comment]
Oh (as Jens Axel knows!) there are lots of way to manage concurrency in Racket. The biggest ones are "evt"s and "place"s, which are aimed at very different uses. 

If you have more questions about these kinds of things, maybe try taking them up on the Racket Users mailing list? It is a pretty active place.

**Comment by edom** [comment]
Hello Robby & Jens, thanks for the very quick reply!

The story is, I'm sketching a web server using the Continue framework, and, for peace of mind, I'm looking for guarantees of the language semantics, something like Java's "happen-before" relationship ([JLS 7 section 17.4.5](https://docs.oracle.com/javase/specs/jls/se7/html/jls-17.html#jls-17.4.5)), so that I can confidently vindicate (or blame) myself when errors happen. (I'm not saying that Racket should become Java; I'm just saying that I want to understand a language's semantics before I write programs in it.)

I expected the [Racket evaluation model](https://docs.racket-lang.org/reference/eval-model.html) to imply the answer to my question, but that model seems to assume single-threadedness. 

Therefore, I think what I should have asked is: _Can the evaluation model be updated in order to include threads and parallelism?_ The model should also formalize what Robby means by "it cannot be 'inside' just the set! itself" (How big is this "inside"? Why does a call fit inside `set!` but a let doesn't fit inside `set!`? Isn't a call bigger than a let?)

However, even if the model is updated, I think I still have to synchronize variables accessed by multiple threads, using one of the methods you suggested (box-cas, evt, place, and other methods in the documentation).

Thanks for helping me find what I actually want. I'm going to change the title of this issue to "Update the evaluation model to include threads and parallelism".

I did not ask this on the mailing list because I think the model can only be updated by the developers (the people who know the intended semantics). But I may be wrong. Let me think if it is still a good idea to ask about this on the mailing list. (I just didn't want to disturb lots of people who may not be able to solve the problem.)

**Comment by samth** [comment]
A few things to note about the semantics here:

1. A call is not "inside" a `set!` in this sense you mean. For example, in this program:

```
(set! x (add1 x))
```
there is _not_ a guarantee that the add and set happen together atomically. For example, if you create two threads that just execute that line over and over, you might see situations where the variable is not incremented by 1.

2. There a discussion of threads in the evaluation model [here](https://docs.racket-lang.org/reference/eval-model.html#%28part._thread-model%29). That isn't presented in terms of reduction rules, but you could imagine the reductions shown earlier on that page being interleaved.

3. The evaluation model for futures and places (Racket's constructs for parallelism) is somewhat more complex, and Racket doesn't have a formal specification of exactly what's guaranteed in terms of ordering. That's what the Java specification that you linked to talks about. You don't need to worry about this at all to just use the web server, though. 

4. Typically "discussions" in Racket happen on the mailing list rather than on GitHub, although it's fine to have this discussion here. If what you're interested in is how to program with concurrency in Racket, then the `racket-users` mailing list is a good place. If you want to discuss how to formally model Racket's concurrency, then the `racket-dev` list is the right place.

**Comment by soegaard** [comment]
Den tor. 26. sep. 2019 kl. 20.10 skrev Erik Dominikus <
notifications@github.com>:

> Therefore, I think what I should have asked is: *Can the evaluation model
> be updated in order to include threads and parallelism?* The model should
> also formalize what Robby means by "it cannot be 'inside' just the set!
> itself" (How big is this "inside"? Why does a call fit inside set! but a
> let doesn't fit inside set!? Isn't a call bigger than a let?)
>
>
FWIW the section on threads has the following paragraph:

All constant-time procedures and operations provided by Racket are
thread-safe because they are atomic. For example, set!
<https://docs.racket-lang.org/reference/set_.html?q=thread#%28form._%28%28quote._~23~25kernel%29._set%21%29%29>
assigns
to a variable as an atomic action with respect to all threads, so that no
thread can see a “half-assigned” variable. Similarly, vector-set!
<https://docs.racket-lang.org/reference/vectors.html?q=thread#%28def._%28%28quote._~23~25kernel%29._vector-set%21%29%29>
assigns
to a vector atomically. The hash-set!
<https://docs.racket-lang.org/reference/hashtables.html?q=thread#%28def._%28%28quote._~23~25kernel%29._hash-set%21%29%29>
procedure
is not atomic, but the table is protected by a lock; see Hash Tables
<https://docs.racket-lang.org/reference/hashtables.html?q=thread> for more
information. Port operations are generally not atomic, but they are
thread-safe in the sense that a byte consumed by one thread from an input
port will not be returned also to another thread, and procedures like
port-commit-peeked
<https://docs.racket-lang.org/reference/Byte_and_String_Input.html?q=thread#%28def._%28%28quote._~23~25kernel%29._port-commit-peeked%29%29>
 and write-bytes-avail
<https://docs.racket-lang.org/reference/Byte_and_String_Output.html?q=thread#%28def._%28%28quote._~23~25kernel%29._write-bytes-avail%29%29>
offer
specific concurrency guarantees.


>
>

**Comment by rfindler** [comment]
Does it help that if I tell you that if you don't use places or futures then Racket is sequentially consistent (i.e., threads are sequentially consistent)? In other words, Racket has a far simpler memory model than your processor or Java, etc.

**Comment by edom** [comment]
Sam, thanks for giving me the key to understanding the semantics of threads. I imagine an interleaving of reduction sequences in the example below.

Robby, unfortunately that does not clear up the confusion, but, good news: With your hint ("interleaving") and Sam's hint ("interleaving _of reduction sequences_"), I have an example below that may clarify things. I think now I understand what you mean by "inside": A variable lookup is indeed one separate reduction step. It's great that Racket has a simpler memory model than Java; I believe the problem is just in the way it is presented; I didn't understand the reference until you and Sam gave me some hints. The reference's "Threads" section can perhaps be made more easily understandable by the example below. :)

Jens, unfortunately I didn't find any definition of Racket's "constant-time procedures and operations": Does it mean "primitives" or "kernel forms"? After all, `(set! x x)` takes constant time, but it is not atomic. I suspect that all of us have been using the words like "atomic", "thread-safe", and "consistent" differently. I think, while it is true that `set!` never produces a half-assigned variable, it does not mean that `(set! loc expr)` is atomic; it is only atomic when `expr` is a value; I define "atomic" in the example below.

All: Here comes an example of "interleaving of reduction sequences". I hope this clarifies the semantics of threads and the meaning of "atomic". If you can verify that my understanding is correct, I can help you put the example into the reference, if you don't mind.

---

The semantics of a program with _one thread_ T is a reduction sequence S(T) = < R1, R2, R3, ... >.

The semantics of a program with _multiple threads_ T, U, V, ... _can_ be any of all possible _interleavings_ of the reduction sequences S(T), S(U), S(V), ..., although it is undefined _which_ interleaving _is_ the semantics. Thus, that multi-threaded program is _well-defined_ only if all those interleavings produce the same result.

An _interleaving_ of the sequences X1, ..., Xn is any sequence produced by this non-deterministic procedure:

```
var Result := empty sequence.
var Sequences := copy of X1, ..., Xn.
Repeat until all sequences in Sequences are empty:
    Choose any non-empty sequence S from Sequences.
    Remove the first element from S.
    Add that element to the back of Result.
Now Result is an interleaving of X1, ..., Xn.
```

For example, let us write an example program that is not well-defined.

First, consider the reduction sequence <A,B,C> of the expression `(set! counter (+ counter 1))` where `counter` is a top-level variable:

```
A  =  (set! counter (+ counter 1)) --> (set! counter (+ <in> 1))  {read value <in> from counter}
B  =  (set! counter (+ <in> 1))    --> (set! counter <out>)       {compute <out> = <in> + 1}
C  =  (set! counter <out>)         --> (void)                     {write value <out> to counter}
```

Then, imagine that a program has `counter` initialized to zero and then has two threads reducing the above `set!` expression concurrently. The semantics of that program can be any of these 6! / (3! * 3!) = 20 possible interleavings of <A,B,C> and <A,B,C>:

```
ABCABC, the only interleaving that produces counter = 2, because this is the only interleaving in which the first C precedes the second A;
ABACBC, producing counter = 1;
AABCBC, producing counter = 1;
and all the other 17 possible interleavings, each producing counter = 1.
```

As we can see, not all interleavings above produce the same result; thus that program is not well-defined.

An expression is _atomic_ (A thread reduces an expression _atomically_) iff all other threads always see that either the entire expression has been reduced completely or has not been reduced at all.

An expression has been _reduced completely_ iff it has been evaluated into an irreducible value and all its side-effects have finished.

For example, `(set! loc expr)` is only atomic when `expr` is a value, not a variable, not even `loc` itself, because `(set! loc loc)` takes two steps to reduce completely:

```
(set! loc loc)     --> (set! loc <value>)  {read <value> from loc}
(set! loc <value>) --> (void)              {write <value> to loc}
```

**Comment by samth** [comment]
This is mostly right, but the "not well defined" idea is not right. Instead, Racket programs with threads have multiple possible legal behaviors. The program in your example can produce either 1 or 2 as the value for `counter`. 

The phrase "constant time procedures and operations" is intended to include both primitives (such as `+` and `vector-ref`) as well as language forms (such as `set!` and variable reference). In general this guarantee is just that you will not see "partially-completed" versions of these operations, no matter what thread operations you use. There is not a list of these operations at the moment.

**Comment by rmculpepper** [comment]
The reduction sequence of an expression depends on the shared state, so you can't generate reduction sequences independently and then interleave them afterwards.

There's a redex model of threads here: https://github.com/racket/redex/blob/master/redex-examples/redex/examples/threads.rkt. You can run it with `racket -l redex/examples/threads`, assuming you have the main Racket distribution installed. In the model, a `p` ("configuration") consists of a store and multiple threads (represented by expressions), and reduction relates pairs of configurations. You can think of reduction as taking a configuration an nondeterministically producing a new configuration.

**Comment by mflatt** [comment]
I agree that the Reference's explanation of threads can use some work. As a starting point, I'll move the last paragraph in the 11.1 intro to 1.1.13, since it's about the general model of threads, and all of that should be in one place. Some clarifications on what an "operation" means is certainly in order (e.g., assignment to a variable is an operation, but the evaluation of a `set!` form with its subexpressions is not a single operation).

It's not the Reference's place to cover Concurrency 101, so I won't try to include an example illustrating how concurrent threads with shared state imply non-determinism. Defining atomic operations and leaving some details to the definition of sequential consistency (I can add a cite) seems like the right direction to go for the Reference.

**Comment by edom** [comment]
@rfindler I just found out that "sequential consistency" has a specific meaning; I just found out about Lamport 1979; I thought you invented that term just now, which was why I said it didn't help! Sorry! You can ignore my previous reply. (facepalm)

**Comment by rfindler** [comment]
Oh, no worries! It is a good term and I am
Glad it is now better known. :)

Robby

**Comment by mflatt** [comment]
Have we improved the docs enough to close this issue, or is more needed?

**Comment by edom** [comment]
Yes, I think you have improved the docs enough to close this issue. I think it is reasonable to expect readers to infer the model from the concept of "sequential consistency" and the clarifying paragraph you added:

> Note that the evaluation of a @racket[set!] expression with its subexpression is not necessarily atomic [...]

Thank you very much!
