### ISSUE TITLE
submodule reference error hidden without gc

### ISSUE THREAD

**Issue by samth** [racket/racket#2907]
This program:

```
#lang racket/base
(require (for-syntax racket/base))
(module m racket/base
  (define (f x) (sync x)))

(require racket/place racket/runtime-path)

(define-runtime-module-path worker-mpi (submod "." m))
(define (go)
  ;(collect-garbage)
  ;(displayln (current-memory-use))
  (define p (dynamic-place '(submod "." m) 'f))
  (collect-garbage)
  (displayln (current-memory-use))
  (list p))

(module+ main (go))
```

consistently produces the error:

```
standard-module-name-resolver: no base path for relative submodule path: (submod "." m)
  context...:
   standard-module-name-resolver
   module-path-index-resolve
   do-dynamic-require5
```

However, if you comment out the call to `(collect-garbage)`, the error goes away. The error is consistently there on Racket CS. 

I assume there's some weak cache in the expander that gets cleared by `(collect-garbage)`, but that doesn't seem like it should affect the semantics.

**Comment by mflatt** [comment]
This problem appears to have been fixed. I'm unable to avoid the error even when running with `PLTDISABLEGC`.

There were changes to the way some module-path shifts or resolutions were cached, and I vaguely remember having this problem in mind among others, but I'm not sure I remember correctly. So, that's why there's an "unexplained" tag.
