### ISSUE TITLE
CS DrRacket Bundle probably should not contain symbolic link on Catalina

### ISSUE THREAD

**Issue by jbclements** [racket/racket#2910]
Per email discussion: existence of a symbolic link in the CS DrRacket.app bundle causes installation to trigger a notarization-related failure on MacOS 10.15 Catalina, suggesting that the developer can't be identified and offering to move the application to the Trash. It appears that the solution is to make a copy of the linked file inside the bundle.

**Comment by mflatt** [comment]
My initial plan was to make the distribution builder copy the "boot" directory the same as it copies the Racket framework. But that doesn't work, because `codesign` wants everything in the "MacOS" bundle directory be in Mach-O format.

So, I went one step further and added a build mode that statically links to the Racket runtime implementation (which would otherwise be in the "Racket" framework) and also embeds boot files in the executable. That way, the `racket` executable is completely stand-alone, so signing should work for it (I think), and the `GRacket` application and derived ones like `DrRacket` are also always stand-alone.

The new build mode is not on by default when you build from a checkout, but `distro-build` forces a Mac OS build into that mode, so no new configuration should be needed for the snapshot or release builds.

**Comment by jbclements** [comment]
That sounds great. I’m currently trying to move the racket-dev builds back into the /home/scheme directory, now that NEU systems has re-mounted the home directories using NFS4. After that I’m hoping to get the notarization running on penghu, though I’m not sure whether penghu is currently up.

John

**Comment by rfindler** [comment]
@jbclements : Penghu is up but is suffering from [this problem](https://forums.virtualbox.org/viewtopic.php?f=8&t=95685), so if a non-mac build gets started then it will kernel panic (let me know if you notice this happening; the nightly builds are turned off until that gets fixed).
