### ISSUE TITLE
Mutexes for futures?

### ISSUE THREAD

**Issue by DarinM223** [racket/racket#2957]
Is it possible to add mutexes that work with futures? Binary fsemaphores seem to deadlock when multiple futures are accessing it.

For example, this sometimes deadlocks (in Chez Scheme backend):
```racket
(define mutex (make-fsemaphore 1))
(for/async ([i 10])
  (fsemaphore-wait mutex)
  (println i)
  (fsemaphore-post mutex))
(fsemaphore-count mutex) ; Sometimes returns 0
```

**Comment by mflatt** [comment]
Hi @DarinM223,

Are you really seeing `fsemaphore-count` produce 0, or is it that only the first future manages to print, so the only output is sometimes "0"?

Futures are not threads, and an fsemaphore doesn't really work as a lock (but it can work a signaling mechanism for other purposes). The documentation needs more explanation here.

The problem in your specific example is that `println` has to get the current output port, which means it needs the current continuation to determine the output port, which means that it cannot complete until the future is `touch`ed`. Unfortunately, the fact that the future must wait for `touch` is discovered only after `mutex` is taken. If a future that has taken `mutex` is not the one the main thread is `touch`ing, then the pair of futures effectively deadlock. 

More generally, I think the idea of a future as best-effort parallelism and unspecified concurrency is just not compatible with the idea of a critical region.

Meanwhile, when I try your program in Racket CS, I usually get "internal error: unrecognized future state". That's a bug in the Racket CS implementation of futures, and I'll push a repair.

**Comment by samth** [comment]
Note that you ought to be able to implement a spin-lock with `box-cas!`, which is future-safe.

**Comment by mflatt** [comment]
The problem isn't with fsemaphores as an implementation of locks, but with the idea of a lock with futures.

**Comment by DarinM223** [comment]
For my example, I evaluate `mutex` once, then run the `for/async` multiple times until it deadlocks, kill it, and then run `fsemaphore-count` to check if it is 1 and I see that its 0.

Thanks for the explanation on why the example deadlocks. I've also been having deadlock problems with things like [this test](https://github.com/DarinM223/futures-structures/blob/master/channel.rkt#L71-L92). Is this also caused by futures waiting until `touch`? The code inside the futures seem to only use vector, struct, and fsemaphore operations.

**Comment by mflatt** [comment]
@DarinM223 On the fchannel test: yes and no.

The underlying principle is the same: futures are not threads, and trying to implement locks with fsemaphores is not guaranteed to work.

The details are different. In this case, the relevant question is whether a future will make progress concurrently if it *could* make progress concurrently. (In the example at the top of this PR, deadlock happens in a situation where no future can make progress.) Nothing in the specification of Racket futures provides a guarantee of concurrent progress. So, if a program `touch`es a future that is blocked on an fsemaphore, there's no guarantee that it will become unblocked by an active future that would be allowed to post to the fsemaphore.

The Racket CS implementation of futures is meant to make progress unless all future threads are busy. So, the fchannel example running by itself (i.e., no other futures running) on a machine with multiple processing cores should happen to work in Racket CS, I think. I pushed an improvement where the blocked main thread wasn't notified as it should be by `fsemaphore-post`, and now I no longer get the fchannel test to block on Racket CS when running the test by self. But it works only because of those environment details.

**Comment by mflatt** [comment]
I should also note that while `box-cas!` does not fundamentally solve a problem if it's just used to implement a lock, `box-cas!` and similar operations are useful for implementing "lock-free" data structures, and those can work reliably with futures.

**Comment by DarinM223** [comment]
Okay it seems like adding fmutexes won't help the futures blocking in these types of cases. Thanks!
