### ISSUE TITLE
Move Actions CI to a container based solution on Linux

### ISSUE THREAD

**Issue by pmatos** [racket/racket#2974]
We need to move our Linux jobs to a container based solution on Linux because the Linux VMs keep having intermittent issues like:
https://github.com/racket/racket/runs/348273932#step:6:102

Issues like these are well-known in the community:
https://github.community/t5/GitHub-Actions/ubuntu-latest-Apt-repository-list-issues/td-p/41122

The solution is to select a base container for the work in a job. I started working on this but we are facing another problem - also known in the community. The Actions CI syntax does not allow to conditionally select a container which means that to do so we need to separate the Linux/MacOS matrix further duplicating code (because it also does not support yaml).
More information is here:
https://github.community/t5/GitHub-Actions/Run-matrix-job-on-macos-and-on-ubuntu-in-container/m-p/32796#M1249

Current solution is possibly remove the matrix for `ubuntu-latest` and `macos-latest` and duplicate the jobs for these platforms.

**Comment by pmatos** [comment]
The problem with this is that there are some tests that do not like to be ran inside a container. Take for example:
https://github.com/LinkiTools/racket/runs/350415970#step:10:86

These could be tests that for example, require access to special devices not available inside a container unless you have privileged access. @jackfirth might know more about these issues.

**Comment by jackfirth** [comment]
Based on [this comment](https://github.com/racket/racket/blob/eda5f7a817f1588d783f2467c1d3fe0faf2ca529/pkgs/racket-test-core/tests/racket/subprocess.rktl#L450) in the failing test code, I think the problem is that some of the subprocess tests assume that the Racket process is *not* the init process (PID 1). But docker containers run the container's entrypoint as PID 1 and you don't get an init process unless you explicitly set one up when building the container. I think the right way to fix the test is to try to remove its assumption that there's an init process.

**Comment by samth** [comment]
Couldn't we just use sh as the init process to work around this issue?

**Comment by pmatos** [comment]
I am going back to this issue since it would be useful to get the work containerized. It will help reproduction later on when we have a script to trigger the actions locally (hopefully one day).

Given the comments from @jackfirth and @samth I will try to see what's going on with tests either assuming an init process or explicitly setting up one in the docker container. Maybe the later is better so we don't go around changing potentially many tests. Open to suggestions though.

**Comment by jackfirth** [comment]
Either approach sounds reasonable to me.

If the tests are revealing behavior that's actually _broken_ when Racket runs as PID 1, that would be more of a problem since anyone who runs Racket in a docker container is at risk of hitting the issue. But as long as the test failures are just an artifact of the test setup and teardown, I don't see any reason not to fix the issue by running the tests with `sh` as the init process.

**Comment by pmatos** [comment]
Turns out this problem was due to the lack of `ps` on the container. Fixed here https://github.com/racket/racket/commit/43c88766439f76ba46232a7b3b66f8a712d1cfa1
