### ISSUE TITLE
#f false is misinterpreted with #t true (and in debug mode it's OK)

### ISSUE THREAD

**Issue by formalizm** [racket/racket#3081]
In the following program the control flow falls into the wrong 'if' branch path:
```racket
#lang racket

(define (return-false) #f)

(define foo
  (let ([bar (return-false)])
    (if bar (string-append "bar: " bar)
        (error "bar is false, so why this error is not reached?"))))
```

This program returns:
> Welcome to DrRacket, version 7.6 [3m].
Language: racket, with debugging; memory limit: 128 MB.
. . string-append: contract violation
  expected: string?
  given: #f
  argument position: 2nd
  other arguments...:

When running it under the debugger (by stepping through each expression), it correctly returns an "unreachable" error.

**Comment by mfelleisen** [comment]
On git head (1 or 2 days behind), add
```
(return-false)
```
between the definition of the function and the definition of `foo` and it works fine, too.

**Comment by gus-massa** [comment]
To get the error in DrRacket, it is necessary to have "Preserve Stacktrace" enabled in the language configuration. (This option is enabled by default, but I usually disable it.)

It's an error in the BC version, the CS version is (aparently) fine.

**Comment by mflatt** [comment]
I have a repair to push after testing a little more.

The problem is in the Racket BC optimizer, where it doesn't remove local-variable type information correctly when leaving a `let` binding. Several other things also have to line up to provokee the bug in this example (including "preserve stacktrace"), but it's definitely in the "surprising that this bug could be there for so long" category.

Thanks for the report!

**Comment by mflatt** [comment]
P.S. Although the bug is in the type-reconstruction part of the optimizer, it was my bug and not @gus-massa's. :)

**Comment by formalizm** [comment]
> Thanks for the report!

Welcome.
