### ISSUE TITLE
find-exe: can't find Racket executable for variant 3m

### ISSUE THREAD

**Issue by rachitnigam** [racket/racket#3089]
I recently upgraded to Racket 7.6 and `raco exe` seems to have broken. This command used to work with Racket 7.5 and simply running `racket src/example-gen.rkt` works as expected.

Error message:
```
raco exe --vv -o dios-example-gen src/example-gen.rkt
find-exe: can't find Racket executable for variant 3m
  context...:
   /usr/local/Cellar/minimal-racket/7.6/share/racket/collects/compiler/find-exe.rkt:7:0: find-exe
   /usr/local/Cellar/minimal-racket/7.6/share/racket/collects/compiler/embed.rkt:1445:0: create-embedding-executable
   "/usr/local/Cellar/minimal-racket/7.5/share/racket/pkgs/compiler-lib/compiler/commands/exe.rkt": [running body]
   temp35_0
   for-loop
   run-module-instance!
   "/usr/local/Cellar/minimal-racket/7.6/share/racket/collects/raco/raco.rkt": [running body]
   temp35_0
   for-loop
   run-module-instance!
   "/usr/local/Cellar/minimal-racket/7.6/share/racket/collects/raco/main.rkt": [running body]
   temp35_0
   for-loop
   run-module-instance!
   perform-require!
```

OS X Catalina: Darwin 19.3.0 Darwin Kernel Version 19.3.0
Racket installation through `brew`. `brew info` reports that it installed the `minimal-racket` package.

**Comment by rachitnigam** [comment]
Oddly, this is fixed when I removed `minimal-racket` and replaced `racket` (using `brew install cask racket`).

**Comment by shhyou** [comment]
Comparing the formulas of `minimal-racket` and `racket`, my guess is that this is an issue with the minimal-racket formula. Homebrew builds minimal Racket from source, instead of directly using the installer (<https://mirror.racket-lang.org/installers/7.9/racket-minimal-7.9-x86_64-macosx.dmg>). So I am removing the bug label here.

- [minimal-racket.rb](https://github.com/Homebrew/homebrew-core/blob/920d0b3e/Formula/minimal-racket.rb)
- [racket.rb](https://github.com/Homebrew/homebrew-cask/blob/a219887d2/Casks/racket.rb)

**Comment by mflatt** [comment]
The Homebrew package seems to be in good shape currentlyœ. I'm able to install minimal Racket 8.0, then install "compiler-lib", then use `raco exe`. There's also a full-Racket cask. So I'll close this issue.
