### ISSUE TITLE
local-expand is slow when plain-module-begin is supplied

### ISSUE THREAD

**Issue by sorawee** [racket/racket#3165]
Continued from #3162, related to emina/rosette#155

Consider the following program `test.rkt`:

```
#lang racket

(define-syntax (@if stx)
  (syntax-case stx ()
    [(_ test-expr then-expr else-expr)
     (quasisyntax/loc stx
       (void test-expr
             (#%plain-lambda () then-expr)
             (#%plain-lambda () else-expr)))]))

(define-syntax (and/dot stx)
  (syntax-case stx ()
    [(_) #'#t]
    [(_ x) #'x]
    [(_ x . ys) #'(@if x (and/dot . ys) #f)]))

(define-syntax (test stx)
  (with-syntax ([(xs ...) (for/list ([i 2000]) #t)])
    (time (local-expand #'(and/dot xs ...) 'module-begin '())) ;; line 1
    (time (local-expand #'(#%plain-module-begin (and/dot xs ...)) 'module-begin '())) ;; line 2
    #'(and/dot xs ...))) ;; line 3

(test)
```

Running this program with `time test.rkt` produces the following output:

```
cpu time: 1443 real time: 1506 gc time: 63
cpu time: 17596 real time: 19851 gc time: 2451
racket test.rkt  20.33s user 0.73s system 89% cpu 23.535 total
```

Comparing line 1 with line 2, we can see that by wrapping the form with `#%plain-module-begin`, the expansion time increases tenfold for n = 2000!

But it's really weird because the macroexpander itself doesn't seem to have trouble expanding line 3 which eventually will be wrapped with `#%plain-module-begin` (the majority of time spent in the whole program is on line 2. Line 3 would cost at most 23s - 17s = 6s).

**Comment by samth** [comment]
I don't know if this is the root of the difference, but line 1 is usually not what you want -- instead, expanding in `'module-begin` context usually makes sense when the program is wrapped in something that eventually expands to `#%plain-module-begin`.

**Comment by sorawee** [comment]
Right. I want to contrast line 1 and line 2, so I wrote it in that way. I understand that line 1 should really have `'expression` instead (which by the way is as performant as line 1).

**Comment by mflatt** [comment]
That commit has nothing to do with this issue. It was meant to be #3193, instead.

**Comment by mflatt** [comment]
The difference between line 2 and line 3 is that line 2 has to produce the expanded form of the module body as a syntax object. To do that, it ends up parsing twice: once for the expansion to a syntax object, and again to get the expanded expression in compiled form (in case there are submodules that need the enclosing module to be instantiated). You can see that it's about expansion to a syntax object by timing `raco expand` instead of `racket`.

The second pass, to get from expanded to compiled, seems like it should be the fast one. But it turns out that the nesting of `lambda` forms creates scopes sets that trigger quadratic behavior on re-parsing. I think the second pass doesn't need scopes that it creates (again) and that trigger quadratic behavior, so I'll experiment with a change to the expander to skip them.

**Comment by sorawee** [comment]
Thanks! This helps a lot. Closing.
