### ISSUE TITLE
Large set of dependencies due to racket-doc

### ISSUE THREAD

**Issue by Metaxal** [racket/racket#3214]
Out of the ~1500 user packages on pkgs, more than 1100 depend indirectly on drracket, which I don't believe is right.

Even a package as small as "text-table"—meant for mere text output—which depends directly only on
'("base" "racket-doc" "rackunit-lib" "scribble-lib")
indirectly depends on 148 collections, including
draw, drracket, eli-tester, gui, icons, pict, math, web-server-lib, ...

That makes the idea of a 'minimal' racket a little vacuous.

The culprit is ["racket-doc"](https://github.com/racket/racket/blob/master/pkgs/racket-doc/info.rkt), which depends on almost everything. It's only for building the docs, not for the runtime, but still.

For backward compatibility, racket-doc needs to stay. But maybe it would make sense to also provide smaller doc packages, in particular a "racket-nogui-doc" and make `raco setup --check-pkg-deps` and `raco setup --fix-pkg-deps` provide the minimum set of packages needed to fix the documentation.

Would that make sense or is there something I'm missing?

**Comment by sorawee** [comment]
Wouldn't [binary package](https://docs.racket-lang.org/pkg/strip.html#%28tech._binary._package%29) work here? Put `racket-doc` in `build-deps`. When your users install the binary package from the pkg-build.racket-lang.org, `racket-doc` won't be downloaded.

Personally, I would propose to trim dependencies listed in my comment in #1465 instead, since those are the ones that will be installed even though binary package is used.

**Comment by Metaxal** [comment]
Thanks for the link, I'm closing this one as it's a duplicate.
