### ISSUE TITLE
[Docs] different font used in example of quasiquote

### ISSUE THREAD

**Issue by albertnetymk** [racket/racket#3259]
I notice the backtick used for quasiquote is different for example `#hash(("a" . ,(+ 1 2)))` from https://docs.racket-lang.org/reference/quasiquote.html. Is it intentional?

The corresponding source code (https://github.com/racket/racket/blob/master/pkgs/racket-doc/scribblings/reference/syntax.scrbl#L2878) looks quite complex compared to its neighbors.

**Comment by AlexKnauth** [comment]
It looks like the `` ` `` got mangled into `‘` somehow when the docs were rendered.

I'm guessing the uses of `racketvalfont` / `racketfont` are wrong because of how they decode their content. The docs for them warn about this:
>  Beware that `pre-content` is decoded as usual, making `racketfont` a poor choice for typesetting literal code.

And it's the "decoding" process that mangles the backtick into a fancy quote
> * `` ` ``: converted to `'lsquo`, which is a fancy quote: `‘`

So instead of `racketfont` and `racketvalfont`, what should it use to avoid decoding and mangling the backtick?

Also, I'm confused about why this is necessary, why don't the docs just use `` `#hash(("a" . ,(+ 1 2)))`` there?

**Comment by mflatt** [comment]
The use of `eval:alts` was a workaround for incorrect coloring of `` `#hash(("a" . ,(+ 1 2))) ``, but I'll push a repair for that in Scribble and then correct/simplify the document.

**Comment by albertnetymk** [comment]
Thank you for the explanation and the fix.
