### ISSUE TITLE
Opening files in racket/collects/racket keep DrRacket busy

### ISSUE THREAD

**Issue by yjqww6** [racket/racket#3273]
Opening files (just open, not run) in racket/collects/racket (for example, "generator.rkt") keep DrRacket busy(even with background expansion disabled), and memory consumption keep increasing.
I have tried several versions and variants from 7.4 to current snapshot on Windows and Ubuntu, but got same behavior.

Pressing the Stop button shows it breaks from https://github.com/racket/drracket/blob/9c66e3570b240ec6ce1a4ac25825db2bb74bc72a/drracket/drracket/private/rep.rkt#L1209.
But the Stop button doesn't help, the Kill button stops it.

**Comment by rfindler** [comment]
DrRacket does do a lot of things when you open a file, after background
expansion the next biggest is probably the syntax colorer.

Does it eventually calm down or does memory use keep increasing?

**Comment by yjqww6** [comment]
Its memory usage keep increasing until my machine become unresponsive and I have to kill it, but simply copying a file (without relative dependency) outside collects/racket and opening it would not have this behavior.

**Comment by rfindler** [comment]
I am having trouble guessing what it is (trying) to do. Can you try
starting DrRacket from the command line ("racket.exe -l drracket"  Under
Windows and just running bin/drracket on other platforms) and then typing
control-c when it gets going to see if a hint come out from the stack trace?

Robby

**Comment by yjqww6** [comment]
The stacktrace from command line may not be helpful
```
^Cuser break
  context...:
   p
   call-in-empty-metacontinuation-frame
   check-break-prefix
   call-with-empty-metacontinuation-frame-for-swap
   temp50_1
   dynamic-wind
   temp52_0
   .../common/queue.rkt:634:3
   thunk_10
   call-in-empty-metacontinuation-frame
   call-with-empty-metacontinuation-frame-for-swap
```
Also, backtrace from the stop button is
```
user break

.../private/rep.rkt: 1210:24 

.../private/more-scheme.rkt: 148:2 

.../private/rep.rkt: 1180:9 

.../private/rep.rkt: 1511:17 

.../common/queue.rkt: 435:6 

.../common/queue.rkt: 486:32 

.../private/more-scheme.rkt: 148:2 

.../common/queue.rkt: 374:13 

```

And then, click the Run shows
```
define-values: assignment disallowed;
 cannot re-define a constant
  constant: current-yielder
  in module:"/Applications/Racket v7.7/collects/racket/generator.rkt"
```

**Comment by rfindler** [comment]
Do you have the memory limit disabled? If so and if you turn it back on, do you see an out-of-memory message in the interactions window?

**Comment by yjqww6** [comment]
I remember that in RacketBC, it did ask for increasing memory limit, but in RacketCS, it doesn't.

**Comment by rfindler** [comment]
Under the "racket" menu is the item "Limit Memory". If you choose it, do you see that the memory limit is turned on or disabled? If it is turned on can you lower the number and if it is disabled can you turn it on? If you do those things, then I guess you'll see an out-of-memory message in the interactions window instead of DrRacket running forever. Hopefully this will at least let you open the file for now and I'll see if there is some better behavior for DrRacket in this situation.

**Comment by yjqww6** [comment]
It is enabled and limited, but doesn't work in RacketCS.
I think whether limit memory works is unimportant for such case. In my experience, when I open files in collects/racket/private, it would output
```
require: import cycle detected during module instantiation
Module Language: invalid language specification in: racket
```
But in collects/racket, it just keep busy.

**Comment by gfbee** [comment]
This happens back to 7.0 BC on macOS, with the would-you-like-to-increase-memory dialog IIRC : https://github.com/racket/drracket/issues/227 .

If you're trying to reproduce, that issue narrowed down the steps that still do trigger it on 7.7 cs (sans dialog). I have that open right now, with memory limit 2000MB, and it just got past 6000MB, and now the DrRacket window no longer appears when switching back to it from typing this.

**Comment by rfindler** [comment]
Thanks for calling that one to my attention. This one does appear to be a duplicate, exacerbated by the memory limit not kicking in under DrRacketCS.

**Comment by mflatt** [comment]
For some reason, I haven't been able to replicate the problem in DrRacket, so far.

@yjqww6 Just to confirm: a *snapshot* Racket CS (as opposed to v7.7) doesn't trigger the memory limit?

**Comment by yjqww6** [comment]
@mflatt I fonud the latest snapshot at https://www.cs.utah.edu/plt/snapshots/ is 20200629-4ad93bc, which is at 4ad9, the same as the one I used(20200627-4ad93bc).
I don't think there would be any difference, or should I waiting for next snapshot?

**Comment by samth** [comment]
If you got to https://ci-snapshots.racket-lang.org there are snapshots that are more recent, if they match your platform.

**Comment by mflatt** [comment]
But 20200627-4ad93bc is certainly new enough to confirm already — thanks!

**Comment by yjqww6** [comment]
Using snapshot in ci-snapshots.racket-lang.org, it now prints something like
```
module: current code inspector cannot redeclare module
  module name: "/home/qww6/racket/collects/racket/generator.rkt"
```
So this issue is mostly fixed, though I cannot confirm whether the memory limit problem is fixed too, since the memory usage is no longer keep growing.

**Comment by mflatt** [comment]
I was able to provoke bad behavior in DrRacket CS background expansion using

```
#lang racket

(define-syntax (m stx)
  (let loop ()
    (cons 1 (loop))))

(m 0)
```

This example goes worse in DrRacket CS compared to BC for a combination of reasons: unlike BC, CS didn't have a limit on the depth of context information recorded in a continuation mark set; and, background expansion is even worse than "Run" because background expansion doesn't have debugging enabled (which affects the representation of the continuation, and therefore how many frames are needed to trigger the memory limit).

I can change representations to get an improvement in the neighborhood of 5x, but the problem needs something more like a 50x improvement. The only solution I've found is to limit the amount of context information in a mark set. Limiting it in the same way as BC (where the limit was an accident of the implementation) is effective and practical.

**Comment by mflatt** [comment]
Commit c40a7ae2fcab8836649126dc730cb18c7c4aa47e improves CS behavior for unbounded expander memory use, so I think that covers the problems in this issue.
