### ISSUE TITLE
contract-out struct is inconsistent with struct-out

### ISSUE THREAD

**Issue by sorawee** [racket/racket#3277]
```
#lang racket

(module first racket
  (struct foo (x))
  (provide (contract-out (struct foo ([x boolean?])))))

(module second racket
  (require (only-in (submod ".." first) foo))
  (provide (contract-out (struct foo ([x boolean?])))))

(require 'second)

foo-x
```

evaluates to the accessor `foo-x`.

However, the corresponding `struct-out` fails:

```
#lang racket

(module first racket
  (struct foo (x))
  (provide (struct-out foo)))

(module second racket
  (require (only-in (submod ".." first) foo))
  (provide (struct-out foo)))

(require 'second)

foo-x

;; struct-out: no binding for structure-type identifier
;;   at: struct:foo
;;   in: (struct-out foo)
```

It's unclear which one has the desired behavior. Note that `struct-out` used to have the same behavior as `contract-out`, but it was changed to the current behavior in https://github.com/racket/racket/commit/096ec546a62b7f36b15ee086c389e59887a0250d

**Comment by rfindler** [comment]
Just based on the history, it looks like `struct-out` is right and `contract-out` is wrong.

**Comment by mflatt** [comment]
A note on the difference: A `provide` can only export bindings that are imported or defined. In the case of `struct-out`, if it did not complain about `struct:foo`, then `provide` would complain. In the case of `contract-out`, new bindings are created in the providing module by `contract-out` (to implement the contract), and those bindings can refer to things (via macro expansion) that are not explicitly imported. So, that's why `contract-out` can export more — because it's really exporting different.

**Comment by sorawee** [comment]
Since this seems to work as intended, I will close the issue.
