### ISSUE TITLE
->i flat contract projection

### ISSUE THREAD

**Issue by camoy** [racket/racket#3286]
This program succeeds even, though I would expect it to fail.

```rkt
#lang racket

(define ctc
  (make-flat-contract
   #:late-neg-projection
   (λ (b)
     (λ (x neg-party)
       (error 'ouch)))))

(define/contract (f x)
  (->i ([x any/c])
       [_ (x) ctc])
  42)

(f 10)
```

It turns out that for flat contracts, `->i` will use the first-order test to check instead of the projection. Since for flat contracts the first-order test passes iff the projection succeeds, this is usually alright. However, the projection may produce a different error message, and IMO is the correct behavior for this case.

Seemingly, this was introduced in 7056cd5 as a performance improvement. In [`un-dep/maybe-chaperone`](https://github.com/racket/racket/blob/master/racket/collects/racket/contract/private/arr-i.rkt#L1137) the short-circuit applies to anything that passes `procedure?`. I assume the intention was that this would be for predicates only, but flat contract structs also satisfy `procedure?`. A proposed fix would be to strengthen the first arm of the `cond` by also requiring the contract to not be a contract struct. Does this sound right?

cc @rfindler

**Comment by rfindler** [comment]
I think the use of `make-flat-contract` is buggy because it is using the default `#:first-order` argument and it should be using something like `(lambda (x) #f)` instead.

Generally adding checks like you're suggesting will affect performance so I think the right call here is to say that there is an invariant (about the relationship between the projection and `first-order`) that isn't checked but got violated.

Also I believe that, if no projection is supplied (but a `first-order` function is) then the contract system will make up a projection based on the first order function. I see that isn't documented, however.

**Comment by rfindler** [comment]
Oh, actually I see that the documentation does mention this, actually. Copy and pasting: "The projection arguments (late-neg-proj, proj, and val-first-proj) must be in sync with the test argument. In particular, if the test argument returns #f for some value, then the projections must raise a blame error for that value and if the test argument returns #t for some value, then the projection must not signal any blame for this value, unless there are higher-order interactions later. In other words, for flat contracts, the test and projection arguments must check the same predicate (which is why thee default projection uses the test argument directly)." 

Sorry for that confusion.

**Comment by camoy** [comment]
Sorry, yes you're right that the example is broken. But my concern is more with respect to the error messages. Even when we fix the definition of `ctc` as such:
```rkt
(define ctc
  (make-flat-contract
   #:first-order (λ (x) #f)
   #:late-neg-projection
   (λ (b)
     (λ (x neg-party)
       (raise-blame-error
        b x
        "some informative error message")))))
```
The error reported is: `promised: anonymous-chaperone-contract` instead of the more informative message I would've expected.

**Comment by rfindler** [comment]
Oh, I see now. Another alternative might be to change [these lines](https://github.com/racket/racket/blob/master/racket/collects/racket/contract/private/arr-i.rkt#L1143-L1144) to match [this line](https://github.com/racket/racket/blob/master/racket/collects/racket/contract/private/arr-i.rkt#L1151). How does that look?

**Comment by camoy** [comment]
I believe that would work, but wouldn't that require coercing `orig-ctc` first? That would seem to eliminate the performance gain of 7056cd5f2abfbf9d6ed75d5ba98789a6a0e92cc2 right?

**Comment by rfindler** [comment]
Well, I'm thinking that it would do it only when we know we're going to crash anyway. The performance gain happens when the contract doesn't fail (over and over and over and over :).

**Comment by camoy** [comment]
Ah, ok. That sounds good to me then!
