### ISSUE TITLE
Where are the include files for embedding Racket CS?

### ISSUE THREAD

**Issue by dotoscat** [racket/racket#3374]
Hello, I don't know whether this is a bug exactly. Im using Racket CS 7.8 in Windows 10 and I would like to embed it. [Following the docs](https://docs.racket-lang.org/inside/cs-embedding.html) I don't find the include files. In fact, the include directory is empty. The path is *C:\Program files\Racket\include*
I used this installer: racket-7.8-x86_64-win32-cs.exe

Thank you.

**Comment by mflatt** [comment]
It looks like this is a problem with the Windows cross-compilation build for Racket CS. We'll get it fixed for the next release.

Meanwhile, you could use a snapshot build from https://www.cs.utah.edu/plt/snapshots/ . (Note that CS is now the default from snapshots at that site.) That one has include files because it happens to be native-compiled instead of cross-compiled.
