### ISSUE TITLE
proxy-server test failure

### ISSUE THREAD

**Issue by samth** [racket/racket#3430]
In [this DrDr build](http://drdr.racket-lang.org/55431/) the [proxy-server test](http://drdr.racket-lang.org/55431/cs/pkgs/net-test/tests/net/http-proxy/proxy-server.rkt) started timing out, after previously taking ~3 seconds every time. I've replicated this behavior on my system, but unfortunately it also re-appears with Racket 7.8 on my laptop. Unfortunately, I can't find any changes on the DrDr machine that happened at that time.

cc @mflatt @jeapostrophe

**Comment by jeapostrophe** [comment]
It is good to know that things slowed down... but FWIW I think it is acceptable to change the timeout. We did it in the past, as it is pretty arbitrarily chosen.

**Comment by samth** [comment]
Sure, but it went from taking 3 seconds to 5 minutes, which isn't a reasonable variation.

**Comment by tim-brown** [comment]
It's been a long time...

q.com probably just changed a firewall policy to hold up incoming connections on unknown ports (9887) rather than reject them immediately. I'd say that was probably better practice on their part, but that's not really helpful for the racket build.

Looking at it, the hold up -- your 5 mins -- is probably in the `tcp-connect` at `tests/net/http-proxy/proxy-server.rkt` l.31

https://github.com/racket/racket/pull/1411/files#diff-91672191867034bf65fca41ce68aa1cc77cf6c97bf80cdbfff1f260e4e9305bbR31

I can think of 3 options
1. find another server and port that refuse a connection immediately, and reproduce the old q.com behaviour. Unless you "own" these, this is just moving the brittle behaviour elsewhere
2. wrap the `tcp-connect` in a timer to timeout after a polite length of time. It still has to cope with working servers, so choosing a timeout is well, going to require some art
3. provide your own `tcp-listen`er on `localhost` which rejects your advances

I don't think (1) has much merit.

(2) still puts you mercy of the owner of the service. Coming to think of it, it makes your build depend on an Internet connection too (although I suspect _that's_ worrying unduly).

For (2) and (3) -- I apologise, but I'm a bit time-starved at the moment and, to be honest, I'm not sure I know best practice any more for (if I ever did) for a timed-out `tcp-connect` or writing a `tcp-listen`er.

**Comment by samth** [comment]
Thanks for the detailed follow-up, after a long time. Given your comments on this, I'm inclined to just drop this test.
