### ISSUE TITLE
port->lines incorrectly handles CRLF that crosses 4K boundary

### ISSUE THREAD

**Issue by endobson** [racket/racket#3434]
**What version of Racket are you using?**
Racket v7.8.0.11 [cs]

**What program did you run?**
https://gist.github.com/endobson/300fd2db69016d2462a543df48461b69#file-line-feed-rkt

Body of the program included inline for readability.
```
#lang racket/base

(require racket/runtime-path
         racket/list
         racket/port)

(define-runtime-path good-file "line-feed-good.txt")
(define-runtime-path bad-file "line-feed-bad.txt")

(for ([file (list good-file bad-file)])
  (define lines (call-with-input-file file port->lines))
  (displayln (length lines))
  (write (drop lines 1360))
  (newline)
  (newline))
```

**What should have happened?**
The two files should have the same number of lines since the only difference is the character `4` on one of the lines.

Output:
```
1368
("0" "1" "2" "3" "4" "5" "6" "7")

1369
("0" "1" "2" "3" "" "5" "" "6" "7")
```

The bad file is explicitly constructed so that the CRLF is such that the CR is at index `#xFFF` and the LF is at index `#x1000`. I haven't tried minimizing (beyond reducing to a simple test case) to see if it is an issue at smaller boundaries.

**Comment by mflatt** [comment]
As you may suspect, the fast path (in Racket CS) that tries to use already buffered bytes goes wrong in 'any mode for line reading. When the buffer ends with a "\r" that will be continued by a "\n". In that case, the buffer matches "\r", but the fast path should give up and wait for the next character, instead of taking the "\r".
