### ISSUE TITLE
Incorrect printing by pretty-print

### ISSUE THREAD

**Issue by willghatch** [racket/racket#3439]
Here is a program that uses the `pretty-print` function with input that it doesn't print correctly.  In particular, it prints such that two symbols get joined as one symbol if the output is `read` back in.

```
#lang racket/base
(require racket/pretty racket/port)

;; The bug is that the s-exp is printed such that a-symbol is joined to the previous 
;; weird stuff symbol that has a newline because no space is printed between them.

;; It seems very dependent on the length of the “stuff” and that there is no space before it.
;; Also I haven't reproduced it without `begin` or with a different number of parens, but 
;; that's probably because it's sensitive to indentation depth and such.

(define weird-s-exp
  '((begin (((x something-fairly-long-so-pretty-print-uses-a-line-break-here-in-this-application-like-form
                '|
stuff|
                a-symbol)))))

)

(define-values (in out) (make-pipe))

(pretty-print weird-s-exp out 1)
(define read-back-pretty-print (read in))

(print weird-s-exp out 1)
(define read-back-print (read in))

;; Both should be true, but pretty-print did something wrong so it's false.
(equal? weird-s-exp read-back-pretty-print)
(equal? weird-s-exp read-back-print)

(pretty-print weird-s-exp (current-output-port) 1)

```

This bug is brought to you by Xsmith.  I've tried to minimize the example reasonably well, though it's still bigger than I would have liked.  But any change I try to make at this point seems to no longer show the problem.

**Comment by mflatt** [comment]
The `pretty-print` function inserts a newline when it's on column X and the thing it's about to print wants to be on column Y where Y < X.

By including a newline in a symbol, you set up the possibility that the next thing to be printed doesn't need a newline to start on the same column as just-printed thing. And the symbol has to otherwise have exactly the right length so that it ends at that column (otherwise spaces will be added or a newline will be inserted after all).
