### ISSUE TITLE
`foldl` of Racket has a bug!

### ISSUE THREAD

**Issue by AiziChen** [racket/racket#3482]
**What version of Racket are you using?**
e.g., 7.8 and lower [cs]

**What program did you run?**
> (foldl (lambda (x y) x) 0 '(1 2 3 4))

**What should have happened?**
Return to value `4`, right is `0`

**If you got an error message, please include it here.**
None

**Please include any other relevant details**
e.g., the operating system used or how you are running the code.
macOS & Windows, or Linux maybe.

**Comment by sorawee** [comment]
According to the [documentation](https://docs.racket-lang.org/reference/pairs.html?q=foldl#%28def._%28%28lib._racket%2Fprivate%2Flist..rkt%29._foldl%29%29), this is the expected behavior. See also https://stackoverflow.com/a/8780880/718349 which provides comparison of `foldl` and `foldr` in several languages.

**Comment by AiziChen** [comment]
thank you
