### ISSUE TITLE
Error saving  ... string is not a well-formed UTF-8 encoding string: #"@k\360""

### ISSUE THREAD

**Issue by vladimirtier** [racket/racket#3498]
What version of Racket are you using?
Version 7.9 
Windows 10

What should have happened?
 Saving after:
Save Defenition ...
Save Defenition as ..   
Save Other...

If you got an error message, please include it here.
Error saving
"There was an error saving D:\Muster\Aufg.rkt.
bytes->string/locale: string is not a well-formed UTF-8 encoding
  string: #"@k\360""

**Comment by mflatt** [comment]
Sorry for the delay here. (I missed the notification for some reason.)

This problem is most likely a result of a broken preferences file, which may be located at `AppData\Roaming\Racket\racket-prefs.rktd` in your home directory. Deleting that file will likely solve the problem.

Of course, a broken preferences file should not break DrRackket, and that problem has been fixed by fc53f2998c422dcbf7f49a754529c9949c69e0b7.

It's worrying that the preferences file was corrupted at all, but I think this immediate problem is solved for future releases. I'll close the issue, but please re-open if deleting the preferences file or using a snapshot from https://snapshot.racket-lang.org does not solve the problem.
