### ISSUE TITLE
DrRacket debugger problem?

### ISSUE THREAD

**Issue by jzhs** [racket/racket#3633]
Here's a file that runs in DrRacket but causes an error when I attempt to use debugger. Error message is 
"MAC: cannot use identifier tainted by macro transformation in: MAC".  
Note that the debug works if different punctuation is used (eg MAC:B rather than MAC.B)

Using DrRacket 7.9 on Win10

#lang racket

(define-syntax-rule (THUNK (name x ...) code ...)
  (define (name x ...)
    (let ([x x] ...)
      (λ () code ...))))

(THUNK (MAC)   12)
(THUNK (MAC.B) 21)

((MAC))
((MAC.B))

**Comment by gus-massa** [comment]
Minimized code
(Remember to add 4 spaces before code, so it's formatted nicely.)

    #lang racket

    (define-syntax-rule (THUNK (name) code)
      (define name
        (λ () code)))

    (THUNK (MAC) 12)
    (THUNK (MAC.B) 21)

    (MAC)
    (MAC.B)

I tried it, and I reproduced the error. 

It's very strange the relation of `MAC` and `MAC.B`. You can change they to `MAC` and `MAC.X` or you can change them to `X` and `X.YZ`, he part before the period of one identifier must be equal to the other identifier. 

I tried the obvious names to make the code prettier `F` and `G`, but then the error disappears.

**Comment by yjqww6** [comment]
Though the bug here should be a forgotten `disarm` in the debugger annotator, the "." behavior could be reproduced even without debugger:
```racket
#lang racket

(define x 1)

(define-syntax (g stx)
  (with-syntax ([t (syntax-protect #'x.a)])
    #'(syntax t)))

(g)
```
outputs
```
x: cannot use identifier tainted by macro transformation in: x
```

The error is raised from https://github.com/racket/racket/blob/08fa24304ebf80a21ade32e8e59bb51b27af1dae/racket/collects/racket/private/template.rkt#L407-L418

**Comment by rmculpepper** [comment]
Thanks for the bug report and the minimizations! This is an interesting bug.

The underlying issue is that the graphical debugger's annotator uses `syntax` in one place where it should use `quote-syntax` --- see `#'var` at https://github.com/racket/drracket/blob/6cda6a7b1738b0be624f96aba10c48b1e5adbe4d/drracket/gui-debugger/annotator.rkt#L204
That causes `var` (a protected identifier) to go through syntax template interpretation.

It doesn't make sense to put protected or tainted syntax in a `syntax` template, given that `syntax` expects to inspect the template and interpret some of its identifiers as pattern variables. And `syntax` must not disarm its templates, since `syntax` templates are not expressions and do not necessarily even represent expressions (or definitions, or other Racket forms). Some examples of protected templates currently work by accident:

    (define-syntax (t stx)
      (syntax-case stx ()
        [(_ tmpl) #`(syntax #,(syntax-protect #'tmpl))]))

    (t 3)          ;; works
    (t (2 1 #f))   ;; works
    (t a)          ;; works
    (t (a b c))    ;; works (?!)

On the other hand, the following fail:

    (let ([a 1]) (t (a b c))) ;; fails

    (define x 0)
    (t (x y z)) ;; fails

For backwards compatibility and consistency, the template code should probably be fixed to allow protected dotted identifiers. There are two possibilities: either check the dotted prefixes of a disarmed version of the identifier or skip the check for protected identifiers. I'm leaning towards skipping the check.

**Comment by rfindler** [comment]
I'm not sure if this should have been closed but the commit message closed it automatically. I'll leave it to others to decide to reopen. @rmculpepper ?
