### ISSUE TITLE
`raco pkg install <git repo>` doesn't look for `main` branch

### ISSUE THREAD

**Issue by mbutterick** [racket/racket#3672]
`main` is supplanting `master` as the default branch of Git repos. [The current code](https://github.com/racket/racket/blob/46a191df038244199f83f2bb1235beb8ca137f9a/racket/collects/net/git-checkout.rkt#L385) only looks for `master`, and fails even if `main` exists.

**Comment by mflatt** [comment]
I've changed `raco pkg` so that when a package reference does not specify a branch, it uses the default branch for a repo as reported by the server.

Unfortunately, this change will take a while (i.e., some number of release cycles) to percolate through the package infrastructure and the installations on Racketeers' machines. Using `#main` in the package reference will necessary for a while, yet.

**Comment by pmatos** [comment]
@mbutterick / @mflatt can this be closed?

**Comment by LiberalArtist** [comment]
Now that 8.1 and cff766ab84dcc5d9dc969930611e0b8c150bfaf6 are here, would it make sense for the package catalog server to add explicit branch names automatically? (Or perhaps just when talking to pre-8.1 clients?)

**Comment by mflatt** [comment]
I'm reluctant to add that kind of auto-conversion to the package server. It seems safest (and certainly simpler) to leave this in the hands of package authors.
