### ISSUE TITLE
Make mzscheme work when executed using a nonstandard argv[0]

### ISSUE THREAD

**Issue by iblech** [racket/racket#3685]
**What version of Racket are you using?**
8.0 of course :-) Congratulations on that release!

**What program did you run?**

    $ exec -a some-different-name ./mzscheme

**What should have happened?**
mzscheme should have started as normal, just as it does when invoked simply by `./mzscheme`.

**If you got an error message, please include it here.**
The start aborts:

    $ $ exec -a some-different-name ./mzscheme
    read failed to read all 23 bytes from file /tmp/mzscheme
    Aborted (core dumped)

**Please include any other relevant details**
The issue was noticed in NixOS (specifically [this issue](https://github.com/NixOS/nixpkgs/pull/113128)). There, the `mzscheme` binary is replaced by a wrapper shell script which first sets some environment variables, as NixOS takes care not to pollute the global /bin namespace (and their likes). As its final command, this wrapper shell script executes the true mzscheme binary (located in `/nix/store/.../.mzscheme-wrapped`) as follows:

    exec -a mzscheme /nix/store/.../.mzscheme-wrapped "$@"

It appears that the true binary attempts to read some bytes from `argv[0]`. This fails because `argv[0]` points to the wrapper shell script instead of the true binary.

A simple way out for us would be to patch the source so that the true binary no longer uses `argv[0]` for direction but instead uses a hardcoded path. Could you point us to the relevant point in the source?

**Comment by mflatt** [comment]
I think you're looking for this use of `argv[0]`:

https://github.com/racket/racket/blob/master/racket/src/cs/c/main.c#L434

**Comment by mflatt** [comment]
If it would help, I can imagine supporting a preprocessor definition to set the executable name at compile time. Instead of putting that in "main.c", probably it's better at the start of `extract_built_in_arguments` in "racket/src/start/cionfig.inc", and then it will apply to CS and BC the same.

I'm not clear on whether `raco exe` will cooperate right with this change, though. My guess is not, but I might be wrong, or maybe you already have something else in place for `raco exe`.

**Comment by mflatt** [comment]
By way of fac84630825fdb3780fcd7891fb50e637eb3f910, I've ended up paging back in how things work. Probably https://github.com/racket/racket/blob/master/racket/src/start/ustart.c is more relevant than "main.c".

I can see a way of making `mzscheme` and similar starters independent of `argv[0]` by using `/proc/self/exe`, which is what the main `racket` executable does to find embedded boot files. But a straightforward change would just replace `argv[0]` early on so that it would cancel out the use of `-a` with `exec`.

Can you tell me a little more about the intent of `exec -a`? Is it just to adjust the name of the executable that might be reflected back to the user (e.g., for an error message)? Or is it meant to adjust other things that might be computed relative to the executable — perhaps most simply, the path to executable itself as reported by `(find-exe)`, which various libraries use to start a new Racket process? (For "in place" configurations, Racket finds "collects" and packages relative to the executable, but I imagine that's not relevant in your configuration.)

**Comment by mflatt** [comment]
Commit 6f58ef5458686cde4e071321b473c42a6da9d420 solves the immediate problem of locating bytecode that is embedded in a launcher (to be included in v8.1).

There are various other things that replacing `argv[0]` affects, such as the location of the executable that the launcher is meant to start, but it's not clear which (if any) of those are meant to be affected by the use of `exec -a`. I'm open to making further changes, but I'll close this issue, since the immediate problem is addressed.
