### ISSUE TITLE
raco demod fails

### ISSUE THREAD

**Issue by pekeler** [racket/racket#3706]
**What version of Racket are you using?**
8.0 [cs]

**What program did you run?**
hello.rkt:
```Racket
#lang racket/base
(displayln "Hello World!")
```

`raco demod hello.rkt`

**If you got an error message, please include it here.**
```
linkl-exports: contract violation
  expected: linkl?
  given: #<linklet>
  in: the 1st argument of
      (-> linkl? (listof symbol?))
  contract from: 
      <pkgs>/zo-lib/compiler/zo-structs.rkt
  blaming: <pkgs>/compiler-lib/compiler/demodularizer/name.rkt
   (assuming the contract is correct)
  at: <pkgs>/zo-lib/compiler/zo-structs.rkt:61.21
  context...:
   /Applications/Racket v8.0/collects/racket/contract/private/blame.rkt:347:0: raise-blame-error
   /Applications/Racket v8.0/collects/racket/contract/private/arrow-val-first.rkt:486:18
   /Applications/Racket v8.0/share/pkgs/compiler-lib/compiler/demodularizer/name.rkt:9:0: select-names
   /Applications/Racket v8.0/share/pkgs/compiler-lib/compiler/demodularizer/main.rkt:22:0: demodularize
   body of "/Applications/Racket v8.0/share/pkgs/compiler-lib/compiler/demodularizer/batch.rkt"
   /Applications/Racket v8.0/collects/raco/raco.rkt:41:0
   body of "/Applications/Racket v8.0/collects/raco/raco.rkt"
   body of "/Applications/Racket v8.0/collects/raco/main.rkt"
```

**Please include any other relevant details**
macOS 11.2.2 (Intel)
see also #2226

**Comment by sorawee** [comment]
From Slack:

mflatt  1 month ago
I forgot about raco demod. It can’t work in its present form for CS, because it is based on reading and rewriting bytecode.

mflatt  1 month ago
I think it will have to be declared BC-only, at least.

mflatt  1 month ago
Longer term, I can imagine making it work in combination with compilation to machine-independent mode (as used by the distribution build process), and then recompiling demodularized form to machine code.

But yes, this should not result in an internal error like this.
