### ISSUE TITLE
Error installing Linux packages in CI for Solo Chez Build in 32 bits

### ISSUE THREAD

**Issue by gus-massa** [racket/racket#3730]
Since last week, there is an error in the 32 bits builds of Chez Scheme in the CI.

    The following packages have unmet dependencies:
    libssl-dev:i386 : Depends: libssl1.1:i386 (= 1.1.1-1ubuntu2.1~18.04.8) but it is not going to be installed

https://github.com/racket/racket/runs/2107521053?check_suite_focus=true#step:5:75

(I tried the obvious fix, but I got even more errors ;( .)

**Comment by pmatos** [comment]
@gus-massa thanks - I will look at this.

**Comment by pmatos** [comment]
This has been failing since March 10 and I didn't notice. My apologies.
It turns out I should've changed the default base image to ubuntu-20.04 as the 18.04 was deprecated awhile ago and I didn't. Github did remove the image March 10 and package installation fails on 20.04.

I should also be using a container there to avoid changes in the base VM image causing issues. Pushing a fix soon.

**Comment by pmatos** [comment]
Oh dear - fixing this opens another can of works, which is the fact that chez tests don't like to run inside a container. I have seen something like this before and I think the problem is not necessarily Chez but how github passes variable information into the container. Maybe for now we should run directly in the VM - I will test.
