### ISSUE TITLE
String blocks

### ISSUE THREAD

**Issue by jackfirth** [racket/racket#3796]
I'd like to be able to write multiline strings more easily. For example, instead of writing this `#lang racket` program:

```scheme
(define haiku
  "Haikus are easy\nBut sometimes they don't make sense\nRefrigerator\n")
```

I'd like to write this:

```scheme
(define haiku
  """
  Haikus are easy
  But sometimes they don't make sense
  Refrigerator
  """)
```

The alternatives today aren't great. They require I dedent things:

```scheme
(define haiku
  "Haikus are easy
But sometimes they don't make sense
Refrigerator
")

(define haiku
  #<<END
Haikus are easy
But sometimes they don't make sense
Refrigerator

END
)
```

Or use string concatenation:

```scheme
(define haiku
  (string-append "Haikus are easy\n" "But sometimes they don't make sense\n" "Refrigerator\n"))
```

Would it be feasible to add this to `#lang racket` in a backwards-compatible way? I could also write a meta-language for it like `at-exp`, but it seems like something that's useful enough to go in the base language.

**Comment by mflatt** [comment]
This does seem like a job for `at-exp`. Can you say more about why that's not the right thing?
```
#lang at-exp racket

@~a{
    Haikus are easy
    But sometimes they don't make sense
    Refrigerator
}
```
Using `~a` as above doesn't give you the trailing newline, but you could define another function/form that is like `~a` but adds a newline.

**Comment by jackfirth** [comment]
Reasons I don't usually reach for that:

- Requires escaping `@`, `{`, and `}`
- Requires using a meta-language
- Requires knowing about `~a` and how it works when combined with the @-reader (which I didn't know)
- Requires knowing that the @-reader dedents things correctly (which I also didn't know)

The discoverability issue is the main thing. I'd like something more straightforward and direct for this case. The full power of @-expressions seems like too much for `#lang racket`, but a much more limited string block syntax would be more reasonable to have in the language by default. Absent that though, I'll probably make do with @-expressions.

**Comment by rfindler** [comment]
I agree that at-expressions are this whole new thing that requires learning and that that's a lot to ask but in this case I side with @mflatt in that they are really an incredibly handy tool in the ole toolkit. @elibarzilay is a design genius.

**Comment by jackfirth** [comment]
Hmm. I also want an easy way to write a single-line string over multiple lines, and I can do either that or the multiline string block thing using @-expressions with different functions. So I think dedicated syntax for this is not the way to go. I'll think about it more.

**Comment by jackfirth** [comment]
So I tried the `@~a{}` approach and hit a problem: DrRacket breaks my strings when it reindents them. For instance, this:

```scheme
@~a{
 Foo
   Baz
 Bar
}
```

Reads as "Foo\n  Baz\nBar", which is what I want (sans trailing newline), but when I indent code with DrRacket it changes it to this:

```scheme
@~a{
 Foo
 Baz
 Bar
}
```

I'm trying to use this to write string literals in tests that check the printed representation of things, so the indentation is significant.

**Comment by rocketnia** [comment]
I think formatting a piece of text so that it looks nice in the code but still has predictable and precise output is a legitimately complex problem. Text libraries are complex the way time libraries are, and having to learn about special-purpose tools is pretty normal.

Many things make Unicode text hard, but a few things make *string literals* extra-hard on top of that: indentation, bracket style conventions, comments, escape sequences, and nested occurrences of string literals.

It sounds like your top concerns are:

* You want to do escaping only rarely. You indicate that `"""` is a rare enough delimiter for this purpose. Since you indicate that what you're quoting is *more code*, I'm guessing that the chances you'll end up needing to escape `"""` are nonzero but that you like the odds.
* On lines of code that are part of the string, you want some of the indentation to be mere whitespace surrounding the string's notation, but you also want some of the indentation to be a part of the quoted string contents. The design of `"..."` and `"#<<EOF...EOF` assume all the indentation is part of the string contents, and the tooling for reindenting `at-exp` `{...}` and `|{...}|` sections seems to currently assume that all the indentation is for formatting, but you want a mix of both.

I think `at-exp`'s `|{...}|` is close to the right choice for this. The delimiter `}|` is pretty rare, and most uses of `|{...}|` are for sample code blocks, which generally do need their indentation to be preserved. It's only the reindentation *tooling* that doesn't seem to handle this well.

If you'd like to put up with the tooling that exists today, then I think you can get pretty far with a macro wrapper around `"..."`:

```racket
(define-syntax dedent-according-to-last-lines-indentation
  ; Takes a literal string and transforms it by detending the whole
  ; string by whatever indentation there is on the last line.
  <...>)

(define haiku
  (dedent-according-to-last-lines-indentation
    "
    Haikus are easy
    But sometimes they don't make sense
    Refrigerator
    "))
```

Racket preserves indentation in `"..."`, but it just preserves a bit too much of it for your needs, and the macro wrapper makes up for that. Having string notations that preserve as much information as possible is handy this way, since macro wrappers can just filter it out.

**Comment by elibarzilay** [comment]
<img src="https://media.giphy.com/media/TuZ8v66TzGeYJW23as/giphy.gif" width="48"> Well...

(Sorry, this just begged for a long reply, maybe switch to email if you want to reply?)

> I think formatting a piece of text so that it looks nice in the code but still has predictable and precise output is a legitimately complex problem. Text libraries are complex [...]

I cannot agree more.  Even worse: the fact that *libraries* are complex is nothing compared to the actual string literals, which is almost always done as a quick afterthought (best witnessed by Python's approach of let's-add-an-(n+1)th-quotation-style, or the ascii soup you get if you nest JS string templates).

The @-expression syntax is something that I came up with was the result of trying many, *many* approaches before that, including some that [got left in Racket](https://docs.racket-lang.org/preprocessor/).  And of course they address your concerns very well (or at least IMO they do):


> Requires escaping @, {, and }

```
@string-append|{Look, ma, }@{, no escapes}|
```

or, if you prefer more python-like look:

```
@string-append|"""{Look, ma, }@{, no escapes}"""|
```

[

I'm generally very happy with that, with the only debatable decision of "reversing" some ascii decoration that you might use, and long-prefixing nested escapes:

* `@string-append|<<<{Blah}>>>|`
* `@string-append|"""{Look, ma, }@{, |"""@string-titlecase{one} escapes}"""|`

]

> Requires using a meta-language

Only in the same sense that `"` (or `"""`) are meta-languages.  I'd classify them more as "requires knowing some quotation syntax", which is really unavoidable.  (And scribble should be a far cry from bash-quotations, if you know about that swamp.)


> Requires knowing about ~a and how it works when combined with the @-reader (which I didn't know)

Whew...  Two things here: (1) the @-expr syntax is independent of *any* actual bindings.  It's just an alternative syntax for S-exprs.  And once you know how those work, the choice of what to do with the strings is up to you.  `~a` is often used only because it's a cheap & quick way to "append a bunch of stuffs, most of which are strings".  Other than that, there's no weird interaction between `~a` and the syntax.  (2) I usually dislike `~a` because it tends to look messy, so instead I'll do some quick definition for `str` or something like that.

> Requires knowing that the @-reader dedents things correctly

that was absolutely one of the main goals.  I can't stress enough how much I'm disgusted by unindented multi-line strings.  You should really look at the [text generation examples](https://docs.racket-lang.org/scribble-pp/)...

[In fact, just a few days ago I wrote this gem in a PR:

```
  const body = ((strs: TemplateStringsArray, ...xs: any) =>
      String.raw({ raw: strs.map(s => s.replace(/(^|\n) *\|/g, "$1")) }, ...xs)
    )`some
     |text
     |here`
```

because I couldn't stand what it was before.]

> The full power of @-expressions seems like too much for `#lang racket`

Again, the power is only in what you do with it.  In your case, it sounds like `(define s string-append)` and then `@...|"""{...}"""|` does everything you need.  (And just in case it wasn't clear, it's only a reader thing, so there's no runtime footprint, and not even a macro one.)

> ... easy way to write a single-line string over multiple lines,

```
@s{This is a very @;
   long string, partic@;
   ularly that last word}
```

> I can do either that or the multiline string block thing using @-expressions with different functions.

(I think that you're missing something if you're talking about requiring different *functions* for both cases.)

And yes, DrRacket support for reindentation is difficult...  I'm sure that patches would be welcomed :)

**Comment by elibarzilay** [comment]
Ooh, I forgot to add that if you're learning how to use it, then keep in mind that `'` is very useful -- since it's just a reader syntax, then you can see exactly what it's doing by quoting it.  For example:

```
> '@s{This is a very @;
      long string, partic@;
      ularly that last word}
```

**Comment by jackfirth** [comment]
What I wound up with is this:

```scheme
(define (line-string . parts)
  (string->immutable-string
   (string-trim (regexp-replace* #rx"\n+" (apply ~a parts) " ") #:repeat? #true)))


(define (block-string #:trailing-newline? [trailing-newline? #true] . parts)
  (define block (apply ~a parts))
  (define contains-non-whitespace?
    (for/or ([part (in-list parts)])
      (not (equal? part "\n"))))
  (string->immutable-string
   (if (and trailing-newline? contains-non-whitespace?) (string-append block "\n") block)))
```

And then my use cases look like this:

```scheme
;; Use case 1: multiline string literals with significant newlines
(define expected
  @block-string{
    (web-graph
      (web-link "http://example.org" 'stylesheet "/styles.css")
      (web-link "http://example.org" 'stylesheet "/fonts.css")
      (web-link "http://example.org" 'search "/opensearch.xml")
      (web-link "http://example.org" 'privacy-policy "/privacy-policy"))})
(check-equal? (~pretty graph #:columns 80) expected)

;; Use case 2: single-line string literals spread across multiple lines
;; Newlines replaced with spaces
(define error-message
  @line-string{
    A really bad error occurred. Just an awful, no good, truly
    terrible error that should never happen. Woe is you. Throw
    your hands up and curse the heavens above and machines below.})
```

These work correctly, but DrRacket doesn't indent them the way I want. I don't know if changing DrRacket to indent `#lang at-exp` files the way I've written them here would be backwards-compatible, or if it would have bad effects on Scribble docs. The indentation problem is a deal-breaker, so if changing that is infeasible then I'll have to figure something else out, likely along the lines of the macro @rocketnia suggested.

**Comment by jackfirth** [comment]
For context, this is how DrRacket wants to indent those two examples:

```scheme
;; Use case 1: multiline string literals with significant newlines
(define expected
  @block-string{
 (web-graph
 (web-link "http://example.org" 'stylesheet "/styles.css")
 (web-link "http://example.org" 'stylesheet "/fonts.css")
 (web-link "http://example.org" 'search "/opensearch.xml")
 (web-link "http://example.org" 'privacy-policy "/privacy-policy"))})
(check-equal? (~pretty graph #:columns 80) expected)

;; Use case 2: single-line string literals spread across multiple lines
;; Newlines replaced with spaces
(define error-message
  @line-string{
 A really bad error occurred. Just an awful, no good, truly
 terrible error that should never happen. Woe is you. Throw
 your hands up and curse the heavens above and machines below.})
```

**Comment by rfindler** [comment]
@jackfirth the indenter for @-expressions needs some work. A student produced it years ago and it has kind of limped along without a lot of love since then. I would love it if someone were to actually figure out what the right algorithm really is for indenting those things! Also related: the super useful meta-q keystroke needs help.

**Comment by elibarzilay** [comment]
If you're doing such games, then something else that can be relevant is that the syntax values that are generated for @-forms use a `scribble` properties to tell you how the arguments were provided, and also on string literals so you can tell when a `\n` was from a line split and when a bunch of spaces were from indentation.  You can use these to do these things only on newlines that appeared literally in the text part rather than from subexpressions.

And re indentation, there should be two separate pieces of functionality -- something like `M-q` can move text around, but in other case you don't want that since you care about the spaces and the newlines.  So reindenting

```
@foo{
A
  B
C}
```

might lead to

```
@foo{A B C}
```

in one case, and

```
@foo{
  A
    B
  C}
```

in another.  And on top of these, there is also latex-style uses like

```
blah blah @foo{blah
blah} blah
```

which complicates it further.

**Comment by jackfirth** [comment]
> And re indentation, there should be two separate pieces of functionality -- something like M-q can move text around, but in other case you don't want that since you care about the spaces and the newlines.

This is a problem. If there's two different reasonable ways to reindent something, and it's impossible to guess which one the user likely wants, then autoformatting tooling can't format it. I need something where it's unambiguous to tooling that I'm writing something that should be indented like a text block rather than LaTeX-style prose.

**Comment by rfindler** [comment]
@shhyou @jackfirth I think M-q and tab are the different keystrokes you're asking for?

Tab is normal reindent and M-q (a fantastic keystroke by the way, comes with Emacs) might be better called "reflow".

**Comment by shhyou** [comment]
I have in mind another rule that shifts the entire block of texts to correct nesting depth, but respects the relative indentation difference between the lines. This is what @aowens-21 and I have for pretty-printing test cases and what I've been doing when writing Verbatim latex code and using at-exp to write error messages:

1. A pretty-printing test case

```racket
(define my-let-expected.3
  @string-append{
 (my-let ([a 10]
          [b 5]
          [c (* 7
                3)])
   (+ a b c))
 })
```

2. LaTeX Verbatim code in Pollen

```racket
◊Verbatim[#:numbers "left" #:verbatim "true"]{
(define-id-with-ctc (-> concretize/c
                        (-> any/c any/c concretize/c)
                        any/c)
  concrete-sort  sort-with-ctc  bug  no-blame)

(define (date< d1 d2)
  (or (< (list-ref d1 0) (list-ref d2 0))
      (< (list-ref d1 1) (list-ref d2 1))
      (< (list-ref d1 2) (list-ref d2 2))))

(define (main list-of-dates)
  (define sorted-list (sort-with-ctc list-of-dates date<))
  ...)

}
```

3. Writing text-based error messages

```racket
         [else
          @list{
            An error occurred when running the test:
              got an error: @error-message
              when running the code:
                @(embed-pretty-write-code error-expr #:newline? #t)

          }]
```

I think this is a possible reindenting scenario that is different from tab and M-q.

**Comment by jackfirth** [comment]
> @shhyou @jackfirth I think M-q and tab are the different keystrokes you're asking for?
> 
> Tab is normal reindent and M-q (a fantastic keystroke by the way, comes with Emacs) might be better called "reflow".

Neither of them does the right thing for my use cases. Even if one of them did, that still wouldn't solve the problem of how an autoformatter is supposed to know which one to use on a given @-expression. I want VS Code to fix up my text blocks correctly on save automatically.

**Comment by elibarzilay** [comment]
> I need something where it's unambiguous to tooling that I'm writing something that should be indented like a text block rather than LaTeX-style prose.

There's just no way to do that, without knowing the intention of the binding *and* the preferred layout of the author, which essentially makes you claim that drracket should just avoid touching any text parts of @-expressions in the same way that it doesn't touch the contents of all kinds of strings (including a fictitious `"""` construct).  Even the sensible rule that [@shhyou suggested](https://github.com/racket/racket/issues/3796#issuecomment-825236322) (sensible since @-forms are designed to not change how they read if the indentation is changed consistently) breaks if you reindent

```
This is some text with some @bold{emphasized
part} that crosses a line.
```

to

```
This is some text with some @bold{emphasized
                                  part} that crosses a line.
```

The hopefully obvious conclusion that I hope you'll draw from this, is that what you seem to want is something that cannot happen.  And BTW, this is in no way a problem that is specific to @-forms -- it happens in plain code too.  For example, in my class people write code that looks like:

```
(test (run "{with {x 3}
              {* x 7}}")
      => 21)
```

and when they edit the code in the string, they usually end up with some badly indented code since they learn to blindly rely on their tools (drr or anything else) to "just make my code look good".

And the followup conclusion from this is that your "deal-breaker" of requiring tools that would know what you mean is something that would never happen and therefore not something that should be a deal-breaker.

(/rant on

This is part of a larger disease where I see students that ask for automatic tools that would properly layout their code, and I need to make the same point every semester: that removing the human author from the process of styling code is not possible (at least not without accepting some crappy code as a result).  You can see this problem in the futileness of deciding something minor like "function arguments should all fit on one line, or you must have newlines between all arguments, which breaks on something like

```
(draw-box x y
          w h
          color)
```

to even the common indentation style being broken by people who prefer a more "modern" indentation like

```
(with-output-to-string (λ ()
  (display something)))
```

I don't like how much people put themselves in the hand of such automated tools.  A few years ago I got a random reply to a PR about `scalafmt` that the goal of that project is not to make code look good, but instead it's indented that people use it as a save hook thing, which aims at removing all human factors out of the decision on how the code should look like.  It's also why I frown at statements like having partial/broken/etc tool support for some syntax being classified as a "deal breaker"...

/rant off)

**Comment by rocketnia** [comment]
If it's a dealbreaker for Jack, it's a dealbreaker for Jack. Jack's design makes sense to me as something that _could_ exist, and just as people might have different preferences about how to format that `draw-box` call, they can have different preferences about what autoformatters (if any) they run over their own code.

Personally, I've often found my code is far more maintainable for me when I format it in nonstandard ways. IDEs don't know what to do with my code, and since I consider this to be a dealbreaker, I rarely use IDEs. I probably wouldn't use an autoformatter for the same reason.

> and when they edit the code in the string, they usually end up with some badly indented code since they learn to blindly rely on their tools (drr or anything else) to "just make my code look good".

I was thinking about something similar here. Jack's use case is very close to being a string that contains an expression of code. If it were _just_ a string that contained an expression, then an IDE that could edit it and reindent it like code would arguably be even better than just preserving the indentation. Your students could use that kind of string literal to get the IDE behavior they want (which isn't to say that you'd encourage them to).

But in fact Jack's use case is slightly different: It's a _test for an autoformatter_, so a reindenter that normalized the indentation would change the semantics of the test. It's a kind of niche use case that doesn't have all the same design forces as other strings of code would have.

Still, what if the IDE could highlight that code? What if it could find matching parens? When an ecosystem has a lot of strings that contain code, the IDEs face some pressure to enhance those strings as well as they can (like tools that work with PHP and its emitted HTML snippets at the same time). I think there's a use for a string syntax that statically conveys to the language tooling, "This string contains code, but... { it's not paren-balanced / it's a `match` pattern rather than an expression / it has significant indentation / it has the C-style infix dot enabled / it's in language X }."

That's a lot of configuration to write around a string literal. That's where named aliases come in. If the string literal is surrounded by a call to a user-defined macro, then the tool can expand that call (e.g., as part of background expansion) to find out what the deal is with this particular string literal. The macro serves as a tag on the string that expands into a variety of tooling-hint syntax properties or whatnot.

Personally, I still find nonstandard indentation styles are essential to my purposes. To accommodate these, I would probably have quite a few configurations hidden behind macros. Ultimately, I think this habit of writing tooling-hint macros would develop into a whole tooling-hint stylesheet, something that would let me reconfigure the default behaviors for large numbers of syntactic constructs all at once without having to pepper my code with individual tooling hints. Maybe some of my stylesheet rules would only apply to certain subdirectories or (labeled) subexpressions of my code. Maybe I'd have one stylesheet rule that applied to `@bold{...}` expressions and a different one that applied to `@Verbatim{...}`.

Then, if someone else comes along and finds my choices completely unmaintainable, they can tweak the stylesheet. If some file in particular becomes really unmaintainable when they do this, then first they can ignore the far-off voice saying "welcome to my world," and then they can simply adjust the stylesheet rule so that it only applies to that one file.

In the long term, I think autoformatters have a lot of potential. I think there are just a number of hoops they need to jump through before before they can address all the factors at play in a language-oriented programming ecosystem. Some of these more ambitious possibilities may seem impossible, but that's only due to the particular place we're standing today.

**Comment by elibarzilay** [comment]
Yes, all of that makes perfect sense.  There are editors that rely on all kinds of hacks to get such customization -- either configuration files (with a directory hierarchy for different styles) or specific syntax hooks from the text (as emacs does for something like `mhtml-mode`).  Hooking the behavior on bindings (= macros) instead makes perfect sense, and it's an option that was raised several times in the past but nobody picked it up and implemented something...

**Comment by jackfirth** [comment]
> The hopefully obvious conclusion that I hope you'll draw from this, is that what you seem to want is something that cannot happen.
Yes. I brought it up after being asked why @-expressions didn't work for my use case. I don't think the problem is unsolvable with other notations, given that several languages actually do have syntax for these that plays nicely with autoformatters.

**Comment by jackfirth** [comment]
Also, for the `draw-box` example, I'd be fine with the "function arguments go on separate lines" formatting. My solution would be to change `draw-box` to work like this:

```scheme
(draw-box
  (point x y)
  (dimensions w h)
  color)
```

**Comment by elibarzilay** [comment]
> I don't think the problem is unsolvable with other notations

I don't see how you reach this conclusion, given that @-forms can be used in the basic literal-only way that you want; unless you're claiming that the *language* should be extended with a new syntactic `"""` form just so the *tool* could ignore it (which seems to me like an odd request).  (And "don't touch the quoted text" is by far the most common support I've seen for `"""`-like quotations.)

> My solution would be to change draw-box to work like this:

(Which won't work if it's not your function to change, or if you started with x/y then added a color, etc.)

**Comment by jackfirth** [comment]
Yes, by "other notations" I mean "other notations that could be added to the language", not "other notations that already exist today."

**Comment by elibarzilay** [comment]
So ... if that is indeed an argument to change the language just for the sake of tools, then (a) I'm very surprised, (b) I'd very strongly disagree, (c) I'll add it to my list of rants about how modern "coders" (not programmers) write code, reaching a point of pushing for language changes for tools, and (d) I'm guessing you'd be happier in mainstream/industrial language circles where the tooling emphasis is much stronger.

(But a+c are my subjective opinion, b is irrelevant, and d you'll dismiss as irrelevant, so I guess none of this would make any difference.)

**Comment by jackfirth** [comment]
Autoformatters are pervasive nowadays and many modern languages ship with standard ones out of the box. The [language server protocol](https://microsoft.github.io/language-server-protocol/) makes their integration with editors quite seamless too. I think dismissing their impact on language design is shortsighted. If Racket's manifesto is to internalize extra-linguistic mechanisms, then I think it follows that taking autoformatting tools into account when designing languages is a good idea.

As it stands, I don't think @-forms will work for my use case and I think the main reason for that is that they support nesting. I'm happy to explain what I mean by that further if you're curious, but I think the most productive thing for me to do is to just implement an alternative for my own use cases first.

**Comment by elibarzilay** [comment]
(Yes, I know about the LSP; the indented-text code snippet is from an internal tool that tests the tsserver.)

> If Racket's manifesto is to internalize extra-linguistic mechanisms

It is, and *that* is perfectly fine.  It's what we talked about earlier: having proper bindings is exactly the tool that can be used to internalize knowledge about how to indent a specific form.  The result is internalized because it's the library implementor that takes over the role of specifying how a binding should be indented rather than trying to infer that indentation from use.  That is exactly why a single generic `"""` fails (in that it will inherently depend on hacks or a uniform "don't touch the text" rule) whereas an actual binding will work properly.

> As it stands, I don't think @-forms will work for my use case and I think the main reason for that is that they support nesting.

You've never explained how this is a problem.  If you had a `"""`, you'd be free to write any textual content *except* for a possibly nested `"""` which would require escaping.  So if you're willing to do that (be careful with only a nested `"""`), then I don't see any technical difference between that and being careful not to use `"""` inside of a `@foo|"""{...}"""|`.

> I'm happy to explain what I mean by that further if you're curious

The question for you is in the last paragraph: how would an implementation of a `"""` make your use case better?  If the only answer you have is "DrRacket won't touch its contents", then I claim that this will be wasted effort that would be better spent at ... making DrRacket not touch @-forms by default, and (given more time) extending it by some per-binding information that would specify how it should touch the body for specific bindings.

---

[Time and time again I tell people that the best way to test if a quotation system is robust is to see how easy it is to use when you use it to document itself.  In this regard bash is a horrible disaster, as is HTML.  Python went down a similar route and ended up with a spaghetti of different quotation styles.  Dragging that mess to Racket would be unfortunate to say the least.  OTOH, by allowing you to customize the syntactic separator that @-forms use (similar to MIME separators), combined with the fact that you never need to produce concrete syntax from code (ie, macros allow you to rewrite sexprs to other sexprs rather than to the string representation of the result) you immediately avoid that mess.]

**Comment by elibarzilay** [comment]
BTW, to clarify:
1. Adding something like `"""` is extending the language, which (IMO) is not justified by a "it'll make tools better" argument.
2. Extending DrRacket to use binding information in a form that *already exists* is a very different thing, and in addition, will open the door to creating a binding that tells DrRacket "this binding expects a single string argument that contains code sexpers that should be indented" -- which further makes my point that there is more profit down that route than just handling @-forms.
