### ISSUE TITLE
Racket 8.0.900 BC is installing the directory "collects" to the wrong prefix

### ISSUE THREAD

**Issue by juanfra684** [racket/racket#3801]
I'm updating the OpenBSD port to the version 8.1 (working with 8.0.900 until you release the new stable version). I'm testing the port on OpenBSD Sparc64 with the **BC** variant. The same process worked fine with 8.0 on the same machine, however the version 8.0.900 is installing the collections to the wrong prefix:

```plain
With 8.0.900:
/usr/local/lib/racket/compiled/usr/local/share/racket/collects/acks/compiled/acks_rkt.dep

With 8.0:
/usr/local/share/racket/collects/acks/compiled/acks_rkt.dep
```
I don't know if the same problem happens with CS because this machine can't run the Chez version. I'm using the minimal tarball.

These are the configure args:
```plain
--enable-libffi
--enable-gracket
--enable-foreign
--enable-lt=/usr/bin/libtool
--disable-backtrace
--disable-docs
--disable-libs
--disable-shared
--enable-bcdefault
--disable-jit
--disable-places
--disable-futures
--prefix='/usr/local'
--sysconfdir='/etc'
--mandir='/usr/local/man'
--infodir='/usr/local/info'
--localstatedir='/var'
--disable-silent-rules
--disable-gtk-doc
```

**Comment by mflatt** [comment]
Thanks for trying out 8.0.900!

The change you see is intentional. It's aimed more at CS than BC, but the change the same to keep things simpler. You can get the old behavior back by configuring with `--enable-sharezo`.

The change is because ".zo" files for Racket CS are architecture-specific, so they belong in the "lib" area instead of the "share" area. Overall, you should see two "collect" directories: one in "/usr/local/share/" with ".rkt" files, and one in "/usr/local/lib/racket/" with ".zo" files and ".dep" files (because ".dep" files stick with ".zo" files).

**Comment by juanfra684** [comment]
Thanks for the quick reply!. I was worried because there was a hardcoded `/usr/local` in the middle of the paths.

Looks like racket is passing the usual tests, so I will keep the new default.
