### ISSUE TITLE
begin-encourage-inline changes program behavior

### ISSUE THREAD

**Issue by Aeva** [racket/racket#3817]
I'm using 8.0 cs on Windows 10.

I pushed a branch of my project that reproduces the issue.  [You can find it here](https://github.com/Aeva/sdf-machine/tree/inline-bug).  This shouldn't have any special dependencies beyond racket's standard library.  `Racket.exe sdfs.rkt` runs the program, and after a few seconds, a window should appear with a grayscale image in it.

However, when `sdfs.rkt` is ran unmodified from this branch, the program instead renders a black image.

If you remove the `begin-encourage-inline` on [this line](https://github.com/Aeva/sdf-machine/blob/inline-bug/sdfs.rkt#L43) and nothing else, then the image renders correctly.

The correct image looks like this:
![image](https://user-images.githubusercontent.com/768449/117248721-0ad99300-ae06-11eb-9b53-153b6433ea5b.png)

**Comment by mflatt** [comment]
Thanks for the report!

It looks like this is a bug in inlining for a function that uses `set!` on a variable that is local to the function body. The bug affects inlining via `begin-encourage-inline` as well as automatic cross-module inlining. I'll push a repair for that bug. (For your program, the workaround is to drop `begin-encourage-inline`, since inlining won't actually help much here.)

I notice another Racket CS bug exposed by your program, which is that `->fl` is supposed to work only on exact integers, but it's accepting any real number (while Racket BC's `->fl` accepts only exact integers). The `(->fl z)` in your program should be `(exact->inexact z)` or just `z`.
