### ISSUE TITLE
FFI bug passing argc&argv

### ISSUE THREAD

**Issue by mrmathematica** [racket/racket#3825]
I compiled a simple dynamic library from C code:

```
#include<stdio.h>
int test(int argc,char** argv)
{
    printf("%d\n",argc);
    for(int i=0;i<argc;i++)
    {
        printf("%s\n",argv[i]);
    }
	return 0;
}
```
and calling it from Racket by

```
(define test
  (get-ffi-obj 'test lib
               (_fun args ::
                     (_int = (add1 (length args)))
                     ((_list i _string/locale) = (cons "racket" args))
                     -> _bool)))
```

With Racket 7.9 cs on Linux (installed from binary), all seems good:

```
> (test)
1
racket
#f
```

With Racket 8.1 cs on Linux (installed from binary), no string on C side:

```
> (test "abc")
2


#f
```

**Comment by mflatt** [comment]
This is a limitation of CS that should have triggered an error instead of quietly passing a useless pointer to the foreign function. The limitation is that a pointer to non-atomic memory cannot usefully be passed to foreign functions, because GCable pointers have offsets that make them nonsensical to foreign code.

The general foreign-call path includes a check and error when there's an attempt to pass non-atomic memory for a foreign function, but that check got lost in the implementation of the common-case fast path.

The limitation is documented with `malloc`, but that's not at all obvious if you're starting from something like `_list`, so I'll also improve the documentation.

**Comment by mflatt** [comment]
Given the limitation in CS against passing non-atomic memory, passing an array of strings is going to be an especially painful task. Having a new `ffi/unsafe/string-list` library to provide `_string-list`, `_bytes-list`, etc., seems like a good idea.

**Comment by mflatt** [comment]
See also jeapostrophe/pict3d#25. Maybe there's room to improve `_list` and `_vector` after all, and then `ffi/unsafe/string-list` is not needed. So, don't get attached to the new library just yet.
