### ISSUE TITLE
custodian registration prevents finalizer from running

### ISSUE THREAD

**Issue by rmculpepper** [racket/racket#3841]
On Racket CS, registering an object with a custodian (even with `#:ordered? #t`) seems to prevent a separate finalizer from running. Here is an example program:

    #lang racket/base
    (require ffi/unsafe
             ffi/unsafe/custodian)

    (define counter 0)

    (define (make-thing)
      (define v (make-vector 10))
      (register-finalizer v (lambda (v) (set! counter (add1 counter))))
      (register-custodian-shutdown v void #:ordered? #t)
      v)

    (for ([i 1000])
      (make-thing))

    counter
    (for ([i 10])
      (sleep 0.01)
      (collect-garbage))
    counter ;; expected: 1000

On Racket CS 8.1, the program prints `0 0`; no finalizers ran.
On Racket BC 8.1, it prints `0 1000` (as expected).

A similar program using `register-finalizer-and-custodian-shutdown` prints `0 1000` as expected on both Racket CS and Racket BC, but `register-finalizer-and-custodian-shutdown` does not allow other operations (eg, `disconnect`) to remove the custodian registration.

Related to #3839.

**Comment by mflatt** [comment]
Swapping the order of `register-custodian-shutdown` and `register-finalizer` (using `#:ordered? #t`) changes the behavior to the expected one.

The underlying problem is that there are separate will executors in the CS implementation, and a non-`#:weak?` custodian converts its weak reference to a strong reference through a will executor. The theory behind that implementation was that any custodian registration should happen before a value is released to the wild, so it would be first, and that's ok... but that assumption doesn't hold in your example. The solution here may be to document that constraint and note its implication for  combining custodians and finalizers.

**Comment by rmculpepper** [comment]
Thanks, swapping the order does seem to fix the issue.

Based on your clarification, it sounds like the sentence "The value `v` is always weakly held by the custodian..." is now wrong.

I'm also worried about the advice later in the docs to run the finalizer in atomic mode. Since the finalizer does not start in atomic mode, it seems that there would always be a chance that the finalizer could be invoked and then suspended before it is able to enter atomic mode. IIUC, the docs should warn that custodian shutdown might be invoked concurrently with a finalizer and recommend that they cooperate to make their effects atomic and (probably) idempotent (eg with a shared `done?` variable).

In addition to clarifying the documentation, maybe we should add a success continuation argument to `register-finalizer-and-custodian-shutdown` that gets something that can cancel the custodian registration. It could get the registration itself, or it could get a thunk that cancels the registration and also sets the `done?` variable so the finalizer is also no-op.

**Comment by mflatt** [comment]
Yes, those seem like the right corrections and improvements.
