### ISSUE TITLE
Snapshot builds on Windows don't launch correctly from WSL2 

### ISSUE THREAD

**Issue by plane** [racket/racket#3867]
**What version of Racket are you using?**
8.1.0.6--2021-06-02(f31c717/a) [cs].

**What is the problem?**
Snapshot builds can't find `racket/init` if I launch them from WSL2, unless I `cd` to the installation directory before launching.

**Details**
This works fine, in `bash` under WSL2:

```
crystal@wings:/c/Program Files/Racket-8.1.0.6$ ./Racket.exe -e '(current-library-collection-paths)'
'(#<path:C:\Users\plane\AppData\Roaming\Racket\snapshot\collects>
  #<path:C:\Program Files\Racket-8.1.0.6\collects\>)
```

But it doesn't work if I do the same thing from outside the Racket directory:

```
crystal@wings:/c/Program Files$ ./Racket-8.1.0.6/Racket.exe -e '(current-library-collection-paths)'
standard-module-name-resolver: collection not found
  for module path: (lib "racket/init")
  collection: "racket"
  in collection directories:
   C:\Users\plane\AppData\Roaming\Racket\8.1.0.6\collects
```

**Additional info**
It works fine from `cmd` or `powershell`, so it's some kind of problem with WSL2:

```
PS C:\Program Files> .\Racket-8.1.0.6\racket.exe -e '(current-library-collection-paths)'
'(#<path:C:\Users\plane\AppData\Roaming\Racket\snapshot\collects>
  #<path:C:\Program Files\Racket-8.1.0.6\collects\>)
```

It also works fine from `bash` with non-snapshot builds:

```
crystal@wings:/c/Program Files$ racket/Racket.exe -e '(current-library-collection-paths)'
'(#<path:C:\Users\plane\AppData\Roaming\Racket\8.1-bc\collects>
  #<path:C:\Program Files\racket\collects>)
```

This makes it a little bit difficult for me to test the Windows snapshot builds, because I can't use them the same way I normally use Racket.

**Comment by mflatt** [comment]
It looks like the problem is that WSL2 passes just `"Racket.exe"` as `argv[0]` to a Windows program that it runs. (Well, Windows doesn't actually have `argv[0]`, but let's assume the conventional parsing of Windows command lines.) As a result, Racket's attempt to locate "collects" relative to `argv[0]` (taking into account the current directory and `PATH` setting) does not work.

This problem doesn't happen with a release build, which uses MinGW, because `argv[0]` is effectively replaced with the result of `GetModuleFileNameW` in that build mode. Replacing that way loses information included in the command line, but changing the MSVC to do the same is more consistent and avoids this problem, so I'll try that change.
