### ISSUE TITLE
list-box% right click selection bug on MacOS

### ISSUE THREAD

**Issue by eddierucker** [racket/racket#3871]
**What version of Racket are you using?**
Welcome to DrRacket, version 8.1.0.6--2021-06-07(-/f) [cs].

**What program did you run?**
#lang racket/gui

(define f (new frame%
               [label "Test"]
               [width 400]
               [height 200]))

(define lb (new list-box%
                [label "Choose"]
                [choices '("A" "B" "C")]
                [parent f]
                [callback (lambda (c e)
                            (when (send e get-event-type)
                              (writeln (send c get-select))))]))

(send f show #t)

;; 1) Right-click on a selection
;; 2) Left-click on any selection

**What should have happened?**

The program should write the index of the clicked item with eight mouse button.

**If you got an error message, please include it here.**

No error message. Sometimes goes into an infinite loop eating memory like issue #3832 on windows.

**Please include any other relevant details**

I am running this on a Mac mini using the M1 processor with 16GB of memory. The OS is Big Sur. This error does not occur on Linux nor on Windows.

Steps to cause the bug:
1) Right-click a selection. No index is printed.
2) Left-click another select. Goes into an infinite loop eating memory.

**Comment by mflatt** [comment]
I haven't yet been able to replicate this problem. A right click has no effect, as you report, but that seems to be generally true for list boxes on Mac OS. When I left-click afterward, the click registers as it should.

I had to change `get-select` to `get-selection` above, but I don't think that's the issue, since the error reports normally with the wrong method name.

I tried in within DrRacket and running via `racket` on the command line. Any thoughts on what I might need to do differently?

**Comment by eddierucker** [comment]
Hi I just tried it again. It worked the first time but then I right clicked a few times in quick succession and boom! It infinitely loops with the following from the terminal:

exception raised by error display handler: internal error: tried to deschedule a descheduled thread; original exception raised: exception raised by exception handler: internal error: tried to deschedule a descheduled thread; original exception raised: internal error: tried to deschedule a descheduled thread



Eddie Rucker

Director of Institutional Research and Computer Programming
Blue Mountain College

***@***.******@***.***>
1.662.685.4771 x125

On Jun 17, 2021, at 2:53 PM, Matthew Flatt ***@***.******@***.***>> wrote:



I haven't yet been able to replicate this problem. A right click has no effect, as you report, but that seems to be generally true for list boxes on Mac OS. When I left-click afterward, the click registers as it should.

I had to change get-select to get-selection above, but I don't think that's the issue, since the error reports normally with the wrong method name.

I tried in within DrRacket and running via racket on the command line. Any thoughts on what I might need to do differently?

**Comment by eddierucker** [comment]
Oh yes. I had to make the change from get-select to get-selection.

Eddie Rucker

Director of Institutional Research and Computer Programming
Blue Mountain College

***@***.******@***.***>
1.662.685.4771 x125

On Jun 17, 2021, at 2:53 PM, Matthew Flatt ***@***.******@***.***>> wrote:



I haven't yet been able to replicate this problem. A right click has no effect, as you report, but that seems to be generally true for list boxes on Mac OS. When I left-click afterward, the click registers as it should.

I had to change get-select to get-selection above, but I don't think that's the issue, since the error reports normally with the wrong method name.

I tried in within DrRacket and running via racket on the command line. Any thoughts on what I might need to do differently?

**Comment by eddierucker** [comment]
I was using the right-mouse click to make a context menu popup. In my original program that worked on Linux and Windows I created the context menu  by overriding the list-box% and then pausing the popup a little so that the row would be selected first. I just assumed it should work on MacOS. By the way, this is the segment from the textbook management program I wrote.

(define ui:popup (new popup-menu%))
  (define ui:popup-edit
    (new menu-item%
         [label "Edit"]
         [parent ui:popup]
         [callback edit-book]))
  (define ui:popup-instructor
    (new menu-item%
         [label "Instructor"]
         [parent ui:popup]
         [callback change-instructor]))
  (define ui:popup-delete
    (new menu-item%
         [label "Delete"]
         [parent ui:popup]
         [callback delete-book]))


  (define ui:book-list
    (new (class list-box%
           (define/override (on-subwindow-event receiver event)
             (when (eq? (send event get-event-type) 'right-down)
               (new timer%
                    [notify-callback
                     (lambda ()
                       (send this popup-menu ui:popup
                             (send event get-x)
                             (send event get-y)))]
                    [interval 100]
                    [just-once? #t])
               #t)
             #f)
           (super-new))
         [parent ui:frame]
         [label #f]
         [choices null]
         [style '(single column-headers clickable-headers)]
         [columns '("Course" "Course Name" "Instructor" "Book Title" "ISBN" "Cost")]
         [callback
          (lambda (c e)
            (case (send e get-event-type)
              [(list-box-column) ; sort by column clicked.
               (update-ui:book-list (send e get-column))]
              [(list-box)
               (send ui:menu-item-edit enable #t)
               (send ui:menu-item-delete enable #t)
               (send ui:menu-item-instructor enable #t)]
              [(list-box-dclick)
               (edit-book c e)]))]))

Eddie Rucker

Director of Institutional Research and Computer Programming
Blue Mountain College

***@***.******@***.***>
1.662.685.4771 x125

On Jun 17, 2021, at 2:53 PM, Matthew Flatt ***@***.******@***.***>> wrote:



I haven't yet been able to replicate this problem. A right click has no effect, as you report, but that seems to be generally true for list boxes on Mac OS. When I left-click afterward, the click registers as it should.

I had to change get-select to get-selection above, but I don't think that's the issue, since the error reports normally with the wrong method name.

I tried in within DrRacket and running via racket on the command line. Any thoughts on what I might need to do differently?

**Comment by mflatt** [comment]
I was able to crash in v8.1 by right-clicking past the end of the list, but v8.1.0.7 doesn't crash that way. Also, the crash in v8.1 is in the vicinity of changes made by Bogdan with https://github.com/racket/gui/commit/f23bd102340e751b52f71870be8f1bb66b136773.

So, maybe Bodgan fixed the problem as a side effect of his changes. Does a snapshot build (from the Utah site, since it looks like Northwestern is still building) behave any differently for you?

**Comment by eddierucker** [comment]
Indeed, the crashes are no more with the latest snapshot. 

Since right-clicks don’t trigger a selection from a list-box% on MacOs, is it possible implement context menus?

**Comment by mflatt** [comment]
It looks like contextual menus for list boxes on Mac OS are normally implemented through direct support in the underlying NSTableView class. Of course, Racket's GUI binding doesn't expose that.

Contextual menus on Mac OS are normally accessed by control-clicking instead of right-clicking. (I don't have a two-button mouse on my laptop, and I had to go find one  to try the program.) Control-clicking turns out to work as expected, because `rackt/gui` reports a control-left-click as a right-click, so you could leave it at that.

Otherwise, my only workable idea: Using the `get-first-visible-item` and `number-of-visible-items` methods, you could map the right-click event's `y` value to a row — at least approximately, because there's no guaranteed that the list height matches an integer count of rows — and select the row to implement the click yourself.

**Comment by eddierucker** [comment]
I didn’t know about the control-left-click as I am new to MacOS. Thanks! I will leave it at that since that is the simplest solution.

Since I haven’t had anymore crashes with the latest builds on any of my programs that use right-mouse clicks, I think this ticket can be closed.

Eddie Rucker

Director of Institutional Research and Computer Programming
Blue Mountain College
