### ISSUE TITLE
call-with-limits + eval + racket/gui cause program to hang up

### ISSUE THREAD

**Issue by capfredf** [racket/racket#3873]
**What version of Racket are you using?**
8.0 or later [cs]

**What program did you run?**
```racket
#lang racket/base

(require racket/sandbox)
(call-with-limits 20 500
                  (lambda () (eval '(begin (module a racket/gui
                                             (define x (make-object bitmap% 100 100))
                                             (provide x))
                                           (require 'a)
                                           x)
                                   (make-base-namespace))))

(displayln "it is over")
```

**What should have happened?**
the program should have exited. 

**If you got an error message, please include it here.**
no error messages. Th program will print "it is over" but won't terminate. 

**Please include any other relevant details**
I have tried running this program on macOS 10.14.16 and ubuntu 18.04. This issue only happens on my mac.

**Comment by mflatt** [comment]
Here's a similar but simpler variant:
```
#lang racket/base

(define es #f)
 
(thread-wait
 (thread
  (lambda ()
    (set! es ((dynamic-require 'racket/gui 'current-eventspace))))))

(displayln "it is over")

(sync es)
```

The `sync` tends not to return on Mac OS, because the eventspace still has events queued, and the eventspace's handler thread is not running events. On other platforms, there probably no events queued on startup.

In your sandbox example, it boils down to the same, where the ending `sync` is because an executable yield handler is installed to `yield` on the eventspace — but in a thread that turns out not to be the handler thread, so `yield` is the same as `sync`. In that case, the mismatch between threads happens due to the way `call-with-limits` runs a thunk in a thread and copies out changed parameter values (including `executable-yield-handler`) from the thunk's thread to the original thread.

I'm not sure what should be improved here, if anything. We could make some adjustments to `yield` or to the executable yield handler, but the eventspace is really in a permanently paused state (its handler thread has terminated) because of the unusual and arguably broken way that it was instantiated. For example, if `call-with-limits` is used a second time with the same expression, it will fail with an error about `racket/gui` being instantiated a second time, and there's not really a way around that. So, this might be a "don't do that" case, but I'll think about it more.

**Comment by mflatt** [comment]
After thinking about this more, I don't think there's a good change to make.

Trying to detect when a handler thread has terminated does not really make `sync` on an eventspace in a non-handler behave nicely; it currently doesn't wait, for example, if the event queue is empty but the handler thread is running handling an event. Another idea was to not set `executable-yield-handler` in a non-mail thread, but there are patterns where running `racket/gui` in a non-main thread could work.

There are likely more problems with the original pattern here, and so "don't do that" seems like the most effective conclusion.

**Comment by sorawee** [comment]
@mflatt is there a written caveat somewhere in the documentation?

**Comment by mflatt** [comment]
I see that `call-with-limits` doesn't explain that the thunk is run in a new thread and how it shuffles parameter values, so I've now added that information.

I'm not sure what else to add. The combination of `call-with-limits` and `racket/gui` seems too specific to mention directly.

**Comment by samth** [comment]
If the caveat is that "programs using `racket/gui` don't terminate successfully when run with `call-with-limits` that definitely seems worth mentioning directly, and describing what to do instead.

Am I correct that the solution is to instantiate `racket/gui` outside the sandbox, attach it, and then evaluate the module? Describing that pattern seems worthwhile.

**Comment by mflatt** [comment]
The `call-with-limits` function is not a sandbox, although it's a piece used in the implementation of sandboxes. There's no namespace inherently involved with `call-with-limits`, so there's nothing about attaching that particularly makes sense in the context of that function. Just starting `racket/gui` outside of `call-with-limits` doesn't inherently solve all problems interacting with `racket/gui`, because `call-with-limits` creates a thread, and that creates other considerations with eventspaces and event handling. The `make-evaluator` function for sandboxes, meanwhile, provides specific support for cooperating with `racket/gui`.

**Comment by rfindler** [comment]
Is there a place in the current documentation where one might look to try to understand the threading issues surrounding racket/gui? (I didn't find one when I looked just now.)

**Comment by mflatt** [comment]
There are two sections with "threads" in the title in the `racket/gui` manual. The first one could use more caveats and explanation. I don't have good ideas on how to make them more findable.
