### ISSUE TITLE
`raco test .` can be very slow

### ISSUE THREAD

**Issue by default-kramer** [racket/racket#4085]
**Is your feature request related to a problem? Please describe.**
If you have a bunch of source files in a directory tree and run `raco test .` it can take a long time to complete. I found that running raco make prior to raco test causes both to finish much faster than raco test alone. My hypothesis is that raco test is not saving and reusing compiled code. Every time your project does `(require "another-file.rkt")` raco test will re-compile another-file.rkt and then discard the compiled code.

Using Git Bash for Windows, I can run `raco make **/*.rkt` to compile an entire directory tree. But using cmd.exe I don't know a way to accomplish the same thing.

(It took me this long to notice this because for a long time `raco setup` was compiling the code for me.)

**Describe the solution you'd like**
From a beginner-friendliness standpoint, it seems like the default behavior of raco test should be to save and reuse compiled code. A switch could be added to keep the existing behavior.

**Describe alternatives you've considered**
If we don't want to change the default behavior, even adding a switch like `raco test -fast .` would be nice. Then I wouldn't have to know/remember that `raco make` is the answer.

**Do you want to contribute to this feature**
I'm certainly willing to attempt the code change, if desired.

**Comment by jasonhemann** [comment]
> But using cmd.exe I don't know a way to accomplish the same thing.

Resolved, but, I'm going to list a couple of other alternatives for someone else who comes along with the same issue. 

You have the location of `raco.exe` listed in the `%PATH%` environment variable, so your shell knows where to find `raco.exe`. So that is not a problem. I presume that working with Powershell is not an option for your use case, correct? I believe that understands `cmd` commands and file globbing and AFAIK comes standard with Windows n (n >= 7). I believe that would solve this for you. 

AFAIK, you are correct that the `cmd.exe` shell does not have built-in support for globbing expansion. S/O has [a useful thread on the Windows workarounds](https://superuser.com/questions/460598/is-there-any-way-to-get-the-windows-cmd-shell-to-expand-wildcard-paths).

**Comment by default-kramer** [comment]
Looks awesome, thanks @mflatt !

@jasonhemann Yes, I probably just need to commit to Powershell. Having 3 different shells (cmd, powershell, and git bash) means that I haven't gotten good with any of them.
