### ISSUE TITLE
Performance regression with Racket 8.3

### ISSUE THREAD

**Issue by ericonr** [racket/racket#4098]
**What version of Racket are you using?**

8.3, chez-scheme

**What program did you run?**

https://github.com/ericonr/adventofcode/blob/main/2021/day15/p.rkt

Run as `racket p.rkt < test4.txt` (with `test4.txt` from the same directory).

**What should have happened?**

With Racket 7.7, it ran in ~5 seconds. With Racket 8.3, it runs in more than 2 minutes.

**Please include any other relevant details**

I am on Void Linux.

I'm learning Racket as I go through this year's Advent of Code, so I didn't know where exactly to flag this issue. I would appreciate help for explaining it and possibly coming up with a minimal example.

The bulk of the runtime, per `(time )`, seems to be in running `(dijkstra)`: `cpu time: 103830 real time: 104227 gc time: 651`

**Comment by mflatt** [comment]
Thanks for the report!

It looks like the problem is poor behavior from the hashing function on pairs of small numbers (where the graph representation uses a hash table). Repairing the hash function makes the example take 2.5s on my machine instead of 73s. I'll perform some more experiments before pushing an update to the hash function, though.

If you need a workaround, use `vector` instead of `cons` to form a node.

**Comment by ericonr** [comment]
Thank you for the quick fix and workaround!

In case the information matters, using a `vector` decreased runtime to 16 seconds. Still not as fast as could be, but definitely way faster :)

Happy holidays!
