### ISSUE TITLE
memory use grows without bound; possibly related to `(send dc draw-bitmap ...)`

### ISSUE THREAD

**Issue by dalev** [racket/racket#4161]
**What version of Racket are you using?**
8.4 [cs] on macos 12.2.1, M1 hardware

**What program did you run?**
I ran the following program from a terminal:

https://gist.github.com/dalev/1e664789f5758c3abd083ed5d55d47f3

(It's a stripped-down version of a little animation I was building.)

**What should have happened?**
I expected this program to run in constant space.  Instead, memory usage increases as the program runs.  I measured using `top`, macos `Activity Monitor`, and also using racket's `current-memory-use` and `dump-memory-stats`.

**If you got an error message, please include it here.**
The program invokes `(dump-memory-stats)` several times, see this file attachment:  [memory-dump.txt](https://github.com/racket/racket/files/8057696/memory-dump.txt).  The `phantom` category sticks out (thought I don't really know what that is).

**Please include any other relevant details**
Possibly related to #3459 and #3832?

A couple observations:  
- if I replace the `draw-bitmap` call on line 50 with `(void)`, the memory usage remains low.
- the rate at which memory grows appears to be proportional to the bitmap's size (try tweaking the initial frame size on line 23).
- the linked program automatically stops after 30 seconds; I've watched it for longer periods, and the memory usage does not plateau for as long as I've let it run (several minutes at least).

**Comment by mflatt** [comment]
The memory growth is a result of using `'transparent` and `'no-autoclear` and the absence of a `(send dc clear)` in `on-paint`.

The `'transparent` part triggers a representation of drawing into the bitmap that is based on `record-dc%`, which means keeping a list of drawing commands instead of, say, a rending of those commands into a bitmap. There's a limit on the recording to 1024 actions, and it turns out that memory use for the program will plateau at a little under 1024 phantom objects. Each phantom object corresponds to a copy of the drawn bitmap.

The `'no-autoclear` part is needed to avoid an automatic clearing action that would reset the recorded drawing commands every time. The absence of `(send dc clear)` in `on-paint` is important for the same reason.

Internally, the recorded commands are always backed up by a bitmap, and the recording is just a heuristic. The idea was that recording commands and replaying them could be faster than a bitmap blit if the recorded commands touch many fewer pixels than the bitmap would. I don't know whether that really works out or whether 1024 is the right threshold, and I can't remember how I picked the it. At minimum, it seems like the heuristic should be adjusted to stop recording if a large bitmap is drawn.

**Comment by dalev** [comment]
Thank you!  Tbh, I am not sure why I chose that combination of styles -- I suspect I copy/pasted it from somewhere and gave it zero thought :(  Removing either or both of those styles keeps the memory usage pretty flat.

Fwiw, I'm not sure why `(send dc clear)` is relevant?  If I add that just before the `draw-bitmap` call, the memory use still steadily increases.  (Is `clear` just recorded into the `record-dc%` instead of immediately clearing the recorded list of actions?)

In any case, my immediate issue is resolved by not using this combo of styles, so closing the issue.  Thanks again!
