### ISSUE TITLE
read is blocking unnecessarily, when `read-line` isn't

### ISSUE THREAD

**Issue by Metaxal** [racket/racket#4184]
**What version of Racket are you using?**
Ubuntu 20.04LTS, Racket v8.4.0.3 [cs]

**What program did you run?**
https://gist.github.com/Metaxal/def826defa710617a16ef5d6c3f5f7dc#file-server-worker-threads-rkt

**What should have happened?**

With `(with-input-from-string (read-line) read)` (line 51 is commented out, and line 52 is uncommented) the program runs fine and fast on a machine with at least 4 cores.

With `read` (line 51 is uncommented and line 52 is commented out) the program runs slowly, blocking on `read` many times unnecessarily.

It seems that `read` is waiting for more input while this should not be the case.

cc @sorawee

**Comment by rmculpepper** [comment]
The problem is that the worker claims to be ready when its pipe contains *any characters*. When a message is written with a trailing whitespace (like a newline) and consumed by calling `read`, the trailing whitespace remains in the port and so the worker claims to be ready even though it's still processing the previous message. When you call `read-line` first, you consume the newlines so the pipe is empty, so the worker does not claim to be ready.

If you change `send-msg` to the following (note the space after the newline), you can see the same kind of delays even with the `read-line` solution:

    (define (send-msg msg out)
      (fprintf out "~s\n " msg)
      (flush-output out))

**Comment by Metaxal** [comment]
Thanks Ryan.

But then why doesn't `read` block _completely_ instead? (deadlock)

More comments and questions:
* Setting the number of workers to 1 doesn't show the issue.
* `read` consumes leading whitespaces, but not trailing ones I guess?
* replacing `writeln` with `write` doesn't work. Presumably `read` can't read just a symbol as there is no terminating character?
* replacing `writeln` with `write` and `'ready` with `'(ready)` does work indeed.
* Is it possible to use `write` and `read` to send just a single symbol?

**Comment by Metaxal** [comment]
Would the proper solution be to consume whitespaces after `read`, and to indeed add "\n" or a whitespace after writing a symbol or a non-self-delimiting object (such as numbers)?

**Comment by rmculpepper** [comment]
The dispatcher `read` doesn't block forever because the worker always eventually finishes its work and writes a message. More precisely, the following invariant holds: When the dispatcher has selected a worker and is about to read, the worker either has written or eventually will write a message to satisfy the read. The invariant doesn't hold immediately after the read (the message is consumed), but it is restored by the end of the loop body because the dispatcher sends a message, so the worker will eventually send a message in response. The invariant holds on the first iteration because of the worker's initial ready message.

Right, `read` does not consume trailing whitespace. And right, to read a symbol, the reader actually needs to read past the end of the symbol to a separate delimiter character.

I think the simplest solution if you want to use `write` and `read` is to only use *self-delimiting* data (lists, vectors, prefab structs, strings, hashes; not numbers or symbols) as messages. I think writing a fixed whitespace suffix and consuming it would also work, but I would just avoid the extra complexity.

**Comment by Metaxal** [comment]
Ok, thank you very much for the complete explanation.

Simplest solution: just encapsulate the data to read/write into a list.
