### ISSUE TITLE
SICP Picture Language

### ISSUE THREAD

**Issue by UdeshyaDhungana** [racket/racket#4219]
**What version of Racket are you using?**
e.g., 8.4 [cs]

**What program did you run?**
```
#lang racket
(require sicp-pict)
(paint (below diagonal-shading (flip-horiz diagonal-shading)))
```

**What should have happened?**
The docs says that (below p1 p2) produces a painter such that second image is below the first, i.e. p2 is below p1. But, p1 is painted below p2 instead.

**If you got an error message, please include it here.**

**Please include any other relevant details**
e.g., the operating system used or how you are running the code.
OS: MacOS 12.3
Editor: Emacs 27.2

**Comment by sorawee** [comment]
The SICP package is not a part of core Racket, so any issue should be reported to https://github.com/sicp-lang/sicp. That being said, from https://mitpress.mit.edu/sites/default/files/sicp/full-text/book/book-Z-H-15.html#%_sec_2.2.4, it says:

> Similarly, below takes two painters and produces a compound painter that draws the first painter's image below the second painter's image.

So that is a documentation bug and I've fixed it. Thanks for the report!

**Comment by UdeshyaDhungana** [comment]
My pleasure!
