### ISSUE TITLE
Precompiled code that applies struct? to a prefab struct raises an exception

### ISSUE THREAD

**Issue by MartianMoorGrove** [racket/racket#4283]
**What version of Racket are you using?**
v8.5.0.7 on Linux x86_64

**What program did you run?**
After compiling it with `raco make`, I ran a module with this code from the command line:
`#lang racket/base`

`(struct? #s(a 1))`

**What should have happened?**
Return `#t`

**If you got an error message, please include it here.**
`unregistered record type '|(a . 1)| in bytevector`

**Other relevant details**
The error does not occur from prefab structs created with the `struct` form and its `#:prefab` option.
Without compiling, the code runs correctly from both that module and inside the REPL.
The code for the exception appears to be [here](https://github.com/racket/racket/blob/235c86a7512e76143029c3154f2462cd639c66a7/racket/src/ChezScheme/c/fasl.c#L880), implying that this is fasl-related.

**Comment by mflatt** [comment]
Thanks for the report!

The problem is an interaction between optimization and serialization. The code serializer is prepared to handle prefab structure values, but the optimizer changes `(struct? #s(a 1))` to `(struct-type-any-transparent? #<struct-type:a>)`. That is, the result of the `struct?` predicate here doesn't depend on the structure, only its type. (In fact, the call to `struct-type-any-transparent?` could be folded all the way to a boolean at compile time, but the optimizer doesn't figure that out.) The code serializer is not prepared to handle a prefab structure *type*, as opposed to a prefab structure instance.

Some possible repairs are (1) to block the optimizer from constant folding when it would produce a structure type, or (2) to add a new case to code serialization to handle prefab structure types. The latter option seems better.
