### ISSUE TITLE
Trying to trace a function from another module fails with unhelpful message

### ISSUE THREAD

**Issue by sarna** [racket/racket#4330]
This code:
```racket
#lang racket

(require racket/trace)

(trace +)
```
fails with:
```
set!: cannot mutate module-required identifier in: +
```

I'd expect that either to work, or fail with a more friendly message.

My setup:
- Racket v8.5 [cs]
- macOS Monterey 12.4

**Comment by sorawee** [comment]
We can detect this case and error it.

Making it work as intended would be more difficult. I'm stuck on this program:

```
#lang racket

(require racket/trace)

(values (trace add1))
(add1 2)
```

Ideally, we want to expand `trace` to the following program:

```
#lang racket

(require racket/trace)

(define (add1 x)
  (racket:add1 x))

(values (actual-trace add1))
(add1 2)
```

The problem is that `add1` is required to be declared _before_ the `trace` call. Using `syntax-local-lift-module-end-declaration` doesn't work because `add1` would be declared _after_ the `trace` call, so we would get the use-before-definition error.

```
#lang racket

(require racket/trace)

(values (actual-trace add1))
(add1 2)

(define (add1 x)
  (racket:add1 x))
```

Is there a solution for this? Otherwise let's make it an error and call it a day.

**Comment by sorawee** [comment]
Talked to @rfindler, and we reached a conclusion that any attempt to fix this probably is not going to work well, so let's simply disallow it.
