### ISSUE TITLE
Racket BC `--eval` cannot change the current namespace

### ISSUE THREAD

**Issue by sorawee** [racket/racket#4362]
**What version of Racket are you using?**
8.6 [BC]

**What program did you run?**

Consider:

```
;; lang.rkt
#lang racket

(provide (except-out (all-from-out racket)
                     #%top-interaction))
```

```
;; file.rkt
#lang s-exp "lang.rkt"
```

Run `/Applications/Racket\ v8.6.0.2\ BC/bin/racket --repl --eval '(enter! (file "/path/to/file.rkt"))'` and evaluate `1`.

(compare this with running `/Applications/Racket\ v8.6.0.2\ CS/bin/racket --repl --eval '(enter! (file "/path/to/file.rkt"))'` and evaluating `1`).

**What should have happened?**

The behaviors of Racket BC and Racket CS agree. Probably, Racket BC should result in:

```
string:1:0: #%app: bad syntax
  in: (#%app #%top-interaction . 1)
```

But currently it actually evaluates to `1`, even though `#%top-interaction` is not provided.

**If you got an error message, please include it here.**

N/A

**Please include any other relevant details**

N/A

**Comment by sorawee** [comment]
The problem in Racket BC seems to be worse: it always uses its own `#%top-interaction`, even if we provide our own.

**Comment by mflatt** [comment]
The difference here is that BC `--eval` is effectively wrapped with `(parameterize ([current-namespace init-namspace]) ...)`, so the namespace change of `enter!` does not take effect. 

Relatedly, the documentation for `eval` is misleading. The `eval` function parameterizes to set `current-namespace` only when a second argument is provided. So, the difference is that CS implements `--eval` with a single-argument call to `eval`, while BC implements `--eval` with a two-argument call to `eval`.

I hesitate to change BC, because it has always worked that way. I would have preserved the old behavior in CS had I noticed (even though it's worse). But the successful transition to CS suggests that things don't rely on the old bad behavior, and changing BC is a good idea.
