### ISSUE TITLE
DrRacket/Errortrace interference

### ISSUE THREAD

**Issue by MichaelBurge** [racket/racket#4399]
**What version of Racket are you using?**
Apple Silicon 64-bit, tested with versions 8.5 and 8.6

The 8.6 test was with a fresh Racket install.

**What program did you run?**
```racket
#lang racket

(require errortrace)

(module+ test
  (require rackunit)
  (check-equal? #f #t)
  )
```
This program gives me an error when run via DrRacket, in both 8.5 and 8.6:
```
exception raised by error display handler: car: contract violation
  expected: pair?
  given: '#(#<path:/Applications/Racket v8.6/share/pkgs/rackunit-lib/rackunit/private/check.rkt> 137 16 4862 675); original exception raised: car: contract violation
  expected: pair?
  given: '#(#<path:/Applications/Racket v8.6/share/pkgs/rackunit-lib/rackunit/private/check.rkt> 137 16 4862 675)
```

**What should have happened?**
The program runs fine via command line:
```
% raco test deleteme.rkt
raco test: (submod "deleteme.rkt" test)
--------------------

  errortrace...:
name:       check-equal?
location:   deleteme.rkt:8:2
actual:     #f
expected:   #t
--------------------
1/1 test failures
```

So something DrRacket is installing for error tracking interferes with rackunit/errortrace.

**Please include any other relevant details**
OS: macOS Monterey 12.3
CPU: Apple M1 (Mac Mini, 2020)

An even more minimal replication might be:
```scheme
#lang racket

(require errortrace)
(error "foo")
```
which has the same pair/syntax mismatch:
```
exception raised by error display handler: car: contract violation
  expected: pair?
  given: '#(#<path:/Users/mburge/repos/autoprog/racket/deleteme.rkt> 4 0 36 13); original exception raised: foo
  context...:
   .../private/map.rkt:40:19: loop
```

but adding rackunit makes it clearer that there's an issue, since you expect a test failure summary on error reports.

**Comment by sorawee** [comment]
Do you mean 8.5 and 8.6? (6.5 and 6.6 are like ages ago)

I'm pretty sure this is the same issue as https://github.com/racket/drracket/issues/564, which is already fixed. But it looks like the fix didn't make it into 8.6 (but will be in the upcoming 8.7).

One possible workaround is to download a snapshot version (https://snapshot.racket-lang.org/) and use it instead.

But also, DrRacket already integrates with errortrace (this is actually the cause of the bug -- it didn't expect that someone will run errortrace in DrRacket explicitly, since DrRacket is already using errortrace implicitly). You can enable it by going to "Langauge > Choose Language... (potentially > Show Details)" and choose "Debugging".

**Comment by sorawee** [comment]
And FWIW, `(require errortrace)` is probably not going to install errortrace correctly. Read how to use errortrace at https://docs.racket-lang.org/errortrace/quick-instructions.html

**Comment by MichaelBurge** [comment]
Both of my sample programs work in the latest snapshot, so I'll close this issue. Thanks for the quick response!
