### ISSUE TITLE
`sync` doesn't work on windows 11.

### ISSUE THREAD

**Issue by Antigen-1** [racket/racket#4417]
**What version of Racket are you using?**
Racket 8.6 [cs]

**What program did you run?**
The server:
![图片](https://user-images.githubusercontent.com/93880182/187064334-bed9ea72-f037-4dda-ad79-308c5ecb0e86.png)

The client:
![图片](https://user-images.githubusercontent.com/93880182/187064344-eae710ee-f80f-4cca-95c1-ce4e89aeece3.png)

The application of `sync` procedure blocks on windows 11, yet returns on Ubuntu 22.04.

**Comment by mflatt** [comment]
The problem here is more generally that trying to read or peek a byte from the console input port blocks all Racket threads. A simpler example is `(begin (thread (lambda () (sleep 1) (printf "done\n"))) (peek-byte))` which gets stuck instead of printing `done` after 1 second.

I've experimented with different ways of reading from a console, and a comment in the source about `USE_BACKGROUND_THREAD_FOR_CONSOLE_INPUT` describes some trade-offs between the two best methods I've found: 
https://github.com/racket/racket/blob/master/racket/src/rktio/rktio_fd.c#L65. Overall, it doesn't seem like the Windows API for consoles can work for both terminal control as in expeditor (responsible for the syntax coloring shown above) and the Racket thread scheduler as an input port.
