### ISSUE TITLE
Large scientific notation literals crash Racket[CS]

### ISSUE THREAD

**Issue by djholtby** [racket/racket#4466]
**What version of Racket are you using?**
8.5[cs], 8.6[cs]

**What program did you run?**
```
#lang racket

(void #e-1E10000000)
```

**What should have happened?**

Nothing, this should be small enough (as far as bignums go) to fit comfortably into memory.  

**If you got an error message, please include it here.**

From command line (Linux), shows

```
Killed
```

In Dr.Racket, nothing, the Dr.Racket window disappears.

**Please include any other relevant details**

Windows x64 (DrRacket), Linux x64 and AArch64 (command line)

Windows: memory usage hit 24GB before window closed, even though Dr.Racket was set to have a limit of only 128MB.

If the mantissa is 1 instead of -1, it works without issue.

**Comment by samth** [comment]
When I looked into this earlier today, the failure seems to be in the reader.

**Comment by mflatt** [comment]
A little more specifically, it's the `datum-intern-literal` step within `read-syntax`. That step goes wrong due to the way bignums are hashed, plus the fact that interrupts are disabled (as a form of locking) when working with the intern table. Disabling interrupts means that a GC cannot happen, and so memory use can spiral out of control. The solution is to fix the hash function on bignums to have bounded time and space.
