### ISSUE TITLE
Problems with compiling ChezScheme in FreeBSD riscv

### ISSUE THREAD

**Issue by ice051** [racket/racket#4467]
**What version of Racket are you using?**
racket-8.7.0.2

When I compiled ChezScheme, I encountered the following problem. I compiled it twice, but the problem was the same.

Qemu version:
% qemu-system-riscv64 -version
QEMU emulator version 7.1.0
Copyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developers

FreeBSD version:
uname -a
FreeBSD generic 13.1-RELEASE FreeBSD 13.1-RELEASE releng/13.1-n250148-fc952ac2212 GENERIC riscv

Compile with gmake and change gcc in configure file to cc.

Here's what happens later in the output window:

cc -DRISCV64 -I/usr/local/include -I/usr/X11R6/include -Irv64fb/boot/rv64fb -Irv64fb/c -Ic/ -Irv64fb/zlib -Irv64fb/lz4/lib -mabi=lp64d -O2 -D_REENTRANT -pthread -Wpointer-arith -Wall -Wextra -Wno-implicit-fallthrough -o rv64fb/c/clearcache.o -c c/clearcache.c
**c/clearcache.c:48:3: warning: implicit declaration of function '__clear_cache' is invalid in C99 [-Wimplicit-function-declaration]
__clear_cache((char )start, (char )end);
^
1 warning generated.
ar rc rv64fb/boot/rv64fb/libkernel.a rv64fb/c/statics.o rv64fb/c/segment.o rv64fb/c/alloc.o rv64fb/c/symbol.o rv64fb/c/intern.o rv64fb/c/gcwrapper.o rv64fb/c/gc-011.o rv64fb/c/gc-par.o rv64fb/c/gc-ocd.o rv64fb/c/gc-oce.o rv64fb/c/number.o rv64fb/c/schsig.o rv64fb/c/io.o rv64fb/c/new-io.o rv64fb/c/print.o rv64fb/c/fasl.o rv64fb/c/vfasl.o rv64fb/c/stats.o rv64fb/c/foreign.o rv64fb/c/prim.o rv64fb/c/prim5.o rv64fb/c/flushcache.o rv64fb/c/schlib.o rv64fb/c/thread.o rv64fb/c/expeditor.o rv64fb/c/scheme.o rv64fb/c/compress-io.o rv64fb/c/random.o rv64fb/c/ffi.o rv64fb/c/clearcache.o
cc -DRISCV64 -I/usr/local/include -I/usr/X11R6/include -Irv64fb/boot/rv64fb -Irv64fb/c -Ic/ -Irv64fb/zlib -Irv64fb/lz4/lib -mabi=lp64d -O2 -D_REENTRANT -pthread -Wpointer-arith -Wall -Wextra -Wno-implicit-fallthrough -o rv64fb/boot/rv64fb/main.o -c c/main.c
cc -mabi=lp64d -O2 -D_REENTRANT -pthread -o rv64fb/bin/rv64fb/scheme rv64fb/boot/rv64fb/main.o rv64fb/boot/rv64fb/libkernel.a rv64fb/zlib/libz.a rv64fb/lz4/lib/liblz4.a -rdynamic -L/usr/local/lib -liconv -lm -lncurses -lpthread
: rv64fb/bin/rv64fb/scheme
running rv64fb/bin/rv64fb/scheme to build rv64fb/s/cmacros.so
failed
in build-one
in loop
in module->hash
make: *** [Makefile:10: build] Error 1

**Comment by mflatt** [comment]
Thanks for the report!

It looks like FreeBSD doesn't yet support icache flushing, and `__clear_cache()` is defined to just crash. For libffi, the temporary workaround is to just not flush the instruction cache:

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=251564

A possibly better repair would be to use a FENCE.I instruction, which has the effect of at least flushing for the current core. There's no guarantee that the Chez Scheme process will stay on that core, though, since the OS may move it. And, of course, it doesn't do anything for other cores.

I don't know whether this is already addressed in FreeBSD 14, but I haven't found anything to suggest that it has been. Commenting out the call to `__clear_cache()` lets the build make progress, but doesn't seem likely to work for very long. So, probably we have to wait on FreeBSD updates.

**Comment by ice051** [comment]
thank you
