### ISSUE TITLE
Failed name resolution leads to internal error

### ISSUE THREAD

**Issue by m4burns** [racket/racket#4470]
**What version of Racket are you using?**
Snapshot 20221023-3ad7af6727 cs

**What program did you run?**
```
#lang racket

(with-handlers
   ([exn? displayln])
   (udp-send-to* (udp-open-socket) "this_does_not_resolve" 1234 #""))

(sleep 1)
```

**What should have happened?**
```
#(struct:exn:fail:network:errno udp-send-to*: can't resolve address
  address: this_does_not_resolve
  port number: 1234
  system error: Name or service not known; gai_err=-2 #<continuation-mark-set> (-2 . gai))
```

followed by a 1 second pause and exit

**If you got an error message, please include it here.**

```
#(struct:exn:fail:network:errno udp-send-to*: can't resolve address
  address: this_does_not_resolve
  port number: 1234
  system error: Name or service not known; gai_err=-2 #<continuation-mark-set> (-2 . gai))
internal error: attempt to deschedule the current thread in atomic mode
  context...:
   body of "/[[[redacted]]]/repro.rkt"
```

**Please include any other relevant details**

Linux, standard DNS settings. Also happens on OS X Big Sur. The internal error seems to occur asynchronously, a short time after `(sleep 1)` causes the main thread to stop running.

**Comment by m4burns** [comment]
The following program doesn't trigger an internal error:

```
#lang racket

(require ffi/unsafe/atomic)

(with-handlers
   ([exn? displayln])
   (udp-send-to* (udp-open-socket) "this_does_not_resolve" 1234 #""))

(end-atomic)
(sleep 1)
```

So it seems failed address resolution can leave atomic mode enabled.

**Comment by m4burns** [comment]
So this happens because `raise-network-error` is called in `call-with-resolved-address` when resolution fails. The `atomically` in `do-udp-send-to` doesn't `(end-atomic)` on exception, so we're left in atomic mode when we get back to the top level.

This could be fixed by calling `end-atomic` before `raise-network-error`, but it's fragile for the `start-atomic` in `do-udp-send-to` to be paired with an `end-atomic` in `call-with-resolved-address`.

**Comment by mxork** [comment]
Was looking at this with @m4burns earlier today.

It does looks like every proc passed to `call-with-resolved-address` consistently calls `end-atomic` before raising, so `call-with-resolved-address` should do the same.

The one-liner fix is up on the PR and tests are passing locally. I'm adding a test case to `racket-test-core`... not sure I know what I'm doing there, but I'll push what I wind up with and accept any feedback.

**Comment by mflatt** [comment]
I think the right repair is to call `end-atomic` before` raise-network-error`. That's what all the other calls to `raise-network-error` do.

A better strategy may be to bundle `end-atomic` and `raise-network-error` somehow, since they're generally paired. Something more like that happens in other places, I think, but it would require a lot of auditing to realign things that way for this particular error function.

I may misunderstand the suggestion, but I doubt that putting the call to `end-atomic` in `call-with-resolved-address` is the right idea. The atomicity requirements on the boundaries to that function are subtle and chosen with care. There could be a better choice overall — but, again, a change would require careful auditing.

I have a build with the addition of `end-atomic` is in progress. Assuming that test pass, I can push it, but I can also leave the PR open in case there's a better approach.

**Comment by m4burns** [comment]
I think @mxork was suggesting the same thing. I can't think of a better overall strategy.

I've seen `attempt to deschedule the current thread in atomic mode` a few times before but haven't been able to reproduce it. That makes me think there are probably similar bugs still around. As a future project, static analysis could be used to determine if control can leave atomic regions without ending atomic.
