### ISSUE TITLE
Using displayln within an ffi callback crashes DrRacket

### ISSUE THREAD

**Issue by wluker** [racket/racket#4475]
Calling displayln within a ffi callback causes DrRacket to crash. I've included a small example that demonstrates the problem. It will run as expected from the command line, but will crash in DrRacket. 

I think I'm using the FFI correctly. From the docs it says that there are no restrictions on the Racket procedure.

>A type created with [_cprocedure](file:///usr/share/doc/racket/foreign/foreign_procedures.html#%28def._%28%28lib._ffi%2Funsafe..rkt%29.__cprocedure%29%29) can also be used for passing Racket procedures to foreign functions, which will generate a foreign function pointer that calls to the given Racket callback procedure. **There are no restrictions on the Racket procedure**; in particular, its lexical context is properly preserved.

**What version of Racket are you using?**
8.6 [cs]

**What program did you run?**
Please see the example code below. It creates a dynamic library from C code, wraps it with the FFI and then calls it. The code runs as expected in the terminal, but it crashes DrRacket.

**What should have happened?**
It should display 1 and return 2.

**If you got an error message, please include it here.**
Crash

**Please include any other relevant details**
OS is ArchLinux

**The example code that exercises the DrRacket crash**

```
#lang at-exp racket/base
#|
Calling displayln within a callback causes a DrRacket crash.

!! The c lib is not reloaded on each run, so DrRacket will
   have to be restarted every time you change the C code. !!
|#
(require racket/format
         dynext/compile
         dynext/link
         dynext/file)

;;;;
;; make the C shared library
;;;;
(define libname "testlib")
(define c-file (append-c-suffix libname))
(define o-file (append-object-suffix libname))
(define lib-file (append-extension-suffix libname))

;; Some C code to allow for racket msg callbacks
(with-output-to-file c-file
  #:mode 'text
  #:exists 'replace
  (λ ()
    (display
     @~a{typedef int (*callback_t)(int);

         int test_it(callback_t f) {
           return f(1);
         }
 })))

;; turn the c code into a shared lib that can be used by the ffi
(current-use-mzdyn #f)
(compile-extension #f c-file o-file '())
(link-extension #f (list o-file) lib-file)

;;;;
;; wrap with FFI
;;;;
(require ffi/unsafe
         ffi/unsafe/define
         ffi/unsafe/define/conventions)

;; wrap the C lib
(define-ffi-definer define-testlib (ffi-lib libname)
  #:make-c-id convention:hyphen->underscore)

(define _callback-t (_fun _int -> _int))
(define-testlib test-it (_fun _callback-t -> _int))

;;;;
;; test the ffi wrapper
;;;;
(define (f x)
  ;; !! this displayln causes DrRacket to crash !!
  (displayln x)
  (+ x 1))

(test-it f)
```

**Comment by mflatt** [comment]
"There are no restrictions" is certainly misleading, and I'll fix that in the documentation.

The intent was to say that the FFI doesn't impose any extra conditions on the representation function, and in particular that closures are allowed (which isn't obvious from the C perspective). However, in a particular use context and given a particular foreign library, there can be all sorts of constraints on unsafe functions to avoid concurrency and memory problems, and that's what's going on here.

Callbacks need to run atomically with respect to Racket threads. Sometimes, that can be accomplished by specifying `#:atomic? #t`, but I/O tends to require synchronization that makes it non-atomic. Your example turns out not to crash in command-line Racket, because `displayln` tends to complete immediately without synchronizing with other Racket threads, but a `displayln` always involves thread synchronization in DrRacket.

To get output from a callback, you can use logging (e.g., `log-error`), because that's safe to use in atomic mode. For more complicated things than just emitting output, and atomic callback normally needs to queue work somewhere to pick picked up outside the callback.

**Comment by wluker** [comment]
Ah, that makes sense. Thanks for the explanation. 

I didn't know about `log-error`, so that will be useful. Thanks.
