### ISSUE TITLE
File recovery actually made me lose my file

### ISSUE THREAD

**Issue by jonathanfvmtl** [racket/racket#4484]
Hi. I wouldn't say it's a bug per se, but I had a computer freeze, so I restarted, and upon restart and reopening my file, I was prompted to recover the file. I shouldn't have done it, because I had saved the file manually anyway so there was nothing to recover, but I did it out of curiosity. The resulting file was pure gibberish, and the file I had manually saved was gone. It wasn't even in my trash or in my /tmp folder. It was just rewritten over by the bad recovery file.

So while this isn't a bug per se, perhaps a better behavior would be to not overwrite the original file or keep a copy of it somewhere? That way, if the recovery doesn't work, at least the previous version can be used? I was doing a homework, and now I have to start over from scratch.

I overall like DrRacket otherwise. It's a great IDE for learning, and it's cool that it can compile into a standalone package.

**Comment by rfindler** [comment]
I'm sorry to hear you lost your work! That's pretty annoying.

Too late now, but probably clicking on the "details" button would have saved the day. Maybe I should (also) make it so that you don't have to click on details somehow (ie improve the GUI). 

If you're curious to see what details would have done, modify (but don't save) your file and then kill DrRacket (without using file|exit). On a mac that's alt-cmd-esc; on windows you can open the task manager, and on linux, just kill -9 the process. Then restart drracket and click that details button to see what I mean.

**Comment by jonathanfvmtl** [comment]
Oh yeah, I see what you mean. Thanks a lot for the response! It's true that
a small overview sample would be nice, or even perhaps a warning if the
recovery and saved file are very different.

**Comment by jonathanfvmtl** [comment]
Or really , upon recovery, renaming the old file so that it's not lost
would seemingly be a simple extra step to help insure no data is lost.

**Comment by rfindler** [comment]
Do you know of a naming convention that would work well? "<orig-filename>-recovered.rkt", perhaps? (That's not the right word, tho!)

**Comment by jonathanfvmtl** [comment]
Some form of timestamp maybe?
-autorec-YYMMDD.rkt

or something like that? Or even some form of version number, such as:

-v01.rkt

That would be shorter, and could be incremented in case of several
recoveries. My main worry about the timestamp would be file name length
limit on some older file systems. But I'm not sure if DrRacket is on use on
many of those.
