### ISSUE TITLE
A conflict between two modules

### ISSUE THREAD

**Issue by Antigen-1** [racket/racket#4485]
**What version of Racket are you using?**
`Welcome to Racket v8.6 [cs].`

**What program did you run?**
I typed 

```
#lang racket/base 
(require racket/contract ffi/unsafe)
```

in the definition window of DrRacket.

**What should have happened?**
Nothing

**If you got an error message, please include it here.**
```
3-unsaved-editor:2:25: module: identifier already required at: -> in: ffi/unsafe also provided by: racket/contract
  #(44 10)
```

**Please include any other relevant details**
The error did not occur in the racket repl.

**Comment by sorawee** [comment]
This is the expected behavior. You can use `rename-in` to avoid the conflict:

```
(require racket/contract
         (rename-in ffi/unsafe [-> ffi-unsafe:->])) ; use ffi-unsafe:-> for -> in ffi/unsafe
```

The fact that the error doesn't occur in the REPL is in fact undesirable. Consider:

```
> (require racket/contract ffi/unsafe)
> (-> integer? integer?)
string:1:0: ->: should be used only in a _fun context
  in: (-> integer? integer?)
```

Here, `->` from `ffi/unsafe` shadows `->` from `racket/contract`, so you can't use it to construct a function contract. It's well-known that [the REPL is hopeless](http://calculist.blogspot.com/2009/01/fexprs-in-scheme.html), so there probably won't be any fix/improvement (while maintaining backward compatibility).

I'm kinda confused by your last comment:

> What is more, identifiers exported from the ffi/unsafe library are not bound when only racket/contract is imported.

Why is this unexpected?
