### ISSUE TITLE
missing optimization for `#2%apply #%vector` 

### ISSUE THREAD

**Issue by samth** [racket/racket#4584]
This program:

```
#lang racket/base
(vector-immutable 1 2 3)
```

Ends up with this after cp0:

```
;; cp0 ---------------------
(lambda (instance-variable-reference.4
         .get-syntax-literal!1.5 .set-transformer!2.6
         print-values3.7)
  (call-with-module-prompt
    (lambda ()
      (#%call-with-values
        (lambda ()
          (let ([vec.8 (#2%apply #3%vector (#3%list 1 2 3))])
            (#3%$vector-set-immutable! vec.8)
            vec.8))
        print-values3.7)))
  (#2%void))
```

which is much slower than it needs to be because of the `apply`. This could be fixed in schemify but I think `cp0` would be more general.

**Comment by mflatt** [comment]
`cp0` covers this, but the problem is that it takes some inlining and propagation steps to get to the `(apply .... (list ....))` combination. If you run `(vm-eval '(run-cp0 (lambda (cp0 x) (cp0 (cp0 (cp0 x))))))` first, for example, then the `apply` is removed.

Changing the implementation of `vector-immutable` to

```
(define vector-immutable
  (case-lambda
   [() (vector->immutable-vector '#())]
   [args (let ([vec (apply vector args)])
           (#%$vector-set-immutable! vec)
           vec)]))
```

turns out to provide enough of a shortcut, but it might be better to force inlining (via `define-inline` plus `define-inline` or similar).
