### ISSUE TITLE
Reboot pathway fails with `#vfl` in `cptypes-lattice.ss`

### ISSUE THREAD

**Issue by jryans** [racket/racket#4601]
I'm trying out the reboot pathway using upstream Chez Scheme on macOS 13.2.1, but it seems to fail due to a recent change:

```

$ chez --version
9.5.8
$ pwd
<repo root>/racket/src/build
$ ../configure --enable-scheme=chez
$ make
...
Configured for machine: ta6osx
== Compile bootfiles
 [At this point, `compile-file` is from the loaded compiler]
...
compiling s/cptypes.ss with output to ../build/cs/c/ChezScheme/xc-ta6osx/s/cptypes.ta6osx
Exception in read: invalid syntax #vfl( before file-position 5213 of #<input port s/cptypes-lattice.ss>; the character position might differ
shell command failed
 in reboot
 in build-one
 in loop
 in module->hash
make: *** [all] Error 1
```

My local repo appears to be up to date (31b33c6ecc216666273e12b1bd99575cb260efcc).

It seems like this was introduced by @gus-massa's recent commit https://github.com/racket/racket/commit/34b48a05fb0f010120516f89d474a5a1f8c47af0, which adds some usages of `#vfl` to `cptypes-lattice.ss`.

**Comment by jryans** [comment]
I made a few attempts at tweaking bits of `reboot.ss` and the list of the build inputs in `build.zuo` to try to address this, but I haven't quite got it yet... I can see that `reboot.ss` has special support to enable reading `#vfl`, but it's seemingly not being used for `cptypes-lattice.ss`.

If anyone has a hint, I am happy to prepare a fix myself. It may help me understand the reboot flow a bit better as well. 🙂

**Comment by mflatt** [comment]
Thanks for the report! The file `cptypes-lattice.ss` is `include`d by another, and the current reader fixup doesn't cover `include`. 

I think this solution is to have `$make-read` (as used by `include`) use `filtered-file->exps`. My initial attempt seems to work, but I'll check more closely.

**Comment by jryans** [comment]
Ah okay, I suspected the `include` was making this case different than the others. Thanks for the detail. 🙂

I was thinking it would be good to add CI coverage for PRs / pushes that downloads stock Chez Scheme and tries the reboot path. I could investigate the CI workflow if that would be useful.

**Comment by mflatt** [comment]
Yes, a CI improvement would be useful. It's probably best to add that in the https://github.com/racket/ChezScheme repo, though.

**Comment by jryans** [comment]
Thanks, I'll take a look. 

Are Racket modifications to Chez Scheme PRed / pushed here (https://github.com/racket/racket) or there (https://github.com/racket/ChezScheme) first (typically)? Just trying to imagine the best place that would offer pre-merge PR feedback for such cases...

**Comment by mflatt** [comment]
Changes happen in both places and get pushed between the repos, so I wouldn't object to PR-triggered checks in both places. There's a lot more testing of Chez Scheme itself in https://github.com/racket/ChezScheme, though, and my guess was that having the test in just one place would be enough.

**Comment by gus-massa** [comment]
Thanks to both for the report and the fix.

---

I'm somewhat confused with all the meta cycles, so I have 6 questions:

* Can Racket create the bootfiles from scratch?  (I think the answer is "yes".)

* Can Chez Scheme create the bootfiles from scratch?  (I thought "no", but now I think "yes".)

* Can Zuo create the bootfiles from scratch?  (I think "no", but last time I cheeked zuo had more features than what I expected.)

The same 3 questions, but about the bootfiles for the upstream version of Chez Scheme.

Bonus question: What about other r6rs implementations?

**Comment by mflatt** [comment]
> Can Racket create the bootfiles from scratch?

Yes, via rktboot.

> Can Chez Scheme create the bootfiles from scratch?

Yes. This is implemented by the "reboot.ss" program in Chez Scheme, which is relatively new compared to rktboot. Since old Chez Scheme versions are more like the current Racket Chez Scheme than Racket itself is like Chez Scheme, reboot is simpler.

For most purposes, rktboot doesn't need to exist anymore. It has fulfilled its job to create an open-source provenance for Chez Scheme boot files, and re-bootstrapping after changing Chez Scheme is just as easy with reboot as with rktboot. But there's also no pressing reason to discard rktboot, and it does provides a path to build from as-close-to-source as possible using only a C compiler (CGC -> 3m -> CS).

> Can Zuo create the bootfiles from scratch? 

No. It would take a *lot* of new Zuo code to do that.

> The same 3 questions, but about the bootfiles for the upstream version of Chez Scheme.

No. One reason is that reboot and rkboot are tied to the Racket branch's record representation. It probably would not be difficult to adapt rktboot and/or reboot, if that was somehow useful.

> Bonus question: What about other r6rs implementations?

Not as crazy as trying to use Zuo, but still a lot of new code.
