### ISSUE TITLE
[Feature Request] Add command-line and script-file from SRFI 193

### ISSUE THREAD

**Issue by lassik** [racket/racket#4665]
**Is your feature request related to a problem? Please describe.**

[racket-extra-srfi-libs](https://github.com/shawnw/racket-extra-srfi-libs) (not written by me) has trouble implementing [SRFI 193 (Command line)](https://srfi.schemers.org/srfi-193/) due to insufficient support from Racket's core. It would help greatly if two fundamental procedures from the SRFI were added to Racket itself. (I apologize if equivalent procedures are already there and I didn't find them.)

While I don't expect SRFIs to be a priority, the simple features in 193 would probably be of more general use to Racket. The SRFI ships with several Scheme implementations and has proven itself convenient for script writing.

**Describe the solution you'd like**

SRFI 193 specifies two fundamental procedures:

* `command-line`
* `script-file`

The `command-line` procedure is a reliable drop-in replacement for RnRS `command-line`. The `command-line` procedure in RnRS is not specified precisely enough to be useful to script writers.

The `script-file` procedure gives the absolute pathname of the currently running script. For example, running `racket foo.rkt` from a Unix shell might give `"/home/xyzzy/foo.rkt"` as the value of `(script-file)`. When not running a script from a source file, `(script-file)` simply returns `#f`.

The other three procedures are merely convenience on top of the fundamentals, and are not as critical:

* `command-name`
* `command-args`
* `script-directory`

**Describe alternatives you've considered**

The alternative is to take no action.

**Do you want to contribute to this feature**

I probably won't have the time and expertise to write code. I can help with testing.

(cc @shawnw, the author of racket-extra-srfi-libs)

**Comment by lassik** [comment]
Here are the hacks racket-extra-srfi-libs is [currently using](https://github.com/shawnw/racket-extra-srfi-libs/blob/e34f9e297ed429de721000b0df65bf595b018602/srfi/193.rkt) to come up with values for `command-line` and `script-file`:

```Racket
(define raw-script-path (find-system-path 'run-file))
(define in-script?
  (or
   (not (equal? raw-script-path (find-system-path 'exec-file)))
   (not (string=? (path->string (file-name-from-path (find-system-path 'exec-file))) "racket"))))

(define absolute-script-path (if in-script? (normalize-path raw-script-path) #f))

(define (command-line)
  (if in-script?
      (cons (path->string raw-script-path)
            (vector->list (current-command-line-arguments)))
      (cons "" (vector->list (current-command-line-arguments)))))
```

**Comment by LiberalArtist** [comment]
I've read SRFI 193 and the most of the archived discussion, and I have to say I find it quite confusing. Could you say a bit more about what functionality you're missing? Also, are you specifically interested in implementing the API of SRFI, or would other means of achieving the SRFI's objectives be helpful? (Or maybe you're interested in both!)

It seems like the main difficulty is determining whether you are "running a script from a source file" or not. I am still not sure confident I've understood what that means, and more fundamentally I'm not clear on why that's a question one would want to ask.

As best as I can tell, the SRFI does *not* ultimately use "script" in the sense of [the definition in John Cowan's comment](https://srfi-email.schemers.org/srfi-193/msg/14185726/), "a mode of operation in which the REPL reads its input from a file", as distinct from an R7RS program.

The definition the SRFI gives is:

> A top-level program run from a source file whose filename is known to the implementation is a *script*. Note that a file being compiled and stored away for later execution is not a script; only a file loaded to be evaluated once immediately is a script. The file may actually be loaded from a compiled cache, as long as the source filename is used to identify it.

"Top-level program" is a defined term, and I think not in the sense a Racketeer might guess ("The top level is hopeless", compatible with John Cowan's definition of "script") nor exactly in any RnRS. Specifically:
> &hellip; the following are considered top-level programs:
> -  A Scheme program turned into a standalone executable.
> - [&hellip;]
> - A file loaded indirectly via a command line evaluate-expression flag (commonly -e).
> - A library or module imported via a command line flag (commonly -m) for the purpose of running that module as a main program.

But at least some of these potential "top-level programs" seem to be excluded by the proviso, "as long as the source filename is used to identify it."

As an example, consider `raco`. I think https://github.com/racket/racket/blob/89a8b08f111f5cd52eb11829603f62431cda89c2/racket/collects/raco/main.rkt is arguably its source file, though there's some room for debate. When I run `$ raco -h` in my shell, I think "the source filename" probably is not "used to identify it". But the actual contents of the file called `raco` in my `PATH` (`/gnu/store/z0a42imbmy6563wvdavapb6c8vbi1s1z-racket-8.8/bin/raco`) are:
```
#!/gnu/store/rib9g2ig1xf3kclyl076w28parmncg4k-bash-minimal-5.1.16/bin/sh
# This script was created by make-mzscheme-launcher

# {{{ bindir
bindir="/gnu/store/f0j2vd8jzfqw9wkchf1aq3288d6w6b3m-racket-vm-cs-8.8/opt/racket-vm/bin"
# }}} bindir

exec "${bindir}/racket" -N "$0" '-G' '/gnu/store/z0a42imbmy6563wvdavapb6c8vbi1s1z-racket-8.8/etc/racket/' '-l-' 'raco/main.rkt'  ${1+"$@"}
```
Here maybe the source file "is being used to identify it". If it makes a difference, on Windows, ` raco.exe` is not a text file, though semantically it does the same thing. (It is a [launcher](https://docs.racket-lang.org/raco/exe.html#%28part._launcher%29) as created by the `launcher/launcher` library or `raco exe` with the `--launcher` flag.)

In this case the `-N` option is used to set the value of `(find-system-path 'run-file)` (`-E` sets `(find-system-path 'exec-file)`), but [the build script I wrote](https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/racket.scm#n621) generated this particular copy of `raco` by running, in essence:
```
racket-vm-cs-8.8/bin/racket --config racket-8.8/etc/racket -l raco pkg install --installation --auto --catalog tmp/src main-distribution
```
So didn't supply `-N`, and I invoked it as `-l raco`, without the `main.rkt`: does it still count as the source filename being "used to identify it" if a know that requiring a collection without a `/` implicitly requires its `main.rkt` file?

For another example:
```
philip@bastet:/tmp/4665$ cat paddle.rkt
```
```racket
#lang racket/base
(displayln "Welcome to Paddle, which is definitely a script!")
(define who-am-i "Paddle")
(define-namespace-anchor ns)
(parameterize ([current-namespace (namespace-anchor->namespace ns)])
  (read-eval-print-loop))
(newline)
(displayln "Bye for now!")
```
```
philip@bastet:/tmp/4665$ racket paddle.rkt 
Welcome to Paddle, which is definitely a script!
> (+ 1 2)
3
> who-am-i
"Paddle"
> (find-system-path 'run-file)
#<path:paddle.rkt>
> (find-system-path 'exec-file)
#<path:/gnu/store/z0a42imbmy6563wvdavapb6c8vbi1s1z-racket-8.8/bin/racket>
> 
Bye for now!
```

Does the SRFI imagine that `(script-file)` would be different in the Paddle REPL than if called in `paddle.rkt`?

When the SRFI says that `(script-file)` "returns an absolute pathname pointing to the **calling script**. &hellip; If the **calling program** is not a script, `#f` is returned." after specifying "a file loaded via `import`[/`require`] (except for a `-m` flag as above)" is not a "top-level program" and therefore not a "script", it almost sounds like the result of `(script-file)` is supposed to depend on the source file in which it textually appears, so that within the same program it might return a string at one call site and `#f` at another. Unlike `command-line`, the SRFI doesn't specify whether `script-name` may be a parameter. Likewise, I find it confusing that "`(command-name)` [r]eturns a friendly version of `(car (command-line))` evaluated in the current lexical environment.". Is it just unfortunate phrasing? Is it suggesting that `(let ((cdr car)) (command-args))` should behave unhygienicly? Or is it saying that there is some lexical environment latent in a source file and that the returned value depends on which file the expression is written in, even within the same program?

**Comment by LiberalArtist** [comment]
Let me try to write a more helpful comment.

If you want to meet the requirement that "Implementations must resolve the absolute pathname of a script before running that script. The script may change the working directory, thereby changing the interpretation of relative pathnames.", try [(find-system-path 'orig-dir)](https://docs.racket-lang.org/reference/Filesystem.html#%28idx._%28gentag._371._%28lib._scribblings%2Freference%2Freference..scrbl%29%29%29) to get "the current directory at start-up, which can be useful in converting a relative-path result from `(find-system-path 'exec-file)` or `(find-system-path 'run-file)` to a [complete path](https://docs.racket-lang.org/reference/Manipulating_Paths.html#%28def._%28%28quote._~23~25kernel%29._complete-path~3f%29%29)." ("Note that for Windows paths, an absolute path can omit the drive specification, in which case the path is neither relative nor complete.") Something like `(path->complete-path (find-system-path 'run-file) (find-system-path 'orig-dir))`.

If you want to find files at runtime relative to some source file, use the [`racket/runtime-path`](https://docs.racket-lang.org/reference/Filesystem.html#%28mod-path._racket%2Fruntime-path%29) library.

For describing a particular source file, see forms like [`quote-source-file`](https://docs.racket-lang.org/syntax/Source_Locations.html#%28form._%28%28lib._syntax%2Flocation..rkt%29._quote-source-file%29%29).
