### ISSUE TITLE
The result of `opt/c`

### ISSUE THREAD

**Issue by Antigen-1** [racket/racket#4696]
**What version of Racket are you using?**
Welcome to Racket v8.9 [cs].

**What program did you run?**
```
> (define test-contract (opt/c (or/c symbol? fixnum?)))
> (procedure? test-contract )
#t
> (test-contract 'a)
#t
> (define test-contract (opt/c (list/c symbol? fixnum?)))
> (procedure? test-contract )
#t
> (test-contract '(a 1))
#t
> (define test-contract (opt/c (or/c symbol? (list/c symbol? fixnum?))))
> (procedure? test-contract )
#f
> (test-contract '(a 1))
; application: not a procedure;
;  expected a procedure that can be applied to arguments
;   given: #<opt-chaperone-contract: (or/c symbol? (list/c symbol? fixnum?))>
; [,bt for context]
> (define test-contract (or/c symbol? (list/c symbol? fixnum?)))
> (procedure? test-contract )
#t
> (test-contract '(a 1))
#t
```

**What should have happened?**
According to the documentation, `opt/c` should have generated contracts that behave identically to its argument, except faster.

**Please include any other relevant details**
`Linux hin-HLYL-WXX9 5.19.0-46-generic #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by sorawee** [comment]
Not all contracts are predicates. I don't know details about `opt/c` (it could be that it's supposed to work as you expect), but it looks like it is functional as far as contract's functionality is concerned:

```
(define test-contract (opt/c (or/c symbol? (list/c symbol? fixnum?))))

;; OK
(define/contract x
  test-contract
  '(a 1))

;; y: broke its own contract ....
(define/contract y
  test-contract
  '(a 1 10))
```

**Comment by rfindler** [comment]
It looks like the fundamental issue here boils down to a flaw in the design of `opt/c`. Specifically, if `opt/c` cannot tell statically that a contract is a flat contract, then it assumes that it is not a flat contract and thus the machinery that turns contracts into predicates does not kick in. In principle, if we added an opter for `list/c` then this example could be made to work, but the underlying flaw in `opt/c` would remain unless more significant work were done.

Also worth pointing out, with this example, because `opt/c` doesn't know about `list/c`, it appears to be about 2x slower to use `opt/c` in this case. Below's a microbenchmark illustrating it.

```
#lang racket/base
(require racket/contract/base)
(define c1 (-> (or/c symbol? (list/c symbol? fixnum?)) any))
(define c2 (-> (opt/c (or/c symbol? (list/c symbol? fixnum?))) any))

(define (time-it c)
  (define f (contract c (λ (x) x) 'pos 'neg))
  (time
   (for ([x (in-range 100000)])
     (f '(x 0)) (f '(x 0)) (f '(x 0)) 
     (f '(x 0)) (f '(x 0)) (f '(x 0)) 
     (f '(x 0)) (f '(x 0)) (f '(x 0)))))

(time-it c1)
(time-it c2)
```

**Comment by rfindler** [comment]
> That's weird.

More details of the implementation of `opt/c`, but that's expected because when `opt/c` doesn't recognize the top-level, it basically doesn't do anything. Whereas in the previous example, it (attempts to) optimize the `or/c` but we get some bailout code that is slow in the transition to the list part of the checking.

**Comment by rfindler** [comment]
FWIW, I think `opt/c` is a good idea and we learned something with the first implementation about how to do it better, but haven't had time to put those ideas into practice to make a better version of it. It is probably best to just avoid it for now. Sorry.....

**Comment by rfindler** [comment]
I'm glad you've had some success with it! Perhaps just using it on specific contracts is the way to go. And I didn't take anything bad in your comments. Best wishes!
