### ISSUE TITLE
Inaccurate doc for PLTSTDERR and PLTSTDOUT

### ISSUE THREAD

**Issue by sorawee** [racket/racket#4778]
**What version of Racket are you using?**
8.10 [cs]

**What program did you run?**

Consider:

```
;; test.rkt
#lang racket

(log-message (current-logger) 'none "abc")
```

**What should have happened?**

The doc states that `PLTSTDERR` is defaulted to `error` and `PLTSTDOUT` is defaulted to `none`. However, `racket test.rkt` produces

```
abc
```

while `PLTSTDERR="error" PLTSTDOUT="none" racket test.rkt` produces:

```
abc
abc
```

Either the doc is inaccurate, or Racket should be adjusted to make both runs output consistently.

**If you got an error message, please include it here.**

N/A

**Please include any other relevant details**

N/A

**Comment by mflatt** [comment]
I think the problem is related to the use of `'none` with `log-message`. I'm surprised that `'none` is accepted there, and I think allowing it was an oversight when sharing a level-parsing function among logger functions.

The repair is probably to fix `log-message` so that it doesn't broadcast `'none` requests at all.
