### ISSUE TITLE
Would you like racket.scheme.org to redirect to racket-lang.org?

### ISSUE THREAD

**Issue by arthurgleckler** [racket/racket#4794]
Many Scheme implementations FOO now have redirects from FOO.scheme.org to FOO.org or equivalent.  Would the Racket folks like such a redirect, too?  I'm happy to put one in place, but I don't want to do it without your permission.

Thanks.

**Comment by spdegabrielle** [comment]
The **Racket** link on https://get.scheme.org/ currently links direct to https://racket-lang.org/.

I believe @arthurgleckler is proposing setting up https://racket.scheme.org/ and having it redirect to https://racket-lang.org/

e.g. https://chez.scheme.org/ redirects to https://cisco.github.io/ChezScheme/


https://get.scheme.org/ :
<img width="858" alt="get.scheme.org" src="https://github.com/racket/racket/assets/108047/4a15d4c4-233e-4570-a066-5d9a5ba860c3">

**Comment by spdegabrielle** [comment]
additional information in comment: https://github.com/schemeorg/schemeorg/pull/29#issuecomment-1765685736

**Comment by rfindler** [comment]
No objection from me (not that I'm the primary maintainer!). Another option to consider is to redirect to [https://docs.racket-lang.org/r6rs/](https://docs.racket-lang.org/r6rs/), so that people who come to Racket looking specifically for Scheme find the standards-compliant part?

**Comment by samth** [comment]
Seems like a fine idea.

**Comment by arthurgleckler** [comment]
> I have created a PR to add links to R5 and R6 implementations in Racket to https://get.scheme.org/ see [schemeorg-community/monorepo#7](https://github.com/schemeorg-community/monorepo/pull/7)

Thanks.  I've merged and pushed that change.

Alas, I'm having trouble getting racket.scheme.org to work properly.  I'll reach out to the volunteer who set up the infrastructure, but I haven't been getting replies from him lately.  I'll let you know once this is working.

**Comment by lassik** [comment]
Hello,

I've been the main person working on scheme.org with Arthur. Most problems can be blamed on me :-) We're trying to set it up so that it's not dependent on any given person.

The current status is:

```
$ host racket.scheme.org
racket.scheme.org is an alias for racket-lang.org.
```

This means you can set up a `racket.scheme.org` virtual host on the Racket server. That virtual host can do whatever you like - probably redirect to the front page or the documentation? You are also free to change what it does at any time without involving Scheme.org maintainers.

Would this arrangement work out for you? We can also set up a HTTP redirect on the Scheme.org server, as we've done for some smaller Scheme implementations, but then you'll have to ask us in case you want to change the redirect later.

If you set up `racket.scheme.org` as a virtual host, you should get a TLS certificate for it (probably via Let's Encypt?) If we host the redirect under Scheme.org, we'll take care of the certificate on our end.

**Comment by spdegabrielle** [comment]
@lassik Since racket.scheme.org is currently returning an error can I suggest the redirect is a good quick interim solution and it is very busy for Racket people right now with RacketCon and a release(8.11) rapidly approaching!

FWIW I don't see the https://racket-lang.org address changing in the immediate future. 

<img width="977" alt="image" src="https://github.com/racket/racket/assets/108047/7e61c9ff-d82f-40ca-b194-33653817bfee">

**Comment by lassik** [comment]
We'll wait for a decision from someone who can speak on behalf of the core team.

There is no rush, and changes can be made later if you want.

**Comment by samth** [comment]
I guess I had been hoping this was something that could work entirely on your end. We run our website through cloudflare which handles the certificates automatically, and I would want the redirect to preserve that.

**Comment by jryans** [comment]
I would have thought the normal thing to do here would be to have `racket.scheme.org` return a 301 redirect to `racket-lang.org`. This appears to be how `guile.scheme.org` and other `<impl>.scheme.org` hosts already function, so surely the same could be done here for Racket...?

**Comment by lassik** [comment]
> I would have thought the normal thing to do here would be to have `racket.scheme.org` return a 301 redirect

Yes. The question is on whose HTTP server the redirect lives.

**Comment by lassik** [comment]
> I guess I had been hoping this was something that could work entirely on your end.

We can make it work entirely on our end.

If you want this, which URL should we redirect to -- the front page https://racket-lang.org/ or something else?

**Comment by samth** [comment]
I think the front page would be best.

**Comment by samth** [comment]
Thanks!
