### ISSUE TITLE
Fail to install racket8.11

### ISSUE THREAD

**Issue by Antigen-1** [racket/racket#4825]
**What program did you run?**
[Unix Source + built packages](https://download.racket-lang.org/installers/8.11/racket-8.11-src-builtpkgs.tgz)
I had removed the original racket installation on my device and successfully built racket8.11 with commands as follows.
```
src $ ./configure --prefix=$HOME/racket
src $ make
```
Then I tried installing racket into the directory specified.
```
src $ make install
```

**What should have happened?**
Racket should have been installed into `$HOME/racket`.

**If you got an error message, please include it here.**
```
*** Error: undoing changes...
copy-file: destination exists
  source path: /home/hin/下载/racket-8.11-src-builtpkgs/racket-8.11/src/cs/c/compiled/home/hin/下载/racket-8.11-src-builtpkgs/racket-8.11/collects/acks/compiled/acks_rkt.dep
  destination path: /home/hin/racket/share/racket/collects/acks/compiled/acks_rkt.dep
  context...:
   /home/hin/下载/racket-8.11-src-builtpkgs/racket-8.11/collects/setup/unixstyle-install.rkt:172:2: loop
   [repeats 2 more times]
   /home/hin/下载/racket-8.11-src-builtpkgs/racket-8.11/collects/setup/unixstyle-install.rkt:219:0: cp*
   /home/hin/下载/racket-8.11-src-builtpkgs/racket-8.11/collects/setup/unixstyle-install.rkt:481:5: loop
   /home/hin/下载/racket-8.11-src-builtpkgs/racket-8.11/collects/setup/unixstyle-install.rkt:469:0: move/copy-tree
   /home/hin/下载/racket-8.11-src-builtpkgs/racket-8.11/collects/setup/unixstyle-install.rkt:583:2
   body of (submod "/home/hin/下载/racket-8.11-src-builtpkgs/racket-8.11/collects/setup/unixstyle-install.rkt" main)
   body of "/home/hin/下载/racket-8.11-src-builtpkgs/racket-8.11/collects/setup/main.rkt"
failed
 in build-one
 in loop
 in module->hash
```

**Please include any other relevant details**
```
uname -a
Linux fedora 6.5.10-300.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Nov  2 20:01:06 UTC 2023 x86_64 GNU/Linux
```

**Comment by mflatt** [comment]
Thank you for the report. I can confirm that the "built packages" source distributions do not work right, and we'll get this fixed.

**Comment by mflatt** [comment]
We are looking at a v8.11.1 release. Meanwhile, this is our candidate patch: https://github.com/mflatt/racket/commit/bed9a444b85951cb83e2b37d07cea2dcadb551b3

**Comment by sorawee** [comment]
Would it be possible to setup a GHA to detect this kind of issue? It doesn't need to run on every push. Perhaps only when there's a push to the `release` branch, or when a workflow is manually triggered.

**Comment by mflatt** [comment]
The current situation is that we have a test that is run manually at release time, https://github.com/racket/distro-build/blob/master/distro-build-test/tests/unix-installer.rkt, and that test did catch the problem. Unfortunately, the release process involves me running this test and actually looking at the result when it finishes a few hours later, and I fumbled that last step for the v8.11 release.

Making the test more automatic would be great. There are two obstacles to include it directly in our regular CI tests:

* it needs a distribution build, not just a Git repo checkout
* it takes a couple of hours to run

Possibly, it would be set up to work in on top of the Snapshot Generation task. A way to manually trigger the test doesn't seem like much of a change, unless that button somehow also removed a bullet from the release checklist (instead of relying on someone to look at the result and not accidentally remove the checklist bullet too early).

**Comment by shhyou** [comment]
@Antigen-1 8.11.1 is released
