### ISSUE TITLE
`read-bytes-evt` from an evdev file fails with EINVAL

### ISSUE THREAD

**Issue by samdphillips** [racket/racket#4853]
**What version of Racket are you using?**
8.9 [cs]

**What program did you run?**
```

;; the size of a `struct input_event` on 64bit Linux
(define size 24)

(define (get-bytes1 size port)
  (read-bytes size port))

(define (get-bytes2 size port)
  (sync (read-bytes-evt size port)))

(define (run get-bytes)
  (call-with-input-file "/dev/input/event8"
    (λ (mouse-input)
      (let loop ([c 0])
        (define data
          (with-handlers ([values (λ (e)
                                  (displayln c)
                                    (raise e))])
            (get-bytes size mouse-input)))
        (loop (add1 c))))
    #:mode 'binary))

(run get-bytes2)
```

170  events are received, and the read gets an `EINVAL` error.

```
170
error reading from stream port
  system error: Invalid argument; errno=22
  context...:
   /usr/local/stow/racket-8.9/share/racket/collects/racket/port.rkt:1244:2: go
```

**What should have happened?**
The program should not have caused an exception.  Using `get-bytes1` in the above does not fail.

**Please include any other relevant details**
OS: Linux

According to Magister Ludi on Discord:
> The Linux evdev kernel driver appears to return this error code (EINVAL) if a read is less than the size of an input event. 

Thanks to @Efimero on Discord for reporting and Magister Ludi for helping diagnose.

**Comment by Efimero** [comment]
It also happened when I tried using 8.11 racket.

**Comment by mflatt** [comment]
The port abstraction provides a stream of individual bytes, and there are various ways that the implementation of file descriptors as ports expects the same from file descriptors.  Since "/dev/input/event8" provides only chunks of bytes for events, it doesn't line up with the port implementation's expectation.

In the example code, `get-bytes1` works accidentally. In the default block-buffering mode, it turns out that `read-bytes` causes Racket CS to ask the file descriptor for a buffer-sized chunk of bytes each time; even though 4096 is not a multiple of 24, it's big enough to hold as many bytes as the file descriptor ever wants to provide, and apparently that's good enough. Even `get-bytes1` doesn't work in Racket BC, because BC's implementation of `read-bytes` turns out to ask for just one byte at first — one of many deficiencies of BC, but in line with the port layer's expectation of file descriptors. CS also turns out to work if you turn off buffering, because the request for 24 bytes does turn into a `read` call for 24 bytes, but that's again just a property the current implementation and not guaranteed (and, again, not the case for BC).

Meanwhile, with CS and get-bytes2`, it turns out that `read-bytes-evt` eventually leads via `peek-bytes-avail!` to a read call that only fills the end of available space in the buffer, which tends to be 16 bytes eventually (after 170*24 other bytes are read). So, that's why it fails.

It seems possible to tweak the CS implementation so that `peek-bytes-avail!` is more like `read-bytes` in its treatment of the buffer, but that adjustment would be fragile. Another possibility would be a buffering configuration that affects the file-descriptor implementation of ports and forces it to ask for only a multiple of N bytes at a time. That seems tricky to maintain for a rare use of ports, though.

Overall, this use of a file descriptor might be better left to the FFI.

**Comment by jjsimpso** [comment]
libevdev is a userspace library for dealing with these devices:
https://www.freedesktop.org/wiki/Software/libevdev/

**Comment by samdphillips** [comment]
Thanks for the feedback @mflatt .

Besides [`libevdev`](https://www.freedesktop.org/wiki/Software/libevdev/), here's a simple wrapper around open, read, and close that will do the basic reading operation.

https://gist.github.com/samdphillips/d355fd9d23fb76a43a7636b0ba070883
