### ISSUE TITLE
Very high chance of collision for hash datatype

### ISSUE THREAD

**Issue by sorawee** [racket/racket#4902]
**What version of Racket are you using?**
8.12 [cs]

**What program did you run?**

```
(set-count
 (set-union
  (for/set ([i (in-range 100000)])
    (equal-hash-code (hash i #t)))
  (for/set ([i (in-range 100000)])
    (equal-hash-code (hash (number->string i) #t)))
  (for/set ([i (in-range 1000)])
    (equal-hash-code (hash (integer->char i) #t)))))
```

**What should have happened?**

The set size should be relatively high (that is, there should be few collisions).

Instead, the result is 16. That is a hash table with 1 association will almost always collide.

**If you got an error message, please include it here.**

N/A

**Please include any other relevant details**

N/A

**Comment by AlexKnauth** [comment]
I think the relevant function would be `intmap-hash-code` in `rumble/hamt-stencil.ss`, but I'm not quite sure because there are other `intmap-hash-code` functions defined in other files

https://github.com/racket/racket/blob/51d92d076740b295977cf9a67548471a96340b08/racket/src/cs/rumble/hamt-stencil.ss#L671-L678

**Comment by AlexKnauth** [comment]
Would it make more sense to improve `intmap-hash-code` for fewer hash collisions, or to change `hash-hash-code` to just remove the special `intmap?` case and just use the same generic hashing that the mutable versions use?

The mutable versions don't seem to have this hash collision problem.
