### ISSUE TITLE
[Feature Request] improve syntax-rules pattern documentation 

### ISSUE THREAD

**Issue by bremner** [racket/racket#4912]
**Is your feature request related to a problem? Please describe.**

Recently I introduced syntax-rules in a class, following https://www.plai.org
A sharp eyed student noticed a typo in one of my examples.

```racket
  (define-syntax my-let*
    (syntax-rules ()
      [(my-let-* () body) body]
      [(my-let-* ([v0 e0] [v1 e1] ...) body)
       (let ([v0 e0])
         (my-let* ([v1 e1] ...) body))]))
```
Imagine our consternation when the the example worked fine. That's not the bug though.
The "bug" is that I stared at the racket language reference for a long time trying to understand if this
was intended behaviour. I can see (now) that it follows from "where each generated-id binds no identifier in the corresponding template" and the fact that id not mentioned again.  Eventually I was pointed to to the R5RS standard and I see Racket behaviour matches that.

**Describe the solution you'd like**

Document the behaviour of ignoring  the first identifier explicitly, rather than relying on (what seems to be) a description of the implementation.

**Describe alternatives you've considered**

If syntax-rules is in some sense deprecated (e.g. "don't use these unless you are porting scheme code"), then please say so.

**Do you want to contribute to this feature**

I've done what I can :)

**Comment by soegaard** [comment]
I think, there is another explanation. 

```
(define-syntax my-let*
```

Here `my-let*` (without the dash) is bound to a syntax transformer.

Then in the last clause of

```
      [(my-let-* ([v0 e0] [v1 e1] ...) body)
       (let ([v0 e0])
         (my-let* ([v1 e1] ...) body))]))
```
the template contains an occurence of `my-let*` (also without a dash),
but that's okay, since `my-let*` is bound.

The surprise came from two typos. 
If you fix one of them, the program is rejected as expected.

Btw: It wasn't until I turned on `racket-xp-mode` that I noticed there were two typos.

<img width="406" alt="image" src="https://github.com/racket/racket/assets/461765/f4a6729a-0e31-41f6-ad36-ba64ad61e00f">

**Comment by bremner** [comment]
I'm not sure I would characterize it as a typo to have the template contain the name of the syntax transformer, but quite possibly I'm misunderstanding something here.  If I add a `-` in the template to make it match the other two, then I get an error there, but it seems to be a different (and straightforward?) issue.

**Comment by soegaard** [comment]
Sorry. The misunderstanding was on my side.

I mistakenly thought this remark referred to your example.
> ... it follows from "where each generated-id binds no identifier in the corresponding template" and the fact that id not mentioned again.

But it was referring to the the documentation of `syntax-rules`.

<img width="723" alt="image" src="https://github.com/racket/racket/assets/461765/77addf92-a1e3-42ba-bf69-cee5cbe84ed5">

But ... if the `generated-id` were bound ... wouldn't your example still work?
[I guess, I am stuck on the conclusion that the surprise was caused by two typos.]

Anyways, the important part of the bug report is:

> Describe the solution you'd like
> Document the behaviour of ignoring the first identifier explicitly, rather than relying on (what seems to be) 
> a description of the implementation.

I agree that making this explicit in the documentation, is a good idea.

**Comment by bremner** [comment]
BTW, the link to R5RS specs I was given is

https://conservatory.scheme.org/schemers/Documents/Standards/R5RS/HTML/r5rs-Z-H-7.html#%_sec_4.3.2

**Comment by bremner** [comment]
I imagine `generated-id` is something gensym like, so no way for it to be bound to the transformer (or anything else?). It's more that the generated syntax-case rule does not include `id`, so it doesn't matter what `id` is.

**Comment by samth** [comment]
I'm not sure exactly what you expected to happen with your typo'd example, but often this kind of surprising behavior is not because of the special treatment `syntax-rules` has for the first element of the form, but because patterns in `syntax-rules` and `syntax-case` (and `syntax-parse` and `match`) are binders, even when they use the same name as something else, and so they match anything at all regardless of spelling.

**Comment by benknoble** [comment]
Does it help to see that one idiomatic version doesn't bother to bind a variable to the match in head position?

```racket
(define-syntax my-let*
  (syntax-rules ()
    [(_ () body) body]
    [(_ ([v0 e0] [v1 e1] ...) body)
     (let ([v0 e0])
       (my-let* ([v1 e1] ...) body))]))
```

Alternately, you could bind it only for the recursion:
```racket
(define-syntax my-let*
  (syntax-rules ()
    [(_ () body) body]
    [(rec ([v0 e0] [v1 e1] ...) body)
     (let ([v0 e0])
       (rec ([v1 e1] ...) body))]))
```

That is, you have _unused variables_ in the original code. Sadly, it doesn't appear that the analyzer I have available (the langserver) flags them, despite usually flagging unused variables.

**Comment by sorawee** [comment]
The latter code `rec` fails with `rec: unbound identifier`.

This is precisely because `[(id . pattern) template]` is transformed to `[(generated-id . pattern) (syntax-protect #'template)]`, so the `id` position is effectively ignored. It won't bind anything.

**Comment by sorawee** [comment]
What about this?
<img width="754" alt="Screenshot 2024-01-25 at 11 14 20 AM" src="https://github.com/racket/racket/assets/9099577/7eb415fa-787e-4cfb-90b4-e1731c4eb7a0">

**Comment by benknoble** [comment]
> The latter code (`rec`) fails with `rec: unbound identifier`.
> 
> This is precisely because `[(id . pattern) template]` is transformed to `[(generated-id . pattern) (syntax-protect #'template)]`, so the `id` position is effectively ignored. It won't bind anything.

Oh, neat. I thought it worked in the REPL, but I was in a rush and you know what they say about the top-level… :)
