### ISSUE TITLE
Fail to cross-compile racket for android.

### ISSUE THREAD

**Issue by Antigen-1** [racket/racket#4923]
**What version of Racket are you using?**
```
racket -v
Welcome to Racket v8.11.1 [cs].
```

**What program did you run?**
I cross-compiled [racket](https://github.com/racket/racket/archive/refs/tags/v8.11.1.tar.gz) with android standalone toolchain.
```
./configure --prefix=$PWD/build --host=aarch64-linux-android31 --enable-racket=racket CC=aarch64-linux-android31-clang
make && make install
```

**What should have happened?**
Racket for aarch64-linux-android31 should have been built successfully and installed into `$PWD/build`.

**If you got an error message, please include it here.**
```
cs/c/local/cs/c/ChezScheme/ta6le/bin/ta6le/scheme -B cs/c/local/cs/c/ChezScheme/ta6le/boot/ta6le/petite.boot -B cs/c/local/cs/c/ChezScheme/ta6le/boot/ta6le/scheme.boot --script cs/c/to-vfasl.ss --xpatch cs/c/ChezScheme/xc-tarm64le/s/xpatch cs/c/ChezScheme/tarm64le/boot/tarm64le/petite.boot cs/c/petite-v.boot
Exception in load: failed for cs/c/ChezScheme/xc-tarm64le/s/xpatch: no such file or directory
failed
 in build-one
 in loop
 in module->hash
```

**Please include any other relevant details**
```
uname -a
Linux 192.168.10.91 6.6.14-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Jan 26 20:12:16 UTC 2024 x86_64 GNU/Linux
```

Besides, for cross-compiling Racket CS, the `--enable-scheme=SCHEME` flag is required, where SCHEME is a Chez Scheme executable which, according to [README.txt](https://github.com/racket/racket/blob/901a31301a49049a911be0b3d2128fedfa1a0014/racket/src/README.txt#L462), does not need to match the Chez Scheme version as used in the Racket being built. I'd installed [Chez Scheme for Racket 8.9](https://github.com/racket/ChezScheme/releases/download/racket-v8.9/chez-scheme-racket-v8.9.tar.gz) so I provided `./configure` with `--enable-scheme=scheme`. But `make` complained about the version of Chez Scheme:
```
cross build needs Scheme with matching version
 in build-one
 in loop
 in module->hash
```
Actually I can go even further without providing `--enable-scheme=scheme`.

**Comment by mflatt** [comment]
Thanks for the report! It appears that the build and the "README.txt" have gotten out of sync as we evolved the way that `--enable-scheme` and `--enable-racket` are used.

The valid options that should work:

* using a matching Chez Scheme version, since the message turns out to be consistent with the current build implementation; you could build a matching version through the "ChezScheme" directory that is part of the Racket source

* using `--enable-racket=auto`, which is probably the easiest way to go; that builds a host Racket and Chez Scheme along the way

I'll update the "README.txt" file with corrections, and I'll also make the build script detect the non-working combination of cross-compilation without `--enable-racket=auto` and without `--enable-scheme=SCHEME`.
