### ISSUE TITLE
--enable-pb fails on s390x (Debian)

### ISSUE THREAD

**Issue by bremner** [racket/racket#4951]
**What version of Racket are you using?**
8.12 

**What program did you run?**
./configure --enable-pb --enable-mach=tpb64b

**What should have happened?**

Ideally, the build should complete or detect some incompatibility. 

**If you got an error message, please include it here.**

building boot files for tpb64b using pb
running cs/c/ChezScheme/pb/bin/pb/scheme to build cs/c/ChezScheme/xc-tpb64b/s/nanopass.so
running cs/c/ChezScheme/pb/bin/pb/scheme to build cs/c/ChezScheme/xc-tpb64b/s/cmacros.so
illegal pb instruction
failed
 in build-one
 in loop
 in module->hash
illegal pb instruction

I will (shortly) be able to provide a full log if someone is interested.

**Comment by mflatt** [comment]
I see that s390x is big-endian, so the problem may be just that `src/ChezScheme/c/version.h` needs some CPP to configure that.

**Comment by bremner** [comment]
@mflatt I guess I would need to do more than just enable PORTABLE_BYTECODE_BIGENDIAN, since that is presumably already enabled by the configure arguments?

**Comment by mflatt** [comment]
It really is a matter of adding

```
#if defined(__s390__) || defined(__s390x__) || defined(__zarch__)
# define PORTABLE_BYTECODE_BIGENDIAN
# define BIG_ENDIAN_IEEE_DOUBLE
#endif
```

to `version.h`. Although `tpb64b` says "big endian", the build is failing at the step of compiling for `pb` to generate `tpb64b` boot files. The `configure` script doesn't currently try to figure this out more automatically.

I'll get this Chez Scheme update into the pipeline. Thanks for the report!

**Comment by bremner** [comment]
With that commit cherry picked onto 8.12, I get farther, but the build still fails:
```
compiler/cm:   finish-compile: /home/bremner/racket-8.12+dfsg1/src/cs/c/embed-boot.rkt
cs/c/racketcs -O info'@'compiler/cm -l- setup --boot ../src/setup-go.rkt cs/c/compiled ignored cs/c/ignored.d ../src/cs/known.rkt ../src/cs/
malformed fasl-object header in scheme
malformed boot file scheme
failed
 in build-one
 in loop
 in module->hash
```

**Comment by LiberalArtist** [comment]
> Although `tpb64b` says "big endian", the build is failing at the step of compiling for `pb` to generate `tpb64b` boot files. The `configure` script doesn't currently try to figure this out more automatically.

For Debian, you may want to use [rktboot](https://github.com/racket/racket/blob/78fef00d4d16a79fdf6ab31924b3a80cadf4b368/racket/src/rktboot/main.rkt) to bootstrap via BC (so you don't have the binary `pb` bootfiles as "sources"), in which case it's possible to build `tpb64b` (or `ta6le`, etc.) without building the C code for `pb` first. That is what Guix has been doing.

> For what it's worth I see the latter behaviour again with ppc64, another tpb64b platform

Guix has been trying to support Racket on powerpc64le (i.e. the little-endian variant). As of Racket 8.11.1, there was a failure in the Chez Scheme test suite, but it's possible that could be because of https://github.com/cisco/ChezScheme/issues/809 / https://github.com/cisco/ChezScheme/issues/813. I haven't dug in deeply, but, just in case it's useful, here's a log: https://ci.guix.gnu.org/build/2824223/log I don't have access to the hardware (I could potentially apply for access if I make time to sort this out), but I could put you in touch with the Guix contributor who's tried to get ppc stuff working, and eventually there will be more logs for my pending update to 8.12.

Even more tangentially, I was reminded of a possible issue about (not) using pbchunk mode for `petite.boot` and `scheme.boot` on pbarch systems: it turned out to be specifically about building Chez directly, but I'll leave a pointer here in the hope of finding it more easily. https://github.com/racket/racket/issues/4456#issuecomment-1316532141

**Comment by bremner** [comment]
Philip McGrath ***@***.***> writes:

>> Although `tpb64b` says "big endian", the build is failing at the step of compiling for `pb` to generate `tpb64b` boot files. The `configure` script doesn't currently try to figure this out more automatically.
>
> For Debian, you may want to use [rktboot](https://github.com/racket/racket/blob/78fef00d4d16a79fdf6ab31924b3a80cadf4b368/racket/src/rktboot/main.rkt) to bootstrap via BC (so you don't have the binary `pb` bootfiles as "sources"), in which case it's possible to build `tpb64b` (or `ta6le`, etc.) without building the C code for `pb` first. That is what Guix has been doing.

I am trying to simplify the debian packaging, so I'll probably just fall
back to BC for the time being, unless using rktboot is a configure switch.

>
>> For what it's worth I see the latter behaviour again with ppc64, another tpb64b platform
>
> Guix has been trying to support Racket on powerpc64le (i.e. the
> little-endian variant).

The little-endian variant seems to build ok on Debian.

https://buildd.debian.org/status/architecture.php?a=ppc64el&suite=experimental

**Comment by bremner** [comment]
@mflatt that built at least once on a s390x porterbox (not exactly the distro build infra, but close). So things are looking up!

**Comment by bremner** [comment]
With the 3 patches from @mflatt 8.12 is building on the Debian s390x autobuilders, so I'm closing this issue.
