### ISSUE TITLE
Cannot marshal value embedded in code

### ISSUE THREAD

**Issue by bdeket** [racket/racket#5008]
**What version of Racket are you using?**
8.13.05 [cs]  and 8.13.05 [3m], both in DrRacket

**What program did you run?**
```
#lang racket/base

(require (for-syntax racket/base))
  (define-syntax (F stx)
    (syntax-case stx ()
      [(_ rules ...)
       (with-syntax ([compiled-rules
                      (datum->syntax stx (cons list (syntax->datum #'(rules ...))))])
         #'compiled-rules)]))

(F 1 2 3)
```

**What should have happened / error message**
Not sure if this is a bug, but CS and BC behave differently.
In BC this just works,
In CS this also runs without any error, but the background expander of DrRacket shows this error:
```
write: cannot marshal value that is embedded in compiled code
  value: #<procedure:list>
```
If this is used across modules in different files at *some* point this leads to a runtime error with a error-trace pointing to 
`... compiler\private\cm-minimal.rkt:853:2: write: cannot...`

This happened for me in the [`print.rkt`](https://github.com/bdeket/rktsicm/blob/041af3e426bb1fb36e62a4cb935f627907b84483/rktsicm/sicm/display/print.rkt) file of my [rktsicm](https://github.com/bdeket/rktsicm) package. Where the file that has the offending `define-syntax` is [`syntax.rkt`](https://github.com/bdeket/rktsicm/blob/041af3e426bb1fb36e62a4cb935f627907b84483/rktsicm/sicm/simplify/simplify.rkt)

An easy fix in this case is to change `list` to `#'list`, but maybe the errormessage could be more helpful pointing to the exact location where things go wrong.

**Comment by bdeket** [comment]
I think this fix for DrRacket makes it worse... If I now have open the above file, no error is reported, but if I require this file from another, I do run into an error that unfortunately still doesn't point me to the offending file/line.
But my main issue was with racket, not DrRacket:

If you `raco make aaa.rkt` the above program, you get:
```
write: cannot marshal value that is embedded in compiled code
  value: #<procedure:list>
  context...:
   C:\Users\bedek\Desktop\RacketCS\App\Racket\collects\compiler\private\cm-minimal.rkt:853:2
   C:\Users\bedek\Desktop\RacketCS\App\Racket\collects\compiler\private\cm-minimal.rkt:822:6
   C:\Users\bedek\Desktop\RacketCS\App\Racket\collects\racket\private\more-scheme.rkt:148:2: call-with-break-parameterization
   C:\Users\bedek\Desktop\RacketCS\App\Racket\collects\racket\file.rkt:590:5
   C:\Users\bedek\Desktop\RacketCS\App\Racket\collects\compiler\private\cm-minimal.rkt:700:0: compile-zo*
   C:\Users\bedek\Desktop\RacketCS\App\Racket\collects\compiler\private\cm-minimal.rkt:633:0: compile-zo*/cross-compile
   C:\Users\bedek\Desktop\RacketCS\App\Racket\collects\compiler\private\cm-minimal.rkt:449:15
   C:\Users\bedek\Desktop\RacketCS\App\Racket\collects\compiler\private\cm-minimal.rkt:435:12: build
   C:\Users\bedek\Desktop\RacketCS\App\Racket\collects\compiler\private\cm-minimal.rkt:406:0: maybe-compile-zo
   C:\Users\bedek\Desktop\RacketCS\App\Racket\collects\compiler\private\cm-minimal.rkt:210:0: compile-root
   C:\Users\bedek\Desktop\RacketCS\App\Racket\collects\compiler\private\cm-minimal.rkt:105:4
   C:\Users\bedek\Desktop\RacketCS\App\Racket\share\pkgs\compiler-lib\compiler\commands\make.rkt:69:0
   body of "C:\Users\bedek\Desktop\RacketCS\App\Racket\share\pkgs\compiler-lib\compiler\commands\make.rkt"
   C:\Users\bedek\Desktop\RacketCS\App\Racket\collects\raco\raco.rkt:41:0
   body of "C:\Users\bedek\Desktop\RacketCS\App\Racket\collects\raco\raco.rkt"
   body of "C:\Users\bedek\Desktop\RacketCS\App\Racket\collects\raco\main.rkt"
```

which does not help in finding the error in the code, if it is supposed to be an error.

**Comment by rfindler** [comment]
I think you're asking for better support for identifying when you've put a 3d value into a syntax object. I don't think we have a general answer for that but it seems possible that there might be a mode to put the expander in that rejects these (and you'd get the error a lot closer to the bug in that case). That seems like a big project, however. Maybe there is an easier idea somewhere?

In any case, I think the change to DrRacket is correctly classified as a bugfix so I'm not really in favor of reverting it.

**Comment by bdeket** [comment]
Sorry, could you explain what you mean with a 3d value?

Regarding this issue, I was surprised that it runs fine, but gives errors when compiling. So I was wondering if it is an error, and if it is, if the error-messages could be more informative.

I didn't want to say that the fix to DrRacket was incorrect, just that it hides this problem even further down the pile.

**Comment by rfindler** [comment]
"3d value" means that there is something that's not a symbol/list/boolean/number (or a few other kinds of values) hiding inside a syntax object. Often this shows up with a function (in this case `list`). Historically, schemes didn't have the best story of for compilation and this issue is one of reasons, as folks would sometimes embed procedures into syntax objects. If you think of a syntax object as a value meant to represent an abstract-syntax tree of another program, then you can easily come to the conclusion that embedding functions into them isn't a good idea (as saving ASTs to disk is generally a good idea and saving arbitrary procedures to disk generally doesn't work very well). We've just taken the "don't do that" point of view, but generally have supported it when it is feasible as people do find it useful for code they don't want to compile. Still, in my mind, it is never a good idea (as you're going to want to compile and save to disk any code that's remotely useful, eventually), so it makes sense to support a mode for the expander that just rules it out. If we had that mode, you'd get an error much closer to the problem in your code and thus be in a better position to understand what's going wrong and find a fix.

Here's an example of 3d code:

```
#lang racket
#lang racket
(require (for-syntax syntax/parse))

(define-syntax (m stx)
  (define (fun-function x)
    (+ (* x 2) x))
  (syntax-parse stx
    [(_ x)
     #`(#,fun-function x)]))

(m (+ 3 3))
```

The result of the macro is an AST with a function application in it, but where the function position literally has a function, instead of having the code for a function. That's what's "3d".

Here's an equivalent way to write that without any 3d values:

```
#lang racket
(require (for-syntax syntax/parse))

(define (fun-function x)
  (+ (* x 2) x))

(define-syntax (m stx)
  (define (fun-function x)
    (+ (* x 2) x))
  (syntax-parse stx
    [(_ x)
     #`(fun-function x)]))

(m (+ 3 3))
```

this time, we compile into a call to a function that exists at runtime, instead of embedding a function from compile-time into the generated code.

Hope this makes some sense!

**Comment by bdeket** [comment]
Thank you very much for the explanation!.

**Comment by soegaard** [comment]
Apropos 3d-values.

Back in the day, a party trick was to make macros that expanded to a cyclic S-expression.
Some evaluators could run these programs. Others refused.

Something like:

```
#lang racket
(require racket/shared)

(define ones (shared ([ones (cons 1 ones)])
               (cons 'begin ones)))

(displayln ones)
(eval ones)
```

These days, Racket produces this error:
```
datum->syntax: cannot create syntax from cyclic datum
  datum: #0='(1 . #0#)
```
