### ISSUE TITLE
The compiler fails to generate foreign function statically.

### ISSUE THREAD

**Issue by Antigen-1** [racket/racket#5011]
**What version of Racket are you using?**
```
$ raco cross --target x86_64-win32 -M -q racket -v
Welcome to Racket v8.13 [cs].
```

**What program did you run?**
An executable is built with `raco cross --target x86_64-win32 -M -q exe main.rkt` on x86_64 Linux. And it is tested in a Windows 10 virtual machine.

**What should have happened?**
The executable should have worked in exactly the same way as an executable built natively.

**If you got an error message, please include it here.**
`compile: unable to generate foreign function statically: (_fun -> _ulong)`

**Please include any other relevant details**
```
$ uname -a
Linux fedora 6.8.9-300.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Thu May  2 18:59:06 UTC 2024 x86_64 GNU/Linux
```

Besides, this error message seems to be located in [racket/racket/src/schemify/optimize.rkt](https://github.com/racket/racket/blob/28d8723b9ac67d796c967280a11e93876b4a2e61/racket/src/schemify/optimize.rkt#L88).

**Comment by mflatt** [comment]
I don't think you really want `-M` here, and that seems to be part of the problem.

Speculation: Maybe you added `-M` because you got an error about `'ta6nt` when using `raco exe` without a `raco make` before. I have run into trouble with `raco exe` without `raco make` in other cases, and I think the documentation needs improvement there, and `raco exe` should detect the mismatch and encourage `raco make`.

Using `-M` with `raco exe` would mean that the generated executable contains code that is not yet compiled for the target platform, so startup would be very slow. Also, because it's not intended mode for running programs, cross-module optimization is not enabled in that mode; that's almost certainly why static code cannot be generated at the last for the FFI bindings.

**Comment by mflatt** [comment]
On further investigation, I think `raco cross .... exe` was supposed to work without `raco cross .... make`, even if starting with `raco cross ... make` is usually better. It does not look difficult to repair `raco cross ... exe`, so I'll push that repair (for future Racket versions).
