### ISSUE TITLE
`syntax-parse` doesn't preserve properties on literals

### ISSUE THREAD

**Issue by jackfirth** [racket/racket#5064]
**What version of Racket are you using?**
8.14 [cs]

**What program did you run?**

```scheme
#lang racket/base

(require syntax/parse)

(syntax-parse (syntax-property #'when 'foo 42)
  #:literals (when)
  [when #'when])
```

**What should have happened?**

The resulting syntax object should have the property `'foo` set to 42.

**Please include any other relevant details**

It's a bit fuzzy whether this is a bug or just a different design choice. `syntax-parse` currently decides that when matching a literal named `foo`, the name `foo` should _not_ be defined as a pattern variable bound to the matched syntax. Instead, using `foo` in an output template produces a fresh usage of `foo` that's unrelated to the original use. This causes some problems for me in Resyntax because 1) I'm attaching extra properties to the input syntax objects, and 2) I'm rearranging a lot of code in ways where I need to keep track of which output syntax objects were left unchanged from their inputs. I've gotten around this so far by using `~and` to preserve the original identifier like this:

```scheme
(syntax-parse (syntax-property #'when 'foo 42)
  #:literals (when)
  [(~and when when-id) #'when-id]
```

But I often forget to do this, and doing it all the time is pretty excessive. Can `syntax-parse` be changed to include bindings for the original uses of literals? Possibly as an opt-in mechanism, if doing it by default would break things?

**Comment by rmculpepper** [comment]
It is intentional that literals do not bind a pattern variable by default. The main obstacle is that literals can occur multiple times in a pattern, but that is disallowed for pattern variables (except for disjunctions). For example, consider this transformation:
```
(when X (when Y . Body)) => (when (and X Y) . Body)
```
There's one `when` in the right-hand side. Does it correspond to one of the left-hand side `when`s? Is it a fresh `when`? Should the left-hand side `when`s be merged somehow? Literals can be used at varying ellipsis depths, too, which further complicates the issue.

`syntax-parse` currently allows declared literals to be used as if they were syntax classes, so you could also write your example as
```
(syntax-parse (syntax-property #'when 'foo 42)
  #:literals (when)
  [w:when #'w])
```
I've considered making `syntax-parse` also accept Redex-style pattern variables (`stxclass_suffix`, like `expr_rhs` or `when_1`), which might make examples like this more readable.

**Comment by jackfirth** [comment]
> `syntax-parse` currently allows declared literals to be used as if they were syntax classes, so you could also write your example as
> 
> ```scheme
> (syntax-parse (syntax-property #'when 'foo 42)
>   #:literals (when)
>   [w:when #'w])
> ```

Whoa, is that documented anywhere? That definitely helps.

**Comment by rmculpepper** [comment]
It's documented in [1.5.1 Syntax Patterns](https://docs.racket-lang.org/syntax/stxparse-patterns.html#(part._stxparse-patterns)) in the grammar and in [1.5.1 Single-term patterns](https://docs.racket-lang.org/syntax/stxparse-patterns.html#(part._.Single-term_.Patterns)) under the `id` form.

**Comment by jackfirth** [comment]
That approach definitely solves my issue.
