### ISSUE TITLE
(string-contains? ...) has inconsistent input order

### ISSUE THREAD

**Issue by Heuzi** [racket/racket#5069]
This is a repost of "string-contains has inversed parameters in documentation #3356 " but I think it wasn't properly discussed/solved.

If using beginning student language, by default, the system uses:

(string-contains? sub-string full-string)
![image](https://github.com/user-attachments/assets/880f1533-2dcd-4251-a88c-8a41b0858574)

But this is inconsistent with some of the documentation:

![image](https://github.com/user-attachments/assets/3e6df9da-7e57-4ef7-a5d9-24646e0a8ef4)
![image](https://github.com/user-attachments/assets/e11a6c76-622a-4a2f-b89d-e4ed03ec24c7)

The images are screenshots of:
https://docs.racket-lang.org/reference/strings.html#%28def._%28%28lib._racket%2Fstring..rkt%29._string-contains~3f%29%29
https://docs.racket-lang.org/htdp-langs/beginner.html#%28def._htdp-beginner._%28%28lib._lang%2Fhtdp-beginner..rkt%29._string-contains~3f%29%29

I understand the different (string-contains? ...) actually come from different packages. The inconsistency is unnecessarily confusing.

**Comment by gus-massa** [comment]
To add some confussion

    (regexp-match? "l" "apple.scm") ;==> #t

**Comment by shhyou** [comment]
Closing because no fixes are available, unless there is a "Student Languages only" distribution.

1. My current action is to tell the students to use Blue Boxes at the top-right corner and/or _"View documentation ..."_ from the pop-up menu.
2. The doc search page currently shows "HtDP" from #5080 as of v8.15 which is an improvement.
