### ISSUE TITLE
the signature for "set-map" is inconsistent with the rest of racket.

### ISSUE THREAD

**Issue by LewisAndrewCampbell** [racket/racket#663]
the map functions for lists, vectors and streams all take a procedure as their first argument:

    > (map add1 '(1 2 3))
    '(2 3 4)
    > (vector-map add1 #(1 2 3))
    '#(2 3 4)
    > (stream-map add1 (stream 1 2 3))
    #<stream>

 set-map, however, takes it as its last argument  - and also returns a list

    > (set-map (set 1 2 3) add1)
    '(4 3 2)

weird behaviour. It should be 

    > (set-map add1 (set 1 2 3))
    (set 4 3 2)

**Comment by harrisi** [comment]
There are two parts to this. First, the order of the parameters. Second, the behavior of `set-map`.

First:

It does seem unfortunate that the signature for `set-map` is opposite of other `*-map` functions, but it seems consistent with other `set-*` functions (such as `set-for-each`). At this point, it seems like a bad idea to change it to swap the two parameters. I don't think there's any solution or change necessary for this.

Second:

`set-map` returning a list may be better off returning a set, but I don't know the best way to go about this. Internally, it seems like [`set-map` is really](https://github.com/racket/racket/blob/master/racket/collects/racket/private/set.rkt#L456) just [calling `map` through `list-map`](https://github.com/racket/racket/blob/master/racket/collects/racket/private/set.rkt#L46)*. I don't know if this is undesired behavior, however. Perhaps it should wrap the returned list in a call to `set`, but, again, it's a bit late for that. If that's the behavior needed, one can just do `(set (set-map (set 1 2 3) add1))`, as much as that might seem superfluous.

*: The actual code running in this case might be [`fallback-map`](https://github.com/racket/racket/blob/master/racket/collects/racket/private/set.rkt#L218); I'm unsure, but they both have the same behavior.

**Comment by lexi-lambda** [comment]
It is unfortunate that the various collections functions in Racket are confused, but it’s worth noting that this behavior isn’t even specific to sets. The `hash-map` function frustratingly always produces a list, especially annoying given that it is often reasonable to simply want to map over values. Less obviously wrong but perhaps even more dangerous due to its subtlety, `vector-map` will always produce mutable vectors even when the input vector is immutable.

The ship has unfortunately sailed on the consistency of Racket’s current collections APIs. It is something that should almost certainly be thoroughly reassessed whenever such an overhaul is possible, but currently, the APIs are probably doomed to be a little rough in places.

I won’t plug the generic collections package too hard, given that I am its author, but if you are frequently feeling this kind of pain, give it a look: it was more or less specifically designed to accommodate this kind of problem.

**Comment by samth** [comment]
This is indeed inconsistent, but it's not something that can change at this point, since we don't want to break code that uses any of these functions. I agree with @lexi-lambda that the best way forward is to build new libraries with nicer interfaces, and use them in new code you write.
