### ISSUE TITLE
[Honu] Error highlightning in DrRacket

### ISSUE THREAD

**Issue by soegaard** [racket/racket#693]
The program

  #lang racket
  (+ 1 "x")

will when run in DrRacket color the expression (+ 1 "x") red.

The corresponding Honu program doesn't color the offending expression:

   #lang honu
   1+"x"

**Comment by harrisi** [comment]
It seems like the problem is that it doesn't highlight contract violations, but other errors are correctly highlighted. For example:

```
#lang honu
1 + x
```

x is highlighted (unbound identifier error), but if it's just a contract violation (such as your example), there is no highlighting. I have no idea how to fix this. I am not sure where such highlighting or error reporting or what would live in Honu/DrRacket.

Although not specifically related to this error, I propose this issue is moved to the [racket/honu](/racket/honu) repository to go along with racket/honu@e0967c070f27e7afcc44d81dc4970baceb8f5c6c

**Comment by samth** [comment]
This issue was moved to racket/honu#17

**Comment by samth** [comment]
Moved!
